### ISSUE TITLE
gzip: Too many levels of symbolic links

### ISSUE THREAD

**Issue by jfourquet2** [nextflow-io/nextflow#1009]
Hello,
I have an issue with a nextflow process which the goal is to compress with the gzip command a .fastq file.

## Bug report 
```
process gzip_test {

  tag "${replicateId}"
  publishDir params.outdir, mode: 'copy'

  input:
  set replicateId, file(reads_R1), file(reads_R2) from reads_ch

  /*output:
  set replicateId, file("${reads_R1}.gz"), file("${reads_R2}.gz") into reads_gzip_ch*/

  script:
  """
  gzip ${reads_R1}
  """
}
```

### Expected behavior
gzip *R1.fastq files

### Program output 
Command error:
  gzip: fileR1.fastq: Too many levels of symbolic links

### Environment 

* Nextflow version: 19.01.0
* Operating system: Linux

Thanks a lot !

**Comment by pditommaso** [comment]
This is a problem with gzip command, not NF.

**Comment by jfourquet2** [comment]
Ok, thanks for your answer !

**Comment by pditommaso** [comment]
Change in the task work dir and run `bash .command.run` to troubleshoot it.

**Comment by jfourquet2** [comment]
Ok, I will try ! Thanks !

**Comment by lwratten** [comment]
Hi,
I have a similar issue running gunzip that I posted about on nf-core help channel.
I need to unzip files in my nf script before calling samtools faidx, so am trying to use gunzip.
I have tried passing the file object, as well as a string but both give the same error:

`gzip: Homo_sapiens.GRCh37.87.gtf.gz: Too many levels of symbolic links`

Small example looking something like this:
```
process wget_files {
    input:
    val fasta_addr from fasta_ch
    val gtf_addr from gtf_ch

    output:
    file("*.gz") into wget_gz

    script:
    """
    wget $fasta_addr
    wget $gtf_addr
    """
  }
 process wget_gunzip {
    input:
    file zip from wget_gz

    script:
    """
    gunzip $zip
    """
  }
```
Like you said in the solution I navigated to the working directory and ran the command in command.run. This worked fine with no errors when I did it manually, I only get errors in the nf context.

This issue was avoided by using `readlink` on the nf file object before passing into the gunzip command.
```
  process unzip {
    echo true
    input:
    file sym_zip from gz_file_ch

    // output:
    // file "*.fa" into fa_ch
    // file "*.gtf" into gtf_ch

    script:
    real_zip = "readlink ${sym_zip}"
    """
    gunzip -k \$(${real_zip})
    """
  }
```

**Comment by apeltzer** [comment]
`gunzip -f ...` worked as well 👍
