### ISSUE TITLE
Allow partition (queue) to be specified for SLURM executor

### ISSUE THREAD

**Issue by dctrud** [nextflow-io/nextflow#101]
On SLURM a 'partition' is equivalent to a 'queue' in other batch systems. At present, nextflow does not use the `process.queue` setting in `nextflow.config` or the `queue' directive in workflow processes to specify the partition used in submitting jobs to SLURM.

Partition is usually specified with the -p / --partition option to sbatch: 

https://computing.llnl.gov/linux/slurm/sbatch.html

> -p, --partition=\<partition_names\>
> Request a specific partition for the resource allocation. If not specified, the default behavior is to allow > the slurm controller to select the default partition as designated by the system administrator. If the job > can use more than one partition, specify their names in a comma separate list and the one offering  > > earliest initiation will be used.

It would be great to have the `queue` value in nextflow used to select a SLURM partition.

**Comment by pditommaso** [comment]
Hi David, thanks a lot for suggesting that. 

I've just uploaded a snapshot adding the support for SLURM partitions. Would you like to give it a try? 

Since this is an unreleased version, to download and run it you will need to prepend the nextflow command line with the `NXF_VER=0.17.1-SNAPSHOT` variable. For example: 

    NXF_VER=0.17.1-SNAPSHOT nextflow run <script name> ...

**Comment by dctrud** [comment]
Hi - sorry for the delay verifying this. If I set e.g.

```
process.queue = 'super'
```

... then it works nicely. However, should I be able to use a queue directive in a process in the .nf? If I have..

```
process bwa_aln {

    queue: 'super'

    input:
    file fastq_file from fastq
    file index_path
```
... then it's still submitting into the SLURM default queue, not 'super'.

Thanks!

**Comment by pditommaso** [comment]
Because you don't need to to use the colon character. So it should be `queue: 'super'`. 

Alternatively you can defined it in a [nextflow.config](http://www.nextflow.io/docs/latest/config.html#configuration-file) file using the assignment operator. For example the content of the config file would be :

    process.executor = 'slurm'
    process.queue = 'super'

**Comment by pditommaso** [comment]
Included in version `0.17.1`

**Comment by ewels** [comment]
Hi @pditommaso 

> Because you don't need to to use the colon character. So it should be `queue: 'super'`.

Did you mean this?

> So it should be `queue 'super'`.

Otherwise, I'm confused :)

**Comment by pditommaso** [comment]
Oops, yes sorry there's a typo in the comment, I'm just removed it.

To recap, in the process script directive are in the form `name value`, while in the config file `name = value`

**Comment by ewels** [comment]
Ok, that's better - thanks! :+1:
