### ISSUE TITLE
"Unknown executor name: ignite" when executor set from ~/.nextflow/config

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nextflow#118]
Specifying `process.executor = 'ignite'` as arguments to `nextflow run` works perfectly, but setting the same options in the nextflow configuration file does not seem to work. Logfile: [nextflow.log](https://github.com/nextflow-io/nextflow/files/173236/nextflow.log.txt).

```
$ cat ~/.nextflow/config 
cluster {
        join = 'path:/data'
}

process.executor = 'ignite'

$ # Executor specified directly as an argument to nextflow (works)
$ nextflow run hello -process.executor ignite
N E X T F L O W  ~  version 0.17.3
Launching 'nextflow-io/hello' - revision: 1b3a2ae053 [master]
[warm up] executor > ignite
[3a/745fc7] Submitted process > sayHello (1)
[90/a943b8] Submitted process > sayHello (2)
[c9/23b97e] Submitted process > sayHello (4)
[32/92998a] Submitted process > sayHello (3)
Bonjour world!
[bf/6acb77] Submitted process > sayHello (5)
Ciao world!
Hello world!
Hola world!
Γεια σου world!

$ # Executor specified in config file (fails)  
$ nextflow run hello
N E X T F L O W  ~  version 0.17.3
Launching 'nextflow-io/hello' - revision: 1b3a2ae053 [master]
ERROR ~ Unknown executor name: ignite

 -- Check script 'main.nf' at line: 6 or see '.nextflow.log' file for more details

$ # Executor specified as environment variable (fails)  
$ NXF_EXECUTOR='ignite' nextflow run hello
N E X T F L O W  ~  version 0.17.3
Launching 'nextflow-io/hello' - revision: 1b3a2ae053 [master]
ERROR ~ Unknown executor name: ignite

 -- Check script 'main.nf' at line: 6 or see '.nextflow.log' file for more details
```

**Comment by robsyme** [comment]
It looks like ignite is absent from the list of Executors defined in [ProcessFactory.groovy](src/main/groovy/nextflow/processor/ProcessFactory.groovy#L52-L64)

**Comment by pditommaso** [comment]
I know this could appear a bug from a user perspective, however is something a bit more tricky. The problem is that by default the nextflow package does not include the Ignite dependencies. These are downloaded only if the ignite executor is specified on the command line. 

When defining it in the nextflow config file does not work because nextflow has been already launched, so it's too late to modify the Java classpath with include the required deps (thought using some advanced classloader technique I guess it's somehow possible and needs to be investigated). 

Thus if you want to specify the `Ignite` executor in the config file you have two options: 

1) Download and use the nextflow [*uber* distribution package](https://github.com/nextflow-io/nextflow/releases/download/v0.17.3/nextflow-0.17.3-all) that includes all dependencies including Apache Ignite.   

2) Set the environment variable `NXF_MODE=ignite` in your environment which will force the Ignite package to the downloaded.

**Comment by robsyme** [comment]
Aha. That makes sense. Thanks!
