### ISSUE TITLE
publishDir does not handle hard linking of directories 

### ISSUE THREAD

**Issue by matanhofree** [nextflow-io/nextflow#126]
publishDir does not handle files which can not be linked. One simple solution would be to create directories in the destination instead of linking. 

I believe the current code also does not test if a hard link can not be created (as in across disk boundaries).  It might make sense to have a link or copy mode.

**Comment by pditommaso** [comment]
I think you are right, currently it only checks if it's the [same file system](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/processor/PublishDir.groovy#L279-279) otherwise it froces a `copy`instead of a `symlink`. It should be improved to check also if it's a different disk. 


> One simple solution would be to create directories in the destination instead of linking.

I'm not getting this. Could you make an example?

**Comment by pditommaso** [comment]
Fixed as suggest by @matanhofree. Thanks.
