### ISSUE TITLE
SGE job array -- Unable to acquire lock on session with ID

### ISSUE THREAD

**Issue by wynstep** [nextflow-io/nextflow#1300]
Hi everyone,
I do have a problem that I hope you can help me in sorting out. I am trying to launch the same Nextflow pipeline in a serial job array. I already setup
` process.executor='sge'
process.clusterOptions='-pe smp 8 -l mem=30G,tmpfs=100G,h_rt=48:0:0'`
in my config file without success.
The first job of the array starts without errors but from the 2nd to the Nth, I receive the error message:

`Unable to acquire lock on session with ID b2e492c4-ac9c-4d43-b89b-f8affc68afa4

Common reasons of this error are:
 - You are trying to resume the execution of an already running pipeline
 - A previous execution was abruptly interrupted leaving the session open

You can check what process is holding the lock file by using the following command:
 - lsof /scratch/scratch/TABS/.nextflow/cache/b2e492c4-ac9c-4d43-b89b-f8affc68afa4/db/LOCK`

Any suggestion?
Thanks

**Comment by pditommaso** [comment]
Each instance needs to be launched in its work directory.

**Comment by wynstep** [comment]
Many thanks for your reply. I'll give a try and come back fro the feedback. Could I suggest to add an additional flag for selecting the cache directory (as for the work dir and reports)?

**Comment by pditommaso** [comment]
That files need to be in the launch directory because that's the place where related commands are expected to be executed. Moving around than the user should specify each time the cache files, turning into a mess.

**Comment by rkendar** [comment]
Hi Paolo,

I have the same problem. And after I read these articles:

> https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html https://www.nextflow.io/blog/2019/troubleshooting-nextflow-resume.html

Seems like the reason is because I changed the input file (same content, but I changed the file name). Am I right it can caused the problem? If yes, is that okay if I just delete the LOCK and resume the pipeline (the pipeline wasn't abruptly interrupted)?

And the article mentioned that:
> "Note that you should avoid launching two (or more) Nextflow instances in the same directory concurrently"

Does it mean I cannot do array job for the same nextflow script but different working folder?

Thank you.
