### ISSUE TITLE
Process hangs for non-zero exit status

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1344]
### Expected behavior and actual behavior

Nextflow does not "notice" that a process finished with an error status and hangs forever in a waiting mode.

### Steps to reproduce the problem

It is difficult to reproduce because I got this problem with certain dockerized applications in kubernetes and was unable to find what was the differencee that made the difference. However I managed to copy .command.ru and .command.sh locally and with minimal changes (paths changed to current directory) I got very similar results. The difference is that on kubernetes it hangs forever while on my local machine it takes around 12 seconds. I have attached the problematic .command.run and .command.sh to this report. To reproduce: change content of .command.sh from "exit 0" to "exit 1" and observe execution time of .command.run. It will be either 0 or 12 seconds.

Generally it looks like a problem in the generated .command.run file in the mechanism that handles exit status  (non-zero error codes).

[bug.zip](https://github.com/nextflow-io/nextflow/files/3761288/bug.zip)

### Environment 

* Nextflow version: 19.09.0-edge (docker)
* Operating system: Linux

### Additional context

Problem spotted on Kubernetes, partially reproduced on Ubuntu 18.04.

**Comment by pditommaso** [comment]
This was a tricking one, the first problem was that when the script returns a non-zero exit status the `nxf_mem_watch` survives the error condition due to the [true fallback](https://github.com/nextflow-io/nextflow/blob/3bc5c5f7df7e0da1c6f9fe85dac15f1b65efc0d0/modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt#L1070). The second issue was that the `nxf_date` was returning an invalid timestamp on some linux distribution (seconds instead of millis) and therefore the watch process was waiting much longer than expected resulting in the process hang.
