### ISSUE TITLE
Process fails not handled properly when using singularity and timeline

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#1380]
### Expected behavior and actual behavior

If a process fails because of some error, and you're  using singularity and with-timeline, rather than failing with the appropriate error message, the workflow hangs writing endlessly to .command.err

### Steps to reproduce the problem

Run

`nextflow run see.nf -with-singularity 'docker://quay.io/h3abionet_org/imputation_tools'  -with-timeline`

(seems to be independent of the actual image)

As can be seen the workflow should fail because the input file is nonsense. If you omit either the `-with-singularity` or the `-with-timeline` option it does behaves properly, but with both present it does not

```
#!/usr/bin/env nextflow
target=Channel.fromPath("see.nf")
process split_target_to_chunk {
    input:
        file target
    output:
    script:
      file("*tbi")
    """
        bcftools index --tbi -f ${target}
    """
}
```
### Program output 

There is no output. The job launches and it hangs.

The `.command.run` script never terminates -- script appears to lose all   its paths and goes into an endless loop writing hundreds of MB to `.command.err` before the error is detected.

The file dot-command.txt is the first few lines of  `.command.err`, dot-nextflow.txt is the contents of `.nextflow.log`

[dot-command.txt](https://github.com/nextflow-io/nextflow/files/3852009/dot-command.txt)
[dot-nextflow.txt](https://github.com/nextflow-io/nextflow/files/3852011/dot-nextflow.txt)

### Environment 

* Nextflow version: version 19.10.0 build 5170
* Java version: OpenJDK Runtime Environment (build 1.8.0_232-b09)
* Operating system: Linux CentOS 7.7.1908

### Additional context

(None)

**Comment by pditommaso** [comment]
Just tried to replicate it the `.command.err` contains the expected error: 

```
index: "see.nf" is in a format that cannot be usefully indexed
```

Try to debug the task running `bash -x .command.run` in the task work dir.

**Comment by shaze** [comment]
Hi Paolo

Thanks for looking at it.

The same problem occurs.

Doing some debugging in the `.command.run` script I found the following 

```
nxf_container_env() {
cat << EOF                                                                                                              
export PATH="/home/jb/bin:\$PATH"                                                                              
EOF                                                                                                                     
}
```

If I delete that export line, then there is no problem when I run `bash -x .command.run`. 

I am uploading the result of `bash -x` in two cases. `ok.txt` is the result of running `bash -x .command.run` produced when I ran nextflow without the `-with-timeline` option.  The workflow gives the expected results.  The `bad.txt` is the result of running `.command.run` produced with the  `-with-timeline` optioni -- and here the workflow hangs.

[bad.txt](https://github.com/nextflow-io/nextflow/files/3857128/bad.txt)
[ok.txt](https://github.com/nextflow-io/nextflow/files/3857129/ok.txt)

**Comment by pditommaso** [comment]
Still unable to replicate it. The `export PATH="/home/jb/bin:\$PATH"` is there because either in the config is defined `env.PATH=something` or your project has a `bin/` folder then NF exports that path in the container. 

> If I delete that export line, then there is no problem when I run bash -x .command.run.

But I'm still seeing the PATH export following in the ok log `eval export PATH="/home/jb/bin:$PATH"`

**Comment by shaze** [comment]
Hi Paolo,
Hmm, not sure where to go from here. I am now trying it in my environment. My .command.run file is a little different but otherwise I see the same thing.

I am now uplaoding the .command.run and .command.sh file

To be clear, there is no nextflow.config file in my directory or any of its parent drectories.



When I run it, it looks like the first time `nxf_tree` is called, the behaviour is good but the second time it's called, it can't find any of the files.

I've done a little instrumenting of the file (echos etc) and am uploading the output. Note when it fails, it fails with the message "Can't find /usr/bin/which` -- so it knows where `which` should be, but can't find it.

Let me know if I can provide any other help in this. 

Thanks for yoru time
[command-run.txt](https://github.com/nextflow-io/nextflow/files/3892873/command-run.txt)
[command-sh.txt](https://github.com/nextflow-io/nextflow/files/3892875/command-sh.txt)
[command-run-out.txt](https://github.com/nextflow-io/nextflow/files/3892876/command-run-out.txt)

**Comment by shaze** [comment]
As an aside, I've tried with two versions of singularity 3.2.1.1 and 3.4.2-1.1

And running it with docker behaves well

**Comment by shaze** [comment]
I tried this on an Ubuntu machine and couldn't replicate the problem -- all OK there.

I also tried launching a CentOS 7 machine on AWS and install versions of Java, singularity, etc that we use and it worked fine. 

However on our CentOS 7 system (our main production cluster uses this) it reproduces. I tried in a clean account (i.e. minimal environment). I also tried running on a local disk rather than NFS but the problem does not go away. 

This isn't a showstopper for us -- we can just leave off the -with-timeline option and it behaves OK

**Comment by jmfernandez** [comment]
Hi, I have just faced the very same problem in a similar scenario:
- Enabled timeline gathering.
- Step running GATK 3.6 command which fails due a missing index.
- Used Singularity image assembled from [broadinstitute/gatk3:3.6-0](https://hub.docker.com/layers/broadinstitute/gatk3/3.6-0/images/sha256-ba0dfa08ea63999a23d1a057aeef43324189e1e9ec126c53222678c9d0b88059?context=explore)

I have been able to triage this very obscure issue. The problem comes from `/bin/bash` bundled in the image. Compared to other images which did not trigger the bug in case of command failure, the version was different. The one in this container is:

```Singularity> bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I have tested my hypothesis fetching latest statically compiled bash version from https://github.com/robxu9/bash-static . Then I edited generated `.command.run` from the failing step in order to add `-B /path/to/downloaded/bash-linux-x86_64:/bin/bash`, and it worked.

Hope this helps to future people facing the same issue.

PS: I have tried finding some related bug from bash 4.3.30 using Google, and I found next https://lists.gnu.org/archive/html/bug-bash/2015-06/msg00010.html
