### ISSUE TITLE
none flattening version of combine

### ISSUE THREAD

**Issue by ii-bioinfo-thomas** [nextflow-io/nextflow#1403]
## Usage scenario 

As a cartesian product of 2 tuplets, I actually would expect as result a tuplet of tuplets.

We not necessarily know how long the lists are which we combine. E.g. 2 channels with all files of a directory. Combining and forking afterwards is than misleading, since it returns lists of different size which cannot be handled anymore with fork.

## Suggest implementation 

```
left = Channel.from(['A',1], ['B',2], ['A',3])
right = Channel.from(['B','x', '1'], ['B','y'], ['A','z'], ['A', 'w'])

left
.map{it->[it]}
.combine(right.map{it->[it]})
.println()
```

Output:

```
[[A, 1], [B, x, 1]]
[[B, 2], [B, x, 1]]
[[A, 3], [B, x, 1]]
[[A, 1], [B, y]]
[[B, 2], [B, y]]
[[A, 3], [B, y]]
[[A, 1], [A, z]]
[[B, 2], [A, z]]
[[A, 3], [A, z]]
[[A, 1], [A, w]]
[[B, 2], [A, w]]
[[A, 3], [A, w]]
```
Here it's clear that fork expects a tuple of length 2. Only combine would now result in tuple of length 4 and 5, which is difficult to handle.

**Comment by pditommaso** [comment]
The canonical form would be 

```
left = Channel.from(['A',1], ['B',2], ['A',3])
right = Channel.from(['B','x', '1'], ['B','y'], ['A','z'], ['A', 'w'])

left
.combine(right)
.println()
```

which produces: 

```
[A, 1, B, x, 1]
[B, 2, B, x, 1]
[A, 3, B, x, 1]
[A, 1, B, y]
[B, 2, B, y]
[A, 3, B, y]
[A, 1, A, z]
[B, 2, A, z]
[A, 3, A, z]
[A, 1, A, w]
[B, 2, A, w]
[A, 3, A, w]
```

The output you are getting is caused by the fact you are creating a nested tuple.

**Comment by Gullumluvl** [comment]
Hi,

I think the OP was requesting for the output he shows: a non-flattening version of `combine`.

Could we have an option to `combine` in order to call `combine(flatten: false)` and get the desired results? (without having to nest tuples with `map`)

This can't be done with `cross` either, because it only crosses items with a grouping key, which cannot be duplicated in the source channel.

**Comment by MatthewWiens101** [comment]
@pditommaso @bentsherman can we please re-open this issue? As @Gullumluvl noted, OP's original question was not answered, and I second the idea for `combine(flatten: false)`, in fact I just tried it in my own pipeline without success before I found this thread.

**Comment by bentsherman** [comment]
The operator library has a lot of odd behaviors and rough edges like this one. Rather than adding more options and making the operators even more complicated, instead I would like to introduce a "second generation" operator library that provides a small set of simple and easily-composable operators.

For example, instead of having combine/cross/join, which have various niche and overlapping behaviors, I would like to just have a `cross` operator that does a cross product (no implicit matching) and a `join` operator that does a SQL join (no implicit flattening, correct handling of duplicate matches).

Until then, the way to get the cross product of tuples with no flattening is to do exactly what the OP showed:
```groovy
left = Channel.from(['A',1], ['B',2], ['A',3])
right = Channel.from(['B','x', '1'], ['B','y'], ['A','z'], ['A', 'w'])

left
  .map { v -> [v] }
  .combine(right.map { v -> [v] })
  .view()
```

The `each` input indeed does not work with tuples, and it is discouraged anyway in favor of explicit operator logic.

**Comment by joseale2310** [comment]
Hi! Any news or workarounds for this? The workaround works fine if both channels have several lists, but if I would like to combine something like:

```
left = Channel.from(['A',1], ['B',2], ['A',3])
right = Channel.from(['B','x', '1'])

left
  .map { v -> [v] }
  .combine(right.map { v -> [v] })
  .view()
```

I would hope to get this:
```
[['A',1], ['B','x', '1']]
[['B',2], ['B','x', '1']]
[['A',3], ['B','x', '1']]
```
Instead, I get this:
```
[['A',1], 'B']
[['B',2], 'x']
[['A',3], '1']
```

**Comment by Gullumluvl** [comment]
Your problem is unrelated to `combine`. You get this because you are using `Channel.from()` ([deprecated](https://www.nextflow.io/docs/stable/reference/channel.html#from)) instead of **`Channel.of()`**. You can always use the [`view`](https://www.nextflow.io/docs/stable/reference/operator.html#view) operator to ensure your channel contents are what you expect.

**Comment by joseale2310** [comment]
I struggled several hours trying to come up with the solution. Turns out I am just a dumb dumb. Thanks @Gullumluvl!
