### ISSUE TITLE
Auto-generate usage from params in pipeline

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#144]
It would be really useful if the usage information displayed for the -help argument of the run command were to display the available params defined in the pipeline.  This would help make a pipeline a bit more self-documenting.  Given that the params are only defined by name and don't have descriptions or type information associated with the, the usage generated would be minimal, but with good names should at least help.

I'm not familiar enough with the nextflow code so I'm not quite sure how I can easily access the params defined in the pipeline, but if someone can point the way I'd be happy to make the change myself and open a pull request.

**Comment by pditommaso** [comment]
This is a nice idea. Currently parameters are managed by [ParamsMap](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/script/ScriptBinding.groovy#L137-137). This is a map for which the `put` method has been overridden so that entry can be set no more than one time. 

However there are a couple of problems to solve. The first is to find a short and idiomatic way to define parameter descriptions. I could propose two approaches: 

    params.foo = defparam( <actual value>, <description> ) 

or 

    params.foo <actual value>, <description> 

In the first case the method `defparam` would take two parameters, the default value and the parameter description, wrap them in a value object and assign it to the `foo` item in the `ParamsMap` object. 

The second syntax could be implemented as a [dynamic method](http://mrhaki.blogspot.com.es/2009/11/groovy-goodness-create-dynamic-methods.html) taking the same two arguments and wrapping them in a value object as before. 

Frankly I'm not satisfied with none of them. I find the first too verbose while the second one introduces a syntax for parameter definitions that does *not* use `=` operator creating an ambiguity with the standard way to set params. 

Maybe the first choice can be improved using a better method name in place of `defparam`. Any suggestion for that?


Then the second problem is that Nextflow processes the pipeline script in one pass, thus it's not easy to run it only to fetch the parameter definitions, prints the usage text and return without launching the pipeline execution itself. How to implement this needs to be investigated.

**Comment by tseemann** [comment]
+1 for this idea. it is essential to resolve the "one pass" problem to make 'nextflow' usable to generate clean standalone tools transparent to the user.

**Comment by pditommaso** [comment]
@tseemann 
> to generate clean standalone tools transparent to the user

What do you mean?

**Comment by cerebis** [comment]
I think any approach that tries to accomplish this, might as well follow the complete convention and allow more thorough definitions. (type, required, multiple values per-parameter, etc).

It's been done many times in many languages to varying success. Python's argparse is fairly succinct.

**Comment by fmorency** [comment]
+1

**Comment by lucacozzuto** [comment]
+1

**Comment by pditommaso** [comment]
I had an idea to implement a mechanism to procede a pipeline usage/help in a relative easy manner. 

It would possible add an helper method as described above eg:  

```
params.foo = defparam( 1, 'some description here' ) 
params.bar = defparam( 2, 'other description etc' ) 
```

Then it would be possible to add a `params.usage()` method that returns a formatted text containing the description for each parameter specified so far. For example: 

```
if( params.help ) {
  print params.usage()
  return
}
```

to further reduce the boilerplate code it could even be possible to add another method like the following 

```
params.ifHelpPrintUsageAndExit()
```
(maybe a bit verbose .. :))

The only problem is that I don't like the method name `defparam`, other possible names could be: 

a. `addParam` 
b. `setParam`
c. `defParam`
d. `newParam`
 other..  ?

alternatively instead of using the following idiom:

```
params.foo = addParam( 1, 'description' )
```

it could be possibile to add a such method to the `params` object itself. For example: 

```
params.add( 'foo', val: 1, description: 'text here' )
params.add( 'bar', val: 2, description: 'etc .. ' )    
```

But it looks more verbose and less intuitive. 


Comments ?

**Comment by pditommaso** [comment]
cc @emi80 @skptic

**Comment by lucacozzuto** [comment]
Currently I'm using this trick.

I print the values as log.info

log.info "BIOCORE@CRGpipe  ~  version 0.1"
log.info "========================================"
log.info "reads                      : ${params.reads}"
log.info "genome                     : ${params.genome}"
log.info "annotation                 : ${params.annotation}"

and then simply

if (params.help)  exit 1

Luca

**Comment by mes5k** [comment]
I think this has probably been superseded by this ticket: https://github.com/nextflow-io/nextflow/issues/866 and the features in nf-core.
