### ISSUE TITLE
Output Nextflow pipeline tasks in a serializable format for external execution

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1458]
## New feature

It would be very helpful to be able to run Nextflow in such a way that it does not actually execute the pipeline tasks, but instead just evaluates the DAG of the pipeline and generates all the tasks to be run. This is similar to the requests for 'dry run' (https://github.com/nextflow-io/nextflow/issues/844 , https://github.com/nextflow-io/nextflow/issues/31), but with the addition of being able to output the tasks in some kind of serializable format (JSON?) that could be used by a different program.

## Usage scenario 

I want to use Nextflow to figure out all the tasks that need to be run in a given pipeline, and their order of execution, but I need to hand this information off to another system to actually execute the tasks. 

## Suggest implementation 

Implementation of a 'dry run' functionality that serializes the evaluated Nextflow 'task' objects and outputs them to JSON, either in a file or sent via the http web logger.

**Comment by bentsherman** [comment]
This issue is old, but just wanted to say, I doubt we will ever implement a full "dry run" feature that lays out the entire schedule of tasks without executing them, because there is no way to do that under the dataflow programming model. There are a number of things we can do that are similar but not exactly the same:

- stub run: simulate a "hypothetical" pipeline run (doesn't correspond to a real run)
- preview run: compute the workflow DAG without running the pipeline (doesn't include tasks)
- task graph: compute the DAG of all tasks executed in a real (or stub) run (requires the pipeline to be executed)
- dry resume: resume a pipeline and show which tasks will be re-executed without executing them (doesn't cover the entire pipeline)
