### ISSUE TITLE
Add keep-logs to cleanup config setting

### ISSUE THREAD

**Issue by fullama** [nextflow-io/nextflow#1562]
## New feature

`cleanup = 'true'` can be defined as top level setting in the config file but does not allow the possibility of keeping the log files (.command* , .exitcode )

## Usage scenario 

Having`cleanup = 'true'` in the config file is super useful however when some steps are ignored/failed during the workflow everything is still deleted at the end. This makes it impossible to check why those steps were ignored as there are no longer any log files.

## Suggest implementation 

 - Simplest option would be to allow this config setting to keep all log files (like #775)
 - Another option would be to not delete the folder where the step was ignored/failed

..id be willing to try implement this ( if it was wanted ) but some pointers where to start would be good..

**Comment by pditommaso** [comment]
The command `nextflow clean -h` is already doing this. The `cleanup` flag is undocumented feature that may not be supported in the future due to #452 therefore -1 to improve it.

**Comment by fullama** [comment]
#452 seems a lot more involved than what i was suggesting.. but fair enough it would cover it.
if it was possible though just to keep the logs of everything that failed that would be nice..

..ill close this issue so.. Thanks!

**Comment by zichner** [comment]
Hi @pditommaso,

This issue is a few years old but still very relevant from my point of view.
Since the `cleanup` flag has become a documented feature and other cleanup functionalities like #452 are not yet fully implemented, is there some plan to allow to keep log files when setting `cleanup = 'true'`?

Using `nextflow clean -h` is unfortunately not a solution in our case, because it requires that all ours users are executing it all the time and it cannot be enforced through some central Nextflow configuration.

Thank you very much!

**Comment by zichner** [comment]
Thank you very much for your quick response and the pointer to nf-boost.
Due to the lack of support for resume, this is unfortunately not an option for us.
And we also do not have the need for sophisticated features like deleting files while the pipeline is still running. 

We are interested in a simple solution that
* Deletes all intermediate files, except for log files, after a successful pipeline run
* Leaves the intermediate files in case of an unsuccesful pipeline run
