### ISSUE TITLE
Nextflow confused by dollar-styled variables in awk code

### ISSUE THREAD

**Issue by jgrzebyta** [nextflow-io/nextflow#157]
I need to write a work flow with strong _awk_ support. Sometimes it is not to worth to create a separate script for that. but it seems nextflow and deeper groovy is confused with all awk's dollar-styled variables such as $1, $1, etc. I have error: 

> N E X T F L O W  ~  version 0.18.3
>
> Launching debug.nf
> ERROR ~ startup failed:
> _nf_script_b95fdd1c: 6: illegal string body character after dollar sign;
>    solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 6, column 37.
>    file 'yeastract_data' into yeast_out

I use: 
java -version:
> openjdk version "1.8.0_91"
> OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)

lsb_release -a:
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04 LTS

My example file is:
```
#!/usr/bin/env nextflow

process import_yeastract {

output:
file 'yeastract_data' into yeast_out

"""
curl -s -L http://www.yeastract.com/download/TFConsensusList_20130918.transfac.gz \
| gunzip -c \
| gawk 'BEGIN{FS="[ ]+"}{ if($0~/^NA/) print $2}' \
|sort \
| uniq >yeastract_data
"""

}

yeast_out.subscribe { println "final file: " + it}

```

**Comment by jgrzebyta** [comment]
update:

It accepts only when three of single citing characters were used: `'''  ... '''`. But in that case I cannot pass any variable with input file for awk code for example.

**Comment by pditommaso** [comment]
This happens because dollar is used also by Groovy for variable interpolation. You have server choices:

1.  Escape the AWK/BASH variable with a `\` character e.g. `\$1`. However this can be a bit tricky with complex script
2. If in your script you don't need to use nextflow variables, use *static* string i.e. use `'''` instead of `"""` to delimit the script string. Read more [here](http://groovy-lang.org/syntax.html#all-strings)

3. Use a `shell` block that allows you to use a different syntax for Nextflow variables. Read more [here](http://www.nextflow.io/docs/latest/process.html#shell).

**Comment by jgrzebyta** [comment]
Thanks  lot. I have used shell mode and passed nextflow's variable as `!{variable}`. In the shell mode even longer code works fine .
