### ISSUE TITLE
Is it possible to access executor settings from a process?

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1652]
I'd like to access the executor's cpu number within a process.
I tried `${executor.cpus}` but got a StackoverflowError (which should probably be fixed and display a better error message by the way).

**Comment by mahesh-panchal** [comment]
You want the `${task.cpus}`.

https://www.nextflow.io/docs/latest/process.html#cpus

**Comment by marcadella** [comment]
No that's the number of CPUs set for the process. What I am looking for is the number of CPUs set for the executor (executor.cpus).

**Comment by mahesh-panchal** [comment]
Can you explain what the difference is?

The CPUs set for the process is what determines how many CPUs are reserved by the executor. In the docs, the executor cpus, link back to the link above. 
I don't understand why executor.cpus is a different value from process.cpus.

**Comment by marcadella** [comment]
Let's assume your executor has 10 CPUs, you set executor.cpus=10. Now, your
process needs only 2 CPUs so you set tasks.cpus=5. If you want to run this
process in parallel, nextflow will look at executor.cpus and deduces that
it can run 5 processes at the same time.
So my question is how to get the value of executor.cpu from within the
process (if at all possible).

fre. 26. jun. 2020, 17:40 skrev Mahesh Binzer-Panchal <
notifications@github.com>:

**Comment by mahesh-panchal** [comment]
Nextflow doesn't do those calculations. It leaves it up to the job scheduler to tell you if the resources are available or not.
You can make your own parameter for the maximum cpus to request if you want (See the configs here: https://github.com/nf-core/configs/tree/master/conf. They each set a `max_cpus`, `max_memory`, and `max_time` parameter which is then used in a function to make sure the maximum resources aren't exceeded). 

Also one never assigns to task.cpus. `${tasks.cpus}` is the current cpus for the task instance, since you can use dynamic directives to tell the executor/job scheduler how many CPUs you want to allocate to your process based on some property.
If your process only needs 2 cpus, then you set `process.withName:'<process_name>'.cpus = 2`. If you want all your processes to use 2 cpus by default, then you can set executor.cpus = 2 or process.cpus = 2, but can override these settings on a per process / label basis. There is no setting for the maximum cpus an executor node has given that infrastructures can vary wildly. If you request too many cpus, it's up to the job scheduler to tell you it cannot meet that requirement. Nextflow doesn't do it.  
You can check what Nextflow is writing in the bash scripts submitted to the executor. When you run a process task, it makes a sub directory in the working directory (this is called `work` in your launch directory if you don't change it). When you go into these directories, there are several hidden files. The one that has the executor directives at the top is the `.command.run` which is the script that gets submitted to your executor. That in turn calls the `.command.sh` that has your interpolated script in it. 

I hope this was helpful. Have a good weekend.

**Comment by marcadella** [comment]
Thanks for your answer @mahesh-panchal, but let me modify my question a bit.
It is possible to configure an executor. For instance:
```
executor {
  name = 'local'
  $local {
    cpus = 64
    memory = '128 GB'
    queueSize = 1
  }
}
```
My question is: is it possible to retrieve those settings from within a process?

**Comment by mahesh-panchal** [comment]
Now I get where you're coming from. This is specific to the local executor case.

I learned a few things myself here. 
Specifically, the section here: https://www.nextflow.io/docs/latest/config.html?highlight=queuesize#scope-executor lists the cpus as the maximum number of cpus for local processes (where it makes sense to have this value). 

And contrary to what I claimed, `executor.cpus` isn't used as a default value for a local process. Nor is there anything in the `.command.run` to indicate the number of cpus for a local process.  

Also it seems from the script, one cannot access the `executor` scope. 
```
// Doesn't work. No such variable: executor
process print_exec_properties {

        echo true
        cpus executor.$local.cpus
        
        script:
        """
        echo ${task.cpus}
        """
}
```
But one can from configuration file:
```
process print_exec_properties {

        echo true
        
        script:
        """
        echo ${task.cpus}
        """
}
```
nextflow.config:
```
executor {
  name = 'local'
  $local {
    cpus = 2
    memory = '128 GB'
    queueSize = 2
  }
}
process {
  cpus = executor.$local.cpus
}
```

**Comment by marcadella** [comment]
Nice that it's possible to use `executor.$local.cpus` in the config. Thanks for the help.
