### ISSUE TITLE
Ability to use files from 'exec' process block

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1678]
While investigating methods of unit testing for DSL2 and modules during the July 2020 Hackathon, I found that it is not possible to interact with files output by other processes inside a Nextflow process `exec` block. For example;

```
process make_file {
    output:
    file("file.txt") into output_ch
    script:
    """
    echo foo > file.txt
    """
}
process lines {
    input:
    file(item) from output_ch

    exec:
    count = item.readLines().size()
    log.info("${count}")
}

```

```
$ ./nextflow run test4.nf
N E X T F L O W  ~  version 20.06.0-edge
Launching `test4.nf` [trusting_northcutt] - revision: 6cdca36468
executor >  local (2)
[60/614eff] process > make_file [100%] 1 of 1 ✔
[77/6de5fa] process > lines     [100%] 1 of 1, failed: 1 ✘
Error executing process > 'lines'

Caused by:
  No such file: file.txt

Source block:
  count = item.readLines().size()
  log.info("${count}")
```

It would be useful to be able to work with files in this context, for example in order to do simple file manipulations with inline Groovy code instead of needed an external script (and thus external software)

**Comment by ilya-kolpakov** [comment]
The snippet works if one replaces `file(item) from output_ch` with `val item from output_ch`. I don't know why this the case though, maybe someone else can chime in.

The issue has nothing to do with the DSL 2. In fact, the example uses the old-style DSL since it uses `from` and `into` directives.

**Comment by manuelesimi** [comment]
@ilya-kolpakov Using `val` instead of `file` converts the Path object handling `file.txt` to its absolute path (it's like calling `toString` on the object). This is why you are able to access to the file from the native code in the second process.

But this is of course not a solution. It works only because you are executing both processes locally and without Docker. As soon as you submit the first process to a job scheduler (any) and it gets executed on a different machine, the code will break again. 

I, for one, I don't consider this as a NF limitation, since I see processes with native code as a fill-in among other processes to run parallel code or for advanced (i.e. not just chaining operators) channel manipulation.
