### ISSUE TITLE
Passing variable as argument for groupTuple()

### ISSUE THREAD

**Issue by iferres** [nextflow-io/nextflow#1702]
## Bug report 

Hi, I'm not sure it's a bug or just that I'm not finding the answer in the documentation. I want to pass a nextflow variable as an argument for the `groupTuple()` operator. 

### Expected behavior and actual behavior
The following chunk works (It's just a made up case that illustrate my actual error). In the final line I'm passing a `size: 2` argument to `groupTuple()`.
```nextflow
nextflow.enable.dsl = 2
ch1 = Channel.from("a", "b")
ch2 = ch1.combine( Channel.from(1,2,3,4) )
ch2.groupTuple(size: 2)
    .view()
```
I wanted to set this parameter programatically, taking the length of `ch1` as argument by using the `count()` operator, but it fails:
```nextflow
nextflow.enable.dsl = 2
//...
ln_ch1 = ch1.count()
ln_ch1.view() // correctly prints 2
ch2.groupTuple(size: ln_ch1) //fails
    .view()
```

### Steps to reproduce the problem
```nextflow
nextflow.enable.dsl = 2
ch1 = Channel.from("a", "b")
ln_ch1 = ch1.count()
ch2 = ch1.combine( Channel.from(1,2,3,4) )
ch2.groupTuple(size: ln_ch1)
    .view()
```

### Program output 
```
$ nextflow run script.nf 
N E X T F L O W  ~  version 20.07.1
Launching `script.nf` [drunk_bernard] - revision: 30d6cb92d2
Value 'DataflowVariable(value=null)' cannot be used in in parameter 'size' for operator 'groupTuple' -- Value don't match: class java.lang.Integer

 -- Check script 'script.nf' at line: 5 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: 20.07.1 
* Java version: openjdk version "1.8.0_252"
* Operating system: Linux
* Bash version: GNU bash, versión 5.0.11(1)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by paulderaadt** [comment]
`ch1.count().val` gets you your desired result, as per documentation `count()` results in a channel and you need the value of that channel for `size:`  .

**Comment by iferres** [comment]
Thanks @paulderaadt, that worked.. kind of. 
```nextflow
nextflow.enable.dsl = 2
ch1 = Channel.from("a", "b")
ln_ch1 = ch1.count().val
ch2 = ch1.combine( Channel.from(1,2,3,4) )
ch2.groupTuple(size: ln_ch1)
    .view()
```
Then I run it:
```
$ nextflow run script.nf 
N E X T F L O W  ~  version 20.07.1
Launching `script.nf` [lethal_swirles] - revision: edd9089a3d
```
... and stays there forever. It only finish when I press `Ctrl+c` :
```
$ nextflow run script.nf 
N E X T F L O W  ~  version 20.07.1
Launching `script.nf` [lethal_swirles] - revision: edd9089a3d
^C
[a, [1, 2, 3, 4]]
[b, [1, 2, 3, 4]]
```
Any idea of what it's happening?

**Comment by iferres** [comment]
Possible duplicate -> #1052

**Comment by pditommaso** [comment]
bump

**Comment by FriederikeHanssen** [comment]
I have been running into the same problem. Is there a work around for now?

**Comment by maxulysse** [comment]
Tried both `.val` and `.getValue()` but both freeze the workflow, and it hangs and no idea what is happening.

Neither working with `21.04.0`

**Comment by pditommaso** [comment]
This is an hard problem, a possible solution consist of using the `groupKey` operator to assign a different size for each key. But still it needs to be resolved ahead, there's an example in this comment https://github.com/nextflow-io/nextflow/issues/796#issuecomment-407108667

**Comment by FriederikeHanssen** [comment]
@pditommaso thank you. I'll try it out. @maxulysse came up with [this]( https://github.com/FriederikeHanssen/sarek/blob/3a3777802cba97f99113ef60a2347b9c51923be7/workflows/sarek.nf#L284)
```
num_intervals = 0
    intervals.count().map{
        num_intervals = it
    }
```
  used [here](https://github.com/FriederikeHanssen/sarek/blob/3a3777802cba97f99113ef60a2347b9c51923be7/subworkflows/nf-core/prepare_recalibration.nf#L62):
  ```
  table_baserecalibrator.map{ meta, table ->
            meta.id = meta.sample
            [meta, table]
        }.groupTuple(size: num_intervals).set{recaltable}
  ```
  
  So far this has worked, too. But we are still testing a lot.

**Comment by MikeWLloyd** [comment]
this seems fundamental to be able to specify size based on the length of another object in the nextflow run. 

> @pditommaso thank you. I'll try it out. @maxulysse came up with [this](https://github.com/FriederikeHanssen/sarek/blob/3a3777802cba97f99113ef60a2347b9c51923be7/workflows/sarek.nf#L284)
> 
> ```
> num_intervals = 0
> intervals.count().map{
>      num_intervals = it
> }
> ```
> 
> used [here](https://github.com/FriederikeHanssen/sarek/blob/3a3777802cba97f99113ef60a2347b9c51923be7/subworkflows/nf-core/prepare_recalibration.nf#L62):
> 
> ```
> table_baserecalibrator.map{ meta, table ->
>           meta.id = meta.sample
>           [meta, table]
>       }.groupTuple(size: num_intervals).set{recaltable}
> ```
> 
> So far this has worked, too. But we are still testing a lot.

I tried this, but only get '0' for my list object. Does anyone have another way to set a size variable dynamically?

**Comment by RogerMoraga-NV** [comment]
I know the bug is closed and that there's even some other bug that was turned into a discussion to reach the conclusion that this cannot be done (with .val or .toValue() hanging forever), but for people who might end up here with a similar issue like I did, here's what I've come up with.

Consider the following code:

```
process looksie {
    input:
    val x

    exec:
    println "In process: " + x.getClass()
    //prints: In process: class java.lang.Integer
}
workflow {
    num_ch = Channel.of(1..100)
    counts = num_ch.count()
    println "In workflow: " + counts.getClass()
    //prints: In workflow: class groovyx.gpars.dataflow.DataflowVariable
    looksie(counts)
}

```

What this tells you is that count() returns a DataflowVariable (well, or a ValueChannel if you use it as such), but it's converted into an Integer, as expected, if used within a process. So if you want to access the count() to do something dynamically with it, you're going to have to do it from a process.

Which seems like a perfectly good solution if you're going to create or modify channels based on this value: "output:" from processes are channels for you to use as you please, after all. For the original post (all the way from 2020), you'd do something like: call a process with the count() of ch1, ch2 as .toList(), and use exec: groovy code to return a list of tuples that can be used as a channel.

**Comment by mribeirodantas** [comment]
The reasoning can be summarized as: If you want to deal with channel elements as if they were regular variables, you have two options:

* You pass the channel to a process where the element will be a regular variable within that process (that's what @RogerMoraga-NV showed above)
* You use closures with channel operators but this has a limitation: The closure has a context and can't operate outside it. That's why it doesn't work for @MikeWLloyd. If you see the snippet below, you'll see that the variable within the closure indeed exists and has the proper value (10), but the one outside it (the one you want actually) won't be modified and will be 0. Move the `println` line outside the closure and you'll see what I'm talking about.

```
Channel
  .of(1..10)
  .set { intervals }

num_intervals = 0

intervals.count().map{
     num_intervals = it;
     println num_intervals
}

println num_intervals
```

So most of the time, if you're having the trouble mentioned in this issue, you can solve it by passing the channel to a process and working on the regular variable within it.

**Comment by jpfeuffer** [comment]
I had the same problem and was not satisfied with a "process" solution since it seemed unnecessary overkill.

I saw that `.val` **apparently** works fine in closures on channels and came up with some channel operator magic:

```
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

workflow {
    x = Channel.of('Bonjour', 'Ciao', 'Hello', 'Hola')
    y = Channel.of(1,2,3)
    z = y.count()
    c = 0
    x.map{ it -> [c++ % z.val, it] }
     .buffer(remainder: true){ it[0] == z.val-1 }
     .map{it -> it.collect{ itt -> itt[1]} }.view()
}
```

prints:

```
N E X T F L O W  ~  version 23.04.2
Launching `main.nf` [hopeful_spence] DSL2 - revision: 4a5bb6178e
[Bonjour, Ciao, Hello]
[Hola]
```

I hope some nextflow people will chime in and tell if this is safe to use in all circumstances. Otherwise, HTH with no guarantees.
