### ISSUE TITLE
AWS Tags propagation

### ISSUE THREAD

**Issue by ggabernet** [nextflow-io/nextflow#1764]
## New feature

Hi, when using Nextflow in AWS it would be really useful to be able to tag all the child jobs as well. So far, when submitting a job, one can Tag the Nextflow job but the tags are not propagated.

## Usage scenario 
When submitting jobs to AWS with Nextflow, one would provide the tags and these would also be used to tag the child jobs.

## Suggest implementation 
A possibility would be that the tags are provided as parameters to NXF and they are then included in the job submission to AWS batch. Maybe there are better options though.

**Comment by olatarkowska** [comment]
This feature woudl be very useful on GCP as well https://cloud.google.com/compute/docs/labeling-resources#gcloud

**Comment by MikeKroell** [comment]
+1

**Comment by abhi18av** [comment]
Bump

**Comment by m-rieke** [comment]
We recently tried to find a solution. The problem is that currently its part of the user to provide the compute environment (and job queues). This means that tags are NOT propagated to the created EC2 instances for AWS batch jobs. If you assign tags to compute environment these tags are also propagated to created EC2.

This behavior of AWS Batch makes total sense, because AWS batch also runs multiple containers on the same instance if the resources are big enough. This is different to GCP where an integration of labels (which is the equivalent for AWS tags) was pretty easy, see also:  https://github.com/nextflow-io/nextflow/pull/2589

The only possibility what i see is that nextflow is taking care of creating the compute environments as well, but I am not aware of the reasons why this is currently not the case. Maybe a Maintainer can help here....

**Comment by MikeKroell** [comment]
I believe the issue is to tag the child jobs, not the instance.

**Comment by m-rieke** [comment]
Thanks for the explanation. But what if I want to use tags for cost separation? But maybe I should ask this question better here: https://github.com/nextflow-io/nextflow/issues/948

**Comment by manuelesimi** [comment]
Technically, the AWS batch API allows to attach custom tags to the job definition and to set a flag to propagate those tags to the ECS tasks generated by the job.

@pditommaso any thought?

**Comment by bentsherman** [comment]
If the AWS Batch API supports custom labels then we should be able to add an option similar to #2589 .

**Comment by MikeKroell** [comment]
For us, this is as simple as respecting the propagate tags to new jobs on the task def (already enabled on our manual head node task def), and nextflow taking the tags of the head node and propagating them to child jobs.

**Comment by MikeKroell** [comment]
> Thanks for the explanation. But what if I want to use tags for cost separation? But maybe I should ask this question better here: #948

Question on this. what would be the desired cost breakdown? We currently create a set of Batch queues and CEs for each team. which results in the ECS instances getting the tags of that CE. This is how we track costs per team. We are still unable to track costs per run or project as they can can run on the same instances as other jobs or projects, and there is no way for AWS to break those apart from my knowledge.

**Comment by m-rieke** [comment]
Yes this is true, but if nextflow would also create the compute environment (or even all aws batch related stuff) then it would be also possible to assign custom tags to all resources. This would offer also indirect controlling over the queue size (by defining the amount of CPUs)

**Comment by MikeKroell** [comment]
I believe @pditommaso is going to come back and say that's what Nextflow Tower is for. https://tower.nf/

**Comment by m-rieke** [comment]
ok, was not aware of this project. Can understand that you want to make some money with it ;-)

**Comment by MikeKroell** [comment]
> ok, was not aware of this project. Can understand that you want to make some money with it ;-)

I believe the public beta is free and fully featured.

**Comment by bentsherman** [comment]
While I do recommend that you try tower.nf and see if it fits your needs, Nextflow should be able to support custom tags on AWS jobs.

Per the AWS docs, tags can be provided with [RegisterJobDefinition](https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html) or [SubmitJob](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html). Nextflow makes these calls in `AwsBatchTaskHandler.groovy`. So we could pass custom tags from the config file, just like the PR I mentioned above.

Something like this:
```
aws {
  batch {
    tags = ['foo': 'bar', 'fizz': 'buzz']
  }
}
```

This way you could define tags that apply to an entire workflow run. Of course, Nextflow could also just provide the run name as a tag, which would yield the same effect.

If you need to apply tags to specific processes (or even specific tasks), then we would have to implement a directive. Or better yet, Nextflow could automatically provide the process name and `tag` directive as tags.

How fine-grained do you need to be? Do you really need to provide custom tags if Nextflow can just use existing values like the run name, process name, tag directive?

**Comment by MikeKroell** [comment]
For my use case, I want Nextflow to take the tags of the head nose job and use them throughout removing the need for users to put it in their config.

**Comment by m-rieke** [comment]
Let me explain our situation a little bit more: In our case we build a batch processing chain with nextflow as a generic product for different countries. Customer A wants to run this chain for Germany and should pay for this. Customer B wants to run the same chain (with the same already existing and deployed environment)  for US at the same time. The bill for customer B has to be much higher than for customer A (because of the size of the country).

RegisterJobDefinition and SubmitJob will add tags to the execution (maybe even the logs, I didn't check all details) but not for the instances itself because tags for the instances has to be defined in compute environment, which currently has to be created by the user.

So afterwards we cannot divide the costs for our customers.

**Comment by pditommaso** [comment]
This feature is under developer on our side. However, the main goal so fair is to make tags applied via Nextflow Tower to *all* resources used by a nextflow pipeline, specifically: compute environment, instances, jobs (head and children), files store into buckets, etc.

Moreover, this is going to be supported for any cloud vendor, not just AWS. 

Still don't have a full overview if this be also possible directly from Nextflow config.

**Comment by interline-jay** [comment]
+1

**Comment by pditommaso** [comment]
Delivered as part of 22.10.0 release! See [resourceLabels](https://www.nextflow.io/docs/latest/process.html#resourcelabels) directive.
