### ISSUE TITLE
nextflow doesn't complete and is working on tasks very slowly

### ISSUE THREAD

**Issue by pranathivemuri** [nextflow-io/nextflow#1793]
## Bug report 

I am trying to run a nextflow job with a lot of files about 57K. The nextflow seems to compute faster once the pipeline is started, but after a few hours (2-3) it processes the similar-sized files slower than before, and it's making the pipeline much slower than expected. Once I ctrl+c it and restart it seems like it is doing faster and completes a few (about 100s of files) and the same slowdown happens again. I am not sure what would cause this behavior (maybe too many tasks pending is intimidating to this pipeline). This is for the kmermaid - https://github.com/nf-core/kmermaid pipeline on nf-core and data and computation is on our local servers

Attaching nextflow log for your review.

### Expected behavior and actual behavior

Expected behavior - pipeline should complete in a few days as compared to it being run for over 14 days with only 200 files completing every day. It has completed 34k files so far and 23k files are processing slowly. 
Each of the files that are going through this nextflow process `translate` in kmermaid take less than a few seconds or a few minutes to complete for the same input files outside of nextflow
### Steps to reproduce the problem
Reproducing the problem is difficult as you don't have the data that I am trying to run. It is kmermaid pipeline run using below command, you could test it with the test-datsets in test config if needed

```
          nextflow run \
                nf-core/kmermaid \
                -r dev -profile docker \
                -latest \
                --tenx_tgz ${TGZ_DIR}'/**.tgz' \
                --skip_compute \
                --skip_compare \
                --molecules dayhoff \
                --ksizes 27,30,33,51,54,57,60 \
                --sketch_scaled 10 \
                --track_abundance \
                --reference_proteome_fasta ${TRANSLATE_FASTA} \
                --outdir ${OUT_DIR} \
                -work-dir ${WORK_DIR} \
                 --tenx_min_umi_per_cell 1000 \
                -with-tower --remove_ribo_rna --save_non_rrna_reads \
                -resume --skip_multiqc
```
### Program output 

[nextflow_log.zip](https://github.com/nextflow-io/nextflow/files/5539651/nextflow_log.zip)

### Environment 

* Nextflow version:       
      N E X T F L O W
      version 20.07.1 build 5412
      created 24-07-2020 15:18 UTC (08:18 PDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
* Java version: openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
* Operating system: [macOS, Linux, etc] Linux
* Bash version: (use the command `$SHELL --version`) GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

### Additional context

(Add any other context about the problem here)

**Comment by mawasak** [comment]
Hi,
Have you resolved this performance issue? When looking in logs attached I see that you have a lot of processes created (max task handler number is 80K, number of tasks in submission queue is 23K and currently running is 32 (max capacity is 128). About 1 to 5 tasks are taken from submission queue every 5 minut - so it takes max 16 days to finishing.
Did you checked number of processes in system (e.g. ps aux |wc -l) or number of handlers (e.g. lsof | wc -l) when pipeline is running and how this numbers are changing during pipeline is running? Are they increasing? Did you check your disks IO (e.g. iostat/iotop)? 
I also noticed that you working dir is on nfs - did you check if this is not bottleneck?
When I run your test profile from https://github.com/nf-core/kmermaid/blob/dev/main.nf  I see in execution_timeline that all tasks are executed sequentially (no parallelism) - is this by design?

M

![obraz](https://user-images.githubusercontent.com/1379060/103286698-198be580-49e1-11eb-8511-e6cb29498201.png)

**Comment by pranathivemuri** [comment]
Hi, Thanks for the great input. The bottleneck was indeed the NFS. And the design is currently sequential as one input from a process transforms into an output that the next process needs, so we couldn't apply any parallelism within those steps.

@olgabot please correct me if I am wrong or feel free to add something I am missing, thank you!
