### ISSUE TITLE
splitFasta operator with the file parameter will not split into single fasta files

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#181]
The splitFasta operator when called like:  `splitFasta(file: true)` fails with this error:

Parameter `file` requires a split size grater than 1 for operator: splitFasta

The splitFasta operator should allow a multifasta file to be split into individual files for each record.

**Comment by pditommaso** [comment]
I agree that could be useful. I think the problem was that the splitting to a file was added in a later stage and there's a design problem than made difficult to implement it. Thus it was disabled for chunks of just one item. 

The relevant parts are methods [processChunk](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/splitter/AbstractTextSplitter.groovy#L202-L221) and [createCollector](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/splitter/AbstractTextSplitter.groovy#L227-L241)

It should be possible to extend them to handle chunks of size 1.

**Comment by mes5k** [comment]
I've been digging into this code and it seems like AbstractSplitter.count is used to signal both the number of lines to split on AND something else.  I'm not sure what that "something else" is.  There are several checks in the splitter package for "count > 1", but it's not clear why.  Can you provide any insight here?  Is my intuition right that there is a state currently captured as "count == 1" that could be extracted into a separate field of AbstractSplitter and count could just mean the number of lines to split on?

**Comment by pditommaso** [comment]
I think the logic behind is this. In the first iteration there was not the ability to save chunks to a file. Thus it was possible to split a file into single records (`count=1`) or create chunks of `count` records. Thus `count==1` is used to discriminate when to enable the *collecting* mechanism. 

When the save chunks to a file was added, it has been implemented as a specialisation of the collecting strategy, resulting in this inconsistency, that is not possible to save chunks of one record. 

I think this feature could be implemented just extracting the collecting condition to something like  `count==1 && !saving_to_a_file`, so that that the collecting strategy it's applied also for chunks of just one record only when it's required to save them to a file.

**Comment by pditommaso** [comment]
Just uploaded version `0.21.1-SNAPSHOT` including this patch.

**Comment by pditommaso** [comment]
Released.
