### ISSUE TITLE
mkdir $NXF_LAUNCHER errors - important or silence?

### ISSUE THREAD

**Issue by dctrud** [nextflow-io/nextflow#186]
We have Nextflow installed as a environment-module on our cluster. The NXF_HOME is not writable for users, so when the nextflow script tries to save the cached classpath file it spits errors:

<code>
mkdir: cannot create directory `/cm/shared/apps/nextflow/0.17.3/tmp': Permission denied
/cm/shared/apps/nextflow/0.17.3/bin/nextflow: line 342: /cm/shared/apps/nextflow/0.17.3/tmp/launcher/nextflow-one_0.17.3/Nucleus005/classpath-c756f173b1e1f7c03242c341d3f57ca9: No such file or directory
</code>

This understandably alarms some users, who have then contacted us asking why nextflow has an error. To my knowledge, there  are no real ill effects.

Am I missing something, or can this just be made to come up as a warning, and not spit the errors from mkdir and printf attempts?

Thanks!

**Comment by pditommaso** [comment]
It's used to write in that directory the nextflow classpath in order to speed-up the application launch time. The consequence is that nextflow will recompute its classpath each time you launch it. 

You may eventually provide a path of your choice using the `NXF_LAUNCHER` variable using a structure similar to the one showed [here](https://github.com/nextflow-io/nextflow/blob/master/nextflow#L220)

**Comment by dctrud** [comment]
Gotcha - for our specific usage it's unlikely the cache would hit that often given it is dependent on hostname and we're running nextflow on a cluster. I could set NXF_LAUNCHER to user home dir location I guess - or /tmp but that then leaves mess

Thanks for clarification.

**Comment by pditommaso** [comment]
That's good. Include the current host name if it's supposed to be launched in parallel by many users.

**Comment by pditommaso** [comment]
See #187
