### ISSUE TITLE
path parts containing square brackets not supported

### ISSUE THREAD

**Issue by biologghe** [nextflow-io/nextflow#194]
nextflow fails with 101 exit code when working directory contains square brackets.
See [forum](https://groups.google.com/d/msg/nextflow/v7kN4YreEPs/CG4sDa5VBAAJ) how to reproduce

**Comment by pditommaso** [comment]
This is a bad one. The problem is that the square brackets are interpret as [glob wildcards](https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob). 

The relevant code is the [TestHelper.visitFiles](https://github.com/nextflow-io/nextflow/blob/master/subprojects/nxf-commons/src/main/nextflow/file/FileHelper.groovy#L747-747)  and [Globs.toUnixRegexPattern](https://github.com/nextflow-io/nextflow/blob/master/subprojects/nxf-commons/src/main/nextflow/file/Globs.java#L231-231) methods.

**Comment by biologghe** [comment]
I think using brackets in file/folder names is a bad idea after all. It will probably not block anyone else. No worries, I tweaked the soaplab2 code a little so that the brackets are stripped from the jobId (which contains those brackets) when used as path part.
Thanks for having looked into this.
Cheers,
Marc
