### ISSUE TITLE
Can't reuse process on workflow

### ISSUE THREAD

**Issue by jfxer** [nextflow-io/nextflow#1948]
## Bug report 
workflow {
     HELLO()
     HELLO()
}
### Expected behavior and actual behavior
expected behavior: Run process HELLO twice
actual result : Process 'HELLO' has been already used -- If you need to reuse the same component include it with a different name or include in a different workflow context

* Nextflow version: 20.10.0 
* Java version: 8
* Operating system: [Ubuntu 18.04]
* Bash version: 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

DSL 2 is enabled.

is I have any way to run the processes on loop?
something like:
    workflow {
     for (int i=0; I< 5; i++){
           HELLO()
     }
}

**Comment by abhi18av** [comment]
Hi @jfxer ,

Actually, this aspect of DSL2 seems to be by design 😉 

Perhaps, [module aliasing](https://www.nextflow.io/docs/latest/dsl2.html#module-aliases) section of the docs might be of help in your use-case.

Regarding the second part of the question, which is independent of the first one. This seems contrary to the `DataFlow` paradigm adapted by NF, which emphasizes parallel processing  (via channels) rather than serial processing (via loops).
