### ISSUE TITLE
resume bug when errorStrategy is ‘retry'

### ISSUE THREAD

**Issue by biowang** [nextflow-io/nextflow#196]
my retry but completed process will not be cached in resume mode rerun.

run nextflow first time
![first](https://cloud.githubusercontent.com/assets/10825631/16605135/061280be-435f-11e6-9299-a1732b0e74c6.PNG)

then my last step error and stop, I add parameter -resume and rerun it.
![resume](https://cloud.githubusercontent.com/assets/10825631/16605147/32fa0570-435f-11e6-8893-3d3d97454737.PNG)

here is the some configure
        errorStrategy     = 'retry'
        maxRetries        = 3
        maxErrors         = 10
        executor          = 'sge'

**Comment by pditommaso** [comment]
The most common reason for this problem is that some inputs have been modified, thus the task are execute one more time.

**Comment by biowang** [comment]
I am not focus on one more time, but the submitted job in resume run.
for example, QCtable is completed in the first time, although one more time. it should be cached in resume run ( second picture ). acturely the QCtable submitted again.
why ?

**Comment by pditommaso** [comment]
Can you share your script?

**Comment by pditommaso** [comment]
I'm closing this because there's feedback anymore.

**Comment by JocelynSP** [comment]
Hi I am having the same issue. There is a large amount of variation in the input file sizes, so we have retry with increasing memory:
```
process {
    withLabel:IndexDedup {
        queue='regular'
        cpus = 5
        memory={ 10.GB * task.attempt }
        time='8h'
        errorStrategy ={ 'retry'  }
        maxRetries= 5
    }
}
```
When I resume, the result from the input that worked with 10 GB is successfully retrieved from cache, but the result for a large input file that had 2 failures before success is not retrieved from cache.

Increasing the initial memory so that the process works first time fixed the issue
