### ISSUE TITLE
BUG?Channel `conbine_qcstat_ch` has been used as an input by more than a process or an operator

### ISSUE THREAD

**Issue by Cynthia1012** [nextflow-io/nextflow#2093]
Hello,
@pditommaso  I have a similar issue where I am sure my channel is not used by another process or operator.
The error I hit is:
Channel `conbine_qcstat_ch` has been used as an input by more than a process or an operator

But if you run it again without making any changes, it will succeed. 
nextflow version 20.10.0.5430

_Originally posted by @Cynthia1012 in https://github.com/nextflow-io/nextflow/issues/819#issuecomment-833177696_

**Comment by XLuyu** [comment]
Hi,

I encountered the same problem many times, even for the latest version 21.
This only happened to me when:
1. My submitted job on **AWS** failed due to some reasons like **network/memory problem** (I think this is the key to trigger the bug)
2. Nextflow didn't end the pipeline as expected.
3. I manually killed nextflow
4. I tried to resume the pipeline to reuse successful jobs

It looks like this is a long-standing problem. I have no choice but rerun the pipeline from very beginning, abandoning cached successful jobs.
