### ISSUE TITLE
Allow map output from a process

### ISSUE THREAD

**Issue by multimeric** [nextflow-io/nextflow#2127]
## New feature

I would like to be able to produce a single channel with multiple named values (ie a `Map`) from my processes, ie `my_proccess.out.view()` should return:
```
[a:abc, b:123, c:false]
[a:abc, b:123, c:false]
[a:def, b:456, c:true]
```

Currently we have a `tuple` qualifier, which creates an output channel which is a tuple of other types. However this tuple is unlabelled, so users have to extract values from this channel by position, which results in confusing code. 

It is also possible to produce multiple output channels, each of which has its own name. However, these channels can't easily be combined into a single channel containing maps or tuples, because the `merge` operator has been deprecated, and in general joining channels by position is discouraged.

## Usage scenario 

This would be useful when a user is working with mostly map data in their channels, likely because they want each field to be labelled instead of unlabelled as in a tuple.

## Suggest implementation 

I would envisage a new `map` qualifier, which is used like this:
```groovy
process hmmer_search {
    container "quay.io/biocontainers/hmmer:3.3.2--h1b792b2_1"
    input:
      path profile
      path database
    output:
        map [table: path('table.txt'), human_readable: path('match.txt')]
    script:
      """
      hmmsearch -o match.txt --tblout table.txt ${profile} ${database} 
      """
}
```

**Comment by christopher-hardy** [comment]
+1

**Comment by bentsherman** [comment]
Quick workaround is to output a tuple and follow up with a map operator that converts each tuple to a map.

**Comment by bentsherman** [comment]
This issue is complementary to #2257, which is about multiple named channels whereas this issue is about named values within a channel (e.g. map). Ideally both use cases should be supported.

A single map channel would be used for 1-to-1 relationships whereas multiple named channels would be used for 1-to-many and many-to-many relationships.

**Comment by notestaff** [comment]
+1

Or maybe immutable named tuples?   E.g.
output:
       tuple table: path('table.txt'), human_readable: path('match.txt')

Then all current tuple-reliant functionality (e.g. groupKey) works as before, but one can use names instead of indices when manipulating process results, e.g.

input_ch
| MY_PROC
| map { it.table }

instead of 

| map { it[0] }

**Comment by bentsherman** [comment]
Closing in favor of #2085

Typed processes in Nextflow 25.10 allow for inputs and outputs to have type `Map`, but it does not stage files for map inputs like it does for `Path` or `Set<Path>`. This is because maps are typically used to hold metadata, and once we have records there won't be as much of a need for maps anyway.

And if you want to output a map, you can just do it:

```groovy
nextflow.preview.types = true

process hmmer_search {
    input:
    profile: Path
    database: Path

    output:
    [ table: file('table.txt'), human_readable: file('match.txt') ]

    script:
    """
    hmmsearch -o match.txt --tblout table.txt ${profile} ${database} 
    """
}
```

And if you wanted to pass this map as a process input, you could stage the input files explicitly using the `stage` section:

```groovy
input:
search: Map

// search.table should be a Path
stage:
stageAs '*', search.table
```

But I think the experience will be much nicer with records. Stay tuned
