### ISSUE TITLE
User-defined nested param does not evaluate properly within config file

### ISSUE THREAD

**Issue by jamesbaye** [nextflow-io/nextflow#2247]
### Expected behavior and actual behavior

Evaluating a nested parameter in `nextflow.config` does not return the user-specified value.

### Steps to reproduce the problem

nextflow.config:
```
params {
    foo = true
    bar = params.foo ? "foo is true" : "foo is false"

    nested.foo = true
    nested.bar = params.nested.foo ? "nested foo is true" : "nested foo is false"
}
```

main.nf:
```
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

workflow {
    print "$params.foo $params.bar"
    print "$params.nested.foo $params.nested.bar"
}
```

### Program output 

nextflow run main.nf --nested.foo false --foo false
```
false foo is false
false nested foo is true // expected: "nested foo is false"
```

Oddly, the return value is as expected if line order is switched in config file:
nextflow.config:
```
params {
    foo = true
    nested.foo = true

    bar = params.foo ? "foo is true" : "foo is false"
    nested.bar = params.nested.foo ? "nested foo is true" : "nested foo is false"
}
```

### Environment 

* Nextflow version: 21.04.1.5556
* Java version: 1.8.0_282
* Operating system: CentOS Linux release 7.9.2009
* Bash version: 4.2.46(2)-release

**Comment by abhi18av** [comment]
Hi @jamesbaye ,

This is a very interesting observation!

I had the hypothesis that `nextflow.config` is file always meant to be used to specify the parameters declaratively, rather than add programming logic in there. 

To test this, modified the script a little bit and added the evaluation part to the `main.nf`  as well, as shown below.

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

workflow {

    print "nested.foo: $params.nested.foo - nested.bar: $params.nested.bar"

    def derived_nested_bar =   params.nested.foo ? "nested.foo is true" : "nested.foo is false"

    print "nested.foo: $params.nested.foo - derived_nested_bar: $derived_nested_bar"
}

```

The config file used was 


```nextflow 
params {
    nested.foo = true
    nested.bar = nested.foo ? "nested foo is true" : "nested foo is false"
}



```



The results for the command invocation were

```
(base) bash-5.0$ nextflow run main.nf --nested.foo false --foo false

N E X T F L O W  ~  version 21.04.2
Launching `main.nf` [ecstatic_fourier] - revision: 1edf06339b
nested.foo: false - nested.bar: nested foo is true
nested.foo: false - derived_nested_bar: nested.foo is false  // <-- As expected

```

------

I imagine that the reason this happens is because, the `nextflow.config` file goes through a parsing process to convert it into Groovy classes (Nextflow is a Groovy DSL) and the `config` file parser does not cater to sophisticated logic within that file.

That logic works perfectly fine once it is expressed into a xyz.nf` i.e. nextflow file which takes care of those derivations. 

> Oddly, the return value is as expected if line order is switched in config file:

To me, the aforementioned observation is troubling and unexpected 😶

**Comment by abhi18av** [comment]
Related https://github.com/nextflow-io/nextflow/issues/1982

**Comment by abhi18av** [comment]
A fix has been merged recently for this and would be available in the next `edge` release i.e. `21.12-edge` .
