### ISSUE TITLE
DSL2 equivalent of from (process with input channel)

### ISSUE THREAD

**Issue by maxbates** [nextflow-io/nextflow#2250]
The docs for DSL2 include examples like:

```
workflow my_pipeline {
    foo()
    bar( foo.out.collect() )
}
```

and

```
workflow {
    data = channel.fromPath('/some/data/*.txt')
    foo(data)
    bar(data)
}
```

But is this actually possible in DSL2?

--

I am trying to write a split-apply-combine wrapper which:

- `split_tarball` takes a tarball with many files, and chunks it into multiple directories
- runs a `sub_workflow` on each chunk directory
- `combine_directory_contents` combines the results into a single output directory

It might look something like this:

```
split_tarball("in.tar.gz") | sub_workflow | flatten | collect | combine_directory_contents
```

I'm unclear how feed the several directories into a process like `combine_directory_contents` which can join all of them together. 

The closest thing I see is the `collectFile` operator, but this only works for text.

Thanks for any help!

**Comment by GDCCP** [comment]
I have used **fromFilePairs** and a few other channel factory methods with DSL2. I don't think there is any additional limitations in DSL2 with respect to factory methods.

I would use **collect** instead of **collectFile**. Note that this may just be one possible implementation.

I am thinking having a process/workflow SubW that output a directory (nextflow path output does recusively copy everything if given a directory). So, feeding SubW.out.collect() to combine_direcctory_contents will get close to what you need.

Experiment by just viewing() this channel. You may need to flatten/sort.....
