### ISSUE TITLE
AWS Batch CLI-mounting potentially disables the container

### ISSUE THREAD

**Issue by multimeric** [nextflow-io/nextflow#2322]
### Summary
Nextflow mounts the AWS CLI from the AMI into the process container. However the way it does this is dangerous, and can mask the contents of the container itself, causing undefined behaviour.

### Expected behavior and actual behavior
If you get an error like this in AWS Batch:
> CannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/local/env-execute": stat /usr/local/env-execute: no such file or directory: unknown

Then this bug is probably at play. Notably it doesn't *have* to involve `env-execute`. Any missing-file error could result from this bug.

### Steps to reproduce the problem
The steps are documented in this repository here:
https://github.com/multimeric/AwsNextflowBug

The crucial part of this repo are that it:

a) Uses a docker container that depends on the contents of `/usr` being present (all biocontainers do this)
b) Sets the AWS CLI path in the config to `/usr/bin/something`, meaning that the entirety of `/usr` is mounted on top of

### Program output 

```
Error executing process > 'spades'

Caused by:
  Process `spades` terminated for an unknown reason -- Likely it has been terminated by the external system

Command executed:

  spades

Command exit status:
  -

Command output:
  (empty)
```

### Environment 

* Nextflow version: 21.04.0.5552
* Java version: 1.8.0_152-release
* Operating system: Ubuntu 20.04.3 LTS
* Bash version: fish, version 3.2.2

### Discussion of Cause

So I've looked into why this is happening. Whenever you have the AWS config set like this:
```
batch.cliPath = '/usr/bin/foobar'
```
Then nextflow mounts `/usr` from the AMI on top of the container, thereby masking out the entire `/usr/` directory, which is obviously *very bad*. You can see the cause of this behaviour here:
https://github.com/nextflow-io/nextflow/blob/f2f1fdea46631b07fefb48a0d098c66ff53e58fe/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy#L440-L443

One common case where you might have the CLI installed to `/usr/bin/awscli` is if you use the AWS ImageBuilder, which has an AWS CLI component, which automatically installs the CLI into that location.

### Workarounds

When building your AMI, make sure that you install the `aws` CLI to a location such that the grandparent directory of the binary is not an important directory for the container. e.g. the grandparent of `/stuff/aws/aws` is `/stuff`, which isn't likely to cause a problem.

**Comment by multimeric** [comment]
In terms of the solution I would like, I think we shouldn't be assuming that `binary.parent.parent` is necessarily the correct directory to mount, it could be highly variable depending on how the binary loads its dependencies. I would like to see another config parameter along the lines of `cliMount`, which takes the path to the directory to mount. In the case of `/usr/bin/aws/` we would set this to `/usr/bin` which would at least limit the damage caused by mounting onto `/usr`.

**Comment by multimeric** [comment]
Also regarding the use of the ImageBuilder component which I was using to install the CLI. I investigated the artifacts that it installs:

```bash
[ec2-user@ip-172-31-16-27 ~]$ ldd /usr/bin/aws
	linux-vdso.so.1 (0x00007ffcb8bc5000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f583ca30000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f583c81b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f583c470000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f583cc34000)
[ec2-user@ip-172-31-16-27 ~]$ ls -l /usr/bin/aws
lrwxrwxrwx 1 root root 18 Sep  7 05:27 /usr/bin/aws -> /usr/local/bin/aws
[ec2-user@ip-172-31-16-27 ~]$ ls -l /usr/local/bin/aws
lrwxrwxrwx 1 root root 37 Sep  7 05:27 /usr/local/bin/aws -> /usr/local/aws-cli/v2/current/bin/aws
[ec2-user@ip-172-31-16-27 ~]$ ls -l /usr/local/aws-cli/v2/current/bin/aws
lrwxrwxrwx 1 root root 11 Sep  7 05:27 /usr/local/aws-cli/v2/current/bin/aws -> ../dist/aws
```
So basically it does use a number of symlinks, but even if I mount `/usr/local/aws-cli/v2/current/bin/aws` into the container, it still won't work because it depends on some shared libs in `/lib64`. So this approach is broadly a dead end.

**Comment by jwarwick-delfi** [comment]
This is a problem for us too. We're using a custom AMI, as recommended, to install the aws cli on the ECS host (in /usr/local/bin/aws). Inside our docker image, we are installing bioinformatic tools into /usr/local/bin/. 

As discussed above, Nextflow is creating the "aws-cli" mount from the ecs host into /usr/local in the container, which is overwriting the tools we installed into /usr/local/bin inside the container. We're also installing the aws cli in our docker container so it's not like that mount is doing anything useful for us.

Our workaround (based on @multimeric's report) is to build the ami with a softlink from /opt/nf/bin/aws -> /usr/local/bin/aws, and set nextflow's aws.batch.cliPath to "/opt/nf/bin/aws" so the resulting mount target is /opt/nf inside the container instead of /usr/local. Inside the image I also had to link /usr/bin/aws -> /usr/local/bin/aws since the aws executable is installed in a different location inside our docker image than in the ECS host AMI.

It would be great not to have to do this. The current mount behavior makes it impossible to use the default ECS AMI for nextflow, forcing users to build and maintain a custom AMI with the CLI in it, a more complex and user-hostile process. I support @multimeric 's idea of a cliMount parameter, but I would like to suggest the default value should be null (no mount), pushing users to install the aws cli in their docker images instead of the ECS host AMI.

**Comment by multimeric** [comment]
For what it's worth, I later moved over to using the [Amazon Genomics CLI](https://aws.amazon.com/genomics-cli/), and I never encountered this problem there. I assume they mount the CLI in a more clever way using that tool, and I used plenty of biocontainers.

**Comment by pditommaso** [comment]
This mounting scheme is required because the `aws` tool is not a static binary but it requires other dependencies in the installation directory. 

To avoid the problem you are reporting it's enough to install into a directory that's not `/usr/something` but use a dedicated installation path e.g. `/opt/aws-cli` or anything of your choice.

**Comment by multimeric** [comment]
My proposed solution is not to mount only the binary, as I said above: https://github.com/nextflow-io/nextflow/issues/2322#issuecomment-920683906. The reason I couldn't use `/opt` is because the ImageBuilder installs the AWS CLI to `/usr/bin`

**Comment by pditommaso** [comment]
If I remember well it creates a symlink into `/usr/bin` but the distribution is installed into another path. That's the one that should be used. Alternatively the CLI can be installed via Conda or manually using the AWS CLI v2

**Comment by multimeric** [comment]
That is correct, but [as I discussed above](https://github.com/nextflow-io/nextflow/issues/2322#issuecomment-920696021), it depends on some libs in `/lib64`, so just mounting that directory doesn't help.

**Comment by pditommaso** [comment]
That works provided you are using a glibc based container (ie. not alpine). Likely soon AWS cli v2 will also support alpine https://github.com/aws/aws-cli/pull/6352#issuecomment-909083091

**Comment by jwarwick-delfi** [comment]
I apologize if I am misunderstanding your comments. But I want to reiterate that it seems like an anti-pattern to have users installing the AWS CLI into AMIs to run on the ECS hosts, and then mounting that CLI into containers, instead of just installing the CLI in the docker container itself. As currently written, nextflow prevents users from following the simple path of installing the CLI in their docker image. We need a way to disable the mounting functionality.

**Comment by pditommaso** [comment]
> instead of just installing the CLI in the docker container itself

If you want to use the AWS CLI in the container you just need to *not* specify any `aws.batch.cliPath` in the config file.

**Comment by multimeric** [comment]
> I apologize if I am misunderstanding your comments. But I want to reiterate that it seems like an anti-pattern to have users installing the AWS CLI into AMIs to run on the ECS hosts, and then mounting that CLI into containers, instead of just installing the CLI in the docker container itself.

It has its downsides, but we are mounting the CLI into the containers so that we can use pre-built containers in our workflows, in particular biocontainers. If we were to install the awscli into all containers we would have to rebuild and rehost all containers we use anywhere in our workflow, whereas mounting the CLI lets us bypass this entirely.

**Comment by jwarwick-delfi** [comment]
> > instead of just installing the CLI in the docker container itself
> 
> If you want to use the AWS CLI in the container you just need to _not_ specify any `aws.batch.cliPath` in the config file.

Thanks I did not realize that was an option!

@multimeric - I see. Running a bioinformatic container without modifying it is definitely a compelling use case.

**Comment by manics** [comment]
I ran into this last month, so I've opened a PR to try and improve the docs https://github.com/nextflow-io/nextflow/pull/2565

**Comment by pditommaso** [comment]
As of version 22.10.x the [Fusion file system](https://www.nextflow.io/docs/latest/fusion.html) can be used as an alternative to installing the `aws` CLI tool in Batch compute node

**Comment by eirinnm** [comment]
As of 2026 this bug still exists. The feature for mounting the aws cli into the container breaks the container.

This is the same bug as #1064
