### ISSUE TITLE
Caching not working after collectFile in some cases

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#2393]
### Expected behavior and actual behavior

Processes after a `collectFile` operation are always being re-executed when using nextflow in Docker or when restarting the host.
This because, by default, `collectFile` stores the `.collect-file`s in `/tmp` which is obviously not persistent on most cases.

I cannot see any reason for why `.collect-file`s should be treated differently from any other files produced by the pipeline (i.e stored somewhere in `workDir`).
It would have been better to default the `storeDir` option of `collectFile` to `tmp` instead of `/tmp`.

### Environment 

* Nextflow version: 21.04.3
* Operating system: Linux

**Comment by multimeric** [comment]
Agreed, and I can't even manage to work around it using `collectFile(name: "combined", cache: true, storeDir: workflow.workDir, tempDir: workflow.workDir)`. It seemingly still tries to use `/tmp`, which I think is a bug. However there's a workaround in [this thread](https://groups.google.com/g/nextflow/c/ofEmR3Xnmjg?pli=1) which looks promising.

**Comment by multimeric** [comment]
It feels like this is the culprit:

https://github.com/nextflow-io/nextflow/blob/397c2f2d284d8f12c2f0de212986bb7b461f1e12/modules/nextflow/src/main/groovy/nextflow/file/FileCollector.groovy#L240-L246

The actual `retrieveCachedFiles` routine seems okay, but it never actually uses the `FileCollector.tempDir` variable because it always runs `FileHelper.getLocalTempPath()` which relies on the `NXF_TEMP` env var, and not on the `tempDir` parameter.

**Comment by pditommaso** [comment]
Related to #3465

**Comment by bentsherman** [comment]
Resolved by #3466

**Comment by bentsherman** [comment]
No, it should just work. If you're still seeing the issue, please share your nextflow log so that we can investigate
