### ISSUE TITLE
Race in task handling

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2424]
Hello,

it seems that nextflow has some kind of race condition in task handling if really large queue size is used (1800) and tasks take only few seconds to run. Maybe it is related only to kuberun executor. I can see many messages like this:
```
 [54/9865f8] NOTE: Unable to find pod nf-549865f8a93ab6e5f44b696d04ab08ce - The pod may be evicted by a node shutdown event.
```

however, if I find output in tmp dir 54/9865f8:
```
Tool returned:
SUCCESS
```

Also exitcode is 0. It seems that having so many tasks in flight, it may happen that the task finishes earlier than the task processor thinks. 

Is there anything we can do here except lowering queue size?

**Comment by bentsherman** [comment]
Was this issue fixed by #2562 ?

**Comment by xhejtman** [comment]
Not sure if it fixes this. I think this is not related. The issue #2562 fixes failing to start the pod, but I believe, it can still happend, that  nextflow controller misses just finished pod. 

However, we are in preparing PR so that we switch pods to jobs and this issue should be fixed (as a job as object does not wanish after completed as is the case for a pod).

**Comment by bentsherman** [comment]
Ah, I see. I think you are right. I have encountered both errors in the past. As for the eviction error, I haven't been able to diagnose why it happens or how to fix it. I have only been able to avoid it by decreasing the queue size or just trying again (the main k8s cluster that I used is highly distributed and has networking issues from time to time).

We have considered using Jobs instead of Pods in the past for other reasons (#1162). I think it would help with k8s cleanup and enable some helpful features like specifying a `time` limit. I look forward to your PR.

**Comment by bentsherman** [comment]
@xhejtman Have you made any progress towards a PR? I'd like to implement K8s jobs in the near to mid term but I don't want to duplicate your work if you're almost there.

**Comment by xhejtman** [comment]
@bentsherman yes, we have basic work ready, not finished error cases. 

basically, we wrapped pod calls with job calls and search pods of a corresponding job to return pod status in the way the code expect. Would it be acceptable way?

**Comment by bentsherman** [comment]
That sounds broadly like the right approach. When you submit your PR we will look at the details 😄

**Comment by xhejtman** [comment]
OK, I believe, I can provide preview of what we have till the end of this week.

**Comment by bentsherman** [comment]
You're welcome to submit a draft PR if you're not finished but want to share your progress. That way people know it's being worked on and we can provide guidance.

**Comment by pdp10** [comment]
Thank you very much for this new feature. We have been experiencing the same problem as described here. 

@bentsherman Would it be possible to have a nextflow release including this new functionality, please?

**Comment by pditommaso** [comment]
> Would it be possible to have a nextflow release including this new functionality, please?

<img src="https://media2.giphy.com/media/3cCwplTPjNqRW/giphy.gif"/>

**Comment by bentsherman** [comment]
@pditommaso I suppose it's about time for a `22.05.0-edge` release. 😄 

In the meantime, you can also build the `nextflow` binary for yourself. It's a bit more complicated with k8s because you have to build the nextflow docker image, push it to dockerhub, and reference it with kuberun. Or build it the normal way and then upload to your cluster.
```
# build nextflow binary
make

# or build nextflow docker image
make dockerPack
```

**Comment by pdp10** [comment]
Just seen the new edge release, thank you very much guys!
