### ISSUE TITLE
Native NF validation via JSON parameter schema

### ISSUE THREAD

**Issue by drpatelh** [nextflow-io/nextflow#2434]
nf-core pipelines are now using a [standardised JSON schema](https://github.com/nf-core/rnaseq/blob/master/nextflow_schema.json) to store, maintain and validate pipeline parameters (see https://github.com/nextflow-io/nextflow/issues/866). The nf-core community has written it's own validation script [here](https://github.com/nf-core/rnaseq/blob/master/lib/NfcoreSchema.groovy) and has some nice tooling to maintain the schema via the [`nf-core schema build`](https://github.com/nf-core/tools#pipeline-schema) command.

The schema is already being used by the front-end of Nextflow Tower to render the parameters in the UI as well as performing validation based on criteria defined in the schema e.g.

![image](https://user-images.githubusercontent.com/23529759/140728604-c2dc9e94-c96f-4677-a1b2-200d6a0396b7.png)

It would be nice to be able to port this validation functionality to native Nextflow too so it can be performed dynamically on the CLI.

A separate plugin was created to add this functionality a while back but may still need some work:
https://github.com/nextflow-io/nf-validation

**Comment by ewels** [comment]
x-ref / continuation of https://github.com/nextflow-io/nextflow/issues/866#issuecomment-761812687 🚀

**Comment by rpetit3** [comment]
For what it's worth, it took little effort to include nf-core's implementation into my non-nf-core pipeline (https://github.com/bactopia/bactopia/tree/dsl2/lib) and it was easy to adapt to my needs. This saved a lot of time and really cleaned up process for checking arguments.

I also like the approach of using external schema files, since they can be reused for things like generating documentation, unlike native arg parsers (e.g. Pythons argparse).

**Comment by pditommaso** [comment]
I would love to see this as well. Is there anybody in the nf-core community can jump into this, to align the nf-core validator with the [plugin](https://github.com/nextflow-io/nf-validation) implementation? 

With that, we could make it generally available.

**Comment by dougnukem** [comment]
Is it possible to extend Nextflow to support strongly-typed Workflow params and process inputs/outputs, something like Flyte does.
- https://docs.flyte.org/projects/cookbook/en/stable/auto/core/control_flow/subworkflows.html

Having it be a core part of the language and then having tools that can introspect the type definitions feels like it could allow building tools like web UI launching in an easier way to understand rather than requiring associating an external JSON schema definition.

Flyte leverages protocol buffers definitions to share their workflow/task types.
- https://docs.flyte.org/projects/flyteidl/en/stable/protos/index.html

**Comment by ewels** [comment]
Not stale, PR ongoing.

**Comment by bentsherman** [comment]
Shall we close this issue now that the nf-validation plugin was developed?

**Comment by ewels** [comment]
Yes 👍🏻 

Some aspects, such as native support for strong typing, native validation, and integration of metadata currently in the schema into the config itself can hopefully happen in https://github.com/nextflow-io/nextflow/issues/2723

But what this issue was specifically about - getting schema validation out of the nf-core template - is done ✅
