### ISSUE TITLE
task.memory inconsistent usage btw process definition and conf file

### ISSUE THREAD

**Issue by pauca** [nextflow-io/nextflow#244]
Task.memory is read from process definition, but not from configuration file.

To reproduce

nf.conf
```
profiles {
    standard {
        executor='local'
        memory='15 G'
     }
}
```

nf-tast.nf
```
ch = Channel.from( 1)
process p0 {
  	input: 
		val t from ch
	
	output: 
		val( f) into chout

	script:
	f = "${task.memory.toMega()}M"
	"""
		ls
	"""	
}
chout.subscribe { print "I say..  $it \n" }
```

nf-task2.nf
```
ch = Channel.from( 1)
process p0 {
	memory '1G' // <======= ADDED
  	input: 
		val t from ch
	
	output: 
		val( f) into chout

	script:
	f = "${task.memory.toMega()}M"
	"""
		ls
	"""	
}
chout.subscribe { print "I say..  $it \n" }
```

`nextflow nf-task.nf -c nf.conf ` => Cannot invoke method toMega() on null object
`nextflow nf-task2.nf`  \\ memory is read

Feature option: Could memory have a default value, like cpus? 

```
nextflow -v
nextflow version 0.22.4.4101
```

**Comment by pditommaso** [comment]
There's several problems here. First, the mem definition in the config file. It should be inside a `process` context eg. 

```
profiles {
    standard {
        executor='local'
        process.memory='15 G'
     }
}
```

Since this above is meant to define a default setting, it won't override the one defined in the script i.e. `memory '1G'`. 

If you want to override the definition in the pipeline script, you will need to specify the process name in the config file as shown below: 

```
profiles {
    standard {
        executor='local'
        process.$p0.memory='15 G'
     }
}
```
