### ISSUE TITLE
Supporting S3 working directories without using AWS Batch executor (?)

### ISSUE THREAD

**Issue by cnexcale** [nextflow-io/nextflow#2564]
Hello there,

we're currently trying to find a way to use an S3-compatible storage backend as a working directory in nextflow without having to use the AWS Batch executor. We want to use the OpenStack S3 API which is based on Ceph (https://docs.ceph.com/en/pacific/radosgw/s3/).
In the documentation it says that an S3 working directory is mandatory when using the AWS Batch executor but we couldn't find much information regarding other executor contexts.

So our question would be: Is this a usecase you, as the project maintainers, would basically want to support?

We've already done some local testing and debugging, encountered a few issues but also found some potential fixes, although we haven't found a working solution yet.
In case you would want to support this feature in general, we are of course willing to share all our findings and insights so far to get this feature to work.

Kind regards,
Lukas

**Comment by birnbera** [comment]
This would be very useful for me as well.

Another motivating use case is that, [according to the docs](https://www.nextflow.io/docs/latest/config.html#scope-process), you can mix executors in the same workflow. However, this is practically impossible since different executors require different types of work directories (e.g. S3 vs local). This came up for me when I found that I couldn't run a particular tool within a container, but wanted to execute the rest of the workflow on AWS Batch. You can't set a local path work directory with Batch, but you can't use an S3 work directory with the local executor.

**Comment by pditommaso** [comment]
As of version `22.10.x` this is supported using [Fusion file system](https://www.nextflow.io/docs/latest/fusion.html).
