### ISSUE TITLE
CLI process.key should override config

### ISSUE THREAD

**Issue by ellendejong** [nextflow-io/nextflow#2652]
### Expected behavior and actual behavior
Process resources provided via command line should override config file.
`nextflow run tutorial.nf -process.time='4m'`

**Expected:**

```
Hello world!
4m
```

**Observed:**

```
Hello world!
1m
```

### Steps to reproduce the problem
tutorial.nf 
```
#!/usr/bin/env nextflow

params.str = 'Hello world!'

process printString {

    output:
    stdout result

    """
    echo '${params.str}'
    echo ${task.time}
    """
}

result.view { it.trim() }
```
.nextflow/config 
```
process {

    withName:printString {
        cpus = 2
        memory = '5G'
	time = '1m'
    }

}


profiles {
    slurm {
        process {
            executor = 'slurm'
            queue = 'cpu'
        }
    }
}

```

### Program output 

```
N E X T F L O W  ~  version 21.04.3
Launching `tutorial.nf` [nice_volta] - revision: 3a6bc1b0e3
executor >  local (1)
[fb/a21f1e] process > printString [100%] 1 of 1 ✔
Hello world!
1m
```

### Environment 

* Nextflow version: 21.04.3
* Java version: openjdk  1.8.0_292-b10
* Operating system: linux, slurm
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

Without having a process dict in the config file, the process variable provided via CLI is used. 

Secondly, I tried to override process resources using the process selector as well.
For example `-​process.'withLabel:processLabel'.time='4m'`​ or simply by its name `-​process.printString.time='4m'`​.
Unfortunately without success. It seems impossible to override process resource via CLI at this moment.
Is this functionality supported or is it a new feature?

**Comment by SamStudio8** [comment]
Am I right in thinking that [this line is responsible for updating the process config with the command line arguments](https://github.com/nextflow-io/nextflow/blob/4e9189ac8e5fcead19b509f0905dc00607783fe1/modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy#L560)? It looks to me like this line can only change top-level keys relating to process configuration, such that the `-process.mykey myvalue` syntax can only emulate a config block like so:

```
process {
    mykey: "myvalue"
}
```

If that is the case, @ellendejong's example above would presumably just insert a process key called `withLabel:processLabel.time` or `printString.time` (or similar) into the configuration, rather than updating the `time` key inside those configuration objects as intended?

If I try to use the above syntax to replace the `withLabel:processLabel` process config key entirely, I get an error which suggests that I've overwritten the configuration object with a string that [cannot be parsed into a proper configuration](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/script/ProcessConfig.groovy#L335).

*i.e.*:

```-process.'withLabel:processLabel'='[container:"hoot"]'```

...will lead to:

```Unknown config settings for process labeled processLabel -- settings=[container:"hoot"]```

The way it is written it looks like the `-process.` CLI arguments are not designed to update keys inside of labelled processes?

**Comment by jorgeaguileraseqera** [comment]
As a workaround, with Nextflow version 22.02.1 you can use the following configuration:

```
process {

    params{
	printStringTime = '1m'  //or whatever you want
    }

    withName:printString {
        cpus = 2
        memory = '5G'
        time = params.printStringTime  //use default value if not overwrite
    }

}
```

and execute with:

```
nextflow run tutorial.nf 
N E X T F L O W  ~  version 22.02.1-edge
Launching `tutorial.nf` [friendly_carlsson] - revision: ee24b9b661
executor >  local (1)
[b1/482dd0] process > printString [100%] 1 of 1 ✔
Hello world!
1m
```


```
nextflow run tutorial.nf --printStringTime=14m
N E X T F L O W  ~  version 22.02.1-edge
Launching `tutorial.nf` [magical_ride] - revision: ee24b9b661
executor >  local (1)
[23/302156] process > printString [100%] 1 of 1 ✔
Hello world!
14m
```
(pay attention to the double minus symbol before printStringTime)

**Comment by SamStudio8** [comment]
Great minds, @jorgeaguileraseqera! Me and @mattdmem were just thinking along the same lines. We'll give this a go.

**Comment by ellendejong** [comment]
@jorgeaguileraseqera Thanks for the workaround suggestion. In my opinion, the workaround is not ideal in case of many processes, since it would increase the number of parameters immensely.
I really like the process specific configuration and would love to be able to override it. 

Within this bug report, I tried to separate the two issues:
1. Override of `process.key = value` impossible.
2. Feature request regarding override of the process selector values.

It appears that the second issue is indeed different than the design, so would become a feature request.
However, i do wonder about the first one. Is it correct that it is a bug?

**Comment by SamStudio8** [comment]
@ellendejong My understanding is that you can't override your `time` key in this way because the more specific `withName:printString` configuration block takes precedence over the command line `-process.time` argument.

**Comment by pditommaso** [comment]
The observed behaviour in the first comment is correct because the process selector has a higher priority compared to the default value provided by the command line option. 

See https://www.nextflow.io/docs/latest/config.html#selectors-priority

A valid workaround is the one provided [here](https://github.com/nextflow-io/nextflow/issues/2652#issuecomment-1096559840).
