### ISSUE TITLE
No task.exitStatus or errorStrategy for SLURM node failure of preemptible nodes on GCP

### ISSUE THREAD

**Issue by davidhbrann** [nextflow-io/nextflow#2672]
### Expected behavior and actual behavior

I'm running a nextflow pipeline for single-cell RNA-sequencing data on a SLURM cluster hosted on GCP. (e.g. via https://github.com/SchedMD/slurm-gcp). This version of SLURM allows for the creation of temporary nodes to run jobs on GCP. Some of the nodes run on preemptible instances. I would like the detect when these preemptible nodes fail and retry the process.

### Steps to reproduce the problem

When the Preemptible VM instances are killed the SLURM job fails with a `NODE_FAIL` state but the exit code (from slurm `sacct`) is still `0:0`. Therefore, it doesn't matches the `errorStrategy` in my `nextflow.config`:
```groovy
profiles {
    standard {
        process.executor = 'local'
    }

    cluster {
        process {
            executor = 'slurm'
            errorStrategy = { task.exitStatus in [9, 143, 137, 104, 134, 139, 247] ? 'retry' : 'finish' }
            maxErrors = '-1'
            maxRetries = 3
        }
    }
}
```

Is there a way to check if `task.exitStatus` is null and if so also retry it?

### Program output 

The output from nextflow is:
```
Error executing process > 'download_bam (2)'

Caused by:
  Process `download_bam (2)` terminated for an unknown reason -- Likely it has been terminated by the external system
```
And the corresponding line in the `nextflow.log` is:
```
 DEBUG nextflow.executor.GridTaskHandler - Failed to get exit status for process TaskHandler[jobId: 36093; id: 2; name: download_bam (2); status: RUNNING; exit: -; error: -; workDir: /mnt/disks/sec/David/nextflow/work/58/a03d5fd6256dd6c659517bdf734746 started: 1645655778818; exited: -; ] -- exitStatusReadTimeoutMillis: 270000; delta: 270007
```
[nextflow.log](https://github.com/nextflow-io/nextflow/files/8128502/nextflow.log)

### Environment 

* Nextflow version: version 21.10.6 build 5660
* Java version: openjdk version "17.0.1" 2021-10-19, OpenJDK Runtime Environment 21.9 (build 17.0.1+12)
* Operating system: Linux 3.10.0-957.21.3.el7.x86_64 x86_64
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by bentsherman** [comment]
What if you include `null` in your set of exit codes?
```
errorStrategy = { task.exitStatus in [9, 143, 137, 104, 134, 139, 247, null] ? 'retry' : 'finish' }
```

**Comment by davidhbrann** [comment]
I tried that but I don't think it worked. I also didn't try more complicated logic like `if(task.exitStatus == null) {errorStrategy = 'retry'}`. Instead, I just set `errorStrategy = 'retry'` to avoid this issue.

**Comment by bentsherman** [comment]
Yeah, that's what I have to do to deal with spot reclamation on AWS Batch. I think we have someone looking into a better way to handle these kinds of errors but I don't know the details.

**Comment by akraymund** [comment]
We've also given the null-check a try and that doesn't seem to work.

`errorStrategy = { (task.exitStatus == null || task.exitStatus in [143,137,104,134,139,247]) ? 'retry' : 'finish' }`

@bentsherman , any update on looking at a better way to handle these types of errors?

**Comment by bentsherman** [comment]
I think the applicable solution here is [this commit](https://github.com/nextflow-io/nextflow/commit/cd95e2976bb6f6bcee7b9b48a28ec167be2ddca1) which allows Nextflow to use the native retry in AWS Batch. So whenever a spot instance is reclaimed, AWS Batch will automatically retry the job without telling Nextflow, and when the job finally succeeds Nextflow will see it as a single successful attempt.

This is particularly helpful if you have dynamic resource settings that increase on each attempt, because ideally a reclaimed spot instance should just be retried with the same resources. But it should also help you guys because this way you don't need to add any extra logic to handle spot reclamations.

It looks like this feature is in the latest edge release. Let me know if it works for you!

**Comment by akraymund** [comment]
The change looks pretty specific to AWS Batch.  The situation we are seeing is with the exit code not being captured when a job is terminated on UGE.

this is the error on .nextflow.log
`Apr-06 18:53:01.240 [Task monitor] DEBUG nextflow.executor.GridTaskHandler - Failed to get exit status for process TaskHandler[jobId: 212948608; id: 27; name: BFX_PIPE:WGS:R2V:R2A:CAT_FASTQ (XU3561754); status: RUNNING; exit: -; error: -; workDir: /locus/home/dcooke/tickets/RDPB-352/AT2/work/5c/04206cffd850646b4a5d751018c076 started: 1649267287819; exited: -; ] -- exitStatusReadTimeoutMillis: 270000; delta: 274765`

**Comment by bentsherman** [comment]
Shoot... I'm sorry guys, I got mixed up and forgot this thread was for GCP. I guess we're back to square one. However, ideally I think we would want to implement a similar solution for preemptible VMs in GCP.

@akraymund Is your UGE cluster running on GCP? If you're on-prem then it's probably a different (although similar) cause from what the OP described.

**Comment by akraymund** [comment]
We're on-prem.

**Comment by bentsherman** [comment]
Okay, then I'll assume that your nodes aren't failing randomly if you're on-prem. INextflow might be having trouble getting job information from the scheduler. This kind of error can happen with grid executors like SLURM and PBS if Nextflow is submitting jobs or checking job statuses too quickly. The `executor` config scope has some options to control that behavior.

Aside from that, you should try to figure out if anything weird is going on with your nodes or jobs when this error happens, which I know is difficult because it's hard to reproduce. If you keep having this issue, I would create a separate issue so that we can stay focused on GCP preemptible VMs here.

**Comment by xrobin** [comment]
I don't know why this issue was closed, as clearly it hasn't been resolved.

I see something similar here with our SLURM scheduler. Sometimes some of our jobs run out of memory and get killed "violently" by SLURM. As a result, no .exitcode file is produced.

This would be fine if I could have an exit strategy checking for `task.exitStatus == null`. But somehow this doesn't catch the case

Here is the sacct output for one such job:
```
$ sacct -j 29806250
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
29806250     nf-score_+        dmz   swissmod          1 CANCELLED+      0:0 
29806250.ba+      batch              swissmod          1  CANCELLED      0:9 
```

**Comment by pditommaso** [comment]
@xrobin Please report the problem in a new issue including the `.nextflow.log` file
