### ISSUE TITLE
Output pipeline dag as a mermaid diagram

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2684]
[Mermaid](https://github.com/mermaid-js/mermaid) is a Javascript library that creates diagrams from a markdown-like syntax. Github recently [add support](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) for Mermaid rendering in markdown files, like this:

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

I think Nextflow's dag renderer would benefit greatly from supporting the Mermaid format. Nextflow just needs to generate the mermaid description, and then either return that as a text file or call the [Mermaid CLI](https://github.com/mermaid-js/mermaid-cli) if it is available. Even with the text description, the user could just paste that into a markdown file in their github repo and it will work out of the box.

I will probably take a crack at this when I have some time. Only thing I'm wondering is whether it should be part of the main codebase or a plugin.

**Comment by abhi18av** [comment]
Good idea Ben!

> Only thing I'm wondering is whether it should be part of the main codebase or a plugin.

I'd suggest that this should make it into the main codebase since it can be pasted directly into Github text boxes, in addition to just returning a text file and using the mermaid CLI [to generate the PNG](https://github.com/mermaid-js/mermaid-cli#convert-mermaid-mmd-diagram-file-to-svg). The current `Graphviz` installation process is a bit involved.

Thoughts?

**Comment by pditommaso** [comment]
The rending component in nextflow is quite extensible. Should not be too difficult to add it.
