### ISSUE TITLE
Add an option to specify the SINGULARITY_TMPDIR used in Nextflow (fix 'no space left on device' when /tmp is too small)

### ISSUE THREAD

**Issue by RaverJay** [nextflow-io/nextflow#2685]
## New feature

Add a setting to the singularity configuration scope that ensures that all singularity invocations see this value as SINGULARITY_TMPDIR in their environment.

Similar to `cacheDir`, it might be called `tmpDir` for example.

## Usage scenario 

This is needed whenever you cannot guarantee that /tmp is large enough on your host system, so you avoid running into this:
```
Command error:
  INFO:    Converting SIF file to temporary sandbox...
  FATAL:   while extracting /data/mahlzeitlocal/sebastian/cholera_schuldt/vibrio_nf/nf_downloads/quay.io-biocontainers-medaka-1.5.0--py38h9bf5490_1.img: root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-589451147/archive-970364270: no space left on device
```

And in general it is nice to have control over where temp data is written on your disk.

## Suggest implementation 

Not exactly sure of the optimal way to get this value to Singularity, I assume using SINGULARITY_TMPDIR works.

Cheers!

**Comment by bentsherman** [comment]
Could you do this through `singularity.runOptions` ? I feel like I've done similar things that way:
```
singularity {
    runOptions = "--bind \${SINGULARITY_TMPDIR}:/tmp"
}
```

**Comment by RaverJay** [comment]
> Could you do this through `singularity.runOptions` ? I feel like I've done similar things that way:
> 
> ```
> singularity {
>     runOptions = "--bind \${SINGULARITY_TMPDIR}:/tmp"
> }
> ```

Thanks for the suggestion!

As I understand it, such a bind for a path inside of the container is 'too late' - this only changes what is used inside of the container and not where the filesystem during container startup is stored

Or am I wrong with this?

**Comment by bentsherman** [comment]
That's right, you're talking about when the container image is launched. I don't remember all of the Singularity options, but surely `SINGULARITY_TMPDIR` can also be provided as a command-line argument to `singularity`? In that case you should be able to specify it in Nextflow via `singularity.runOptions` or `singularity.engineOptions`.

**Comment by RaverJay** [comment]
> surely `SINGULARITY_TMPDIR` can also be provided as a command-line argument to `singularity`

I thought so too. Sadly, I don't think that is the case, I searched for this specifically and didn't find that option

**Comment by RaverJay** [comment]
Bumping this, I still have not found any workaround / option to alleviate this problem

**Comment by bentsherman** [comment]
I'm a bit more familiar with the codebase now so maybe I'll have better odds this time :)

Judging from your error, I assume this is happening at the task level while the task is trying to execute the container. So it's already downloaded the container image which is handled by Nextflow. The relevant class for that is here: https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy

It looks like you have two options:
1. Add `SINGULARITY_TMPDIR` to the [`env` config scope](https://www.nextflow.io/docs/latest/config.html#scope-env). It will be in the task environment when the task runs `singularity exec ...`
2. It looks like the task will also use `TMPDIR` like so: `SINGULARITY_TMPDIR=$TMPDIR singularity exec ...`, so whatever you have as your `TMPDIR` will be used for singularity as well

In fact it looks like (1) might not work because it will always be overwritten by (2). But let me know if either of those options work for you.

**Comment by RaverJay** [comment]
For now, running on a machine with more /tmp space available works

(2) looks promising, not sure if I tested that before though

Thanks again for taking the time thinking about this =)

**Comment by emosyne** [comment]
I also have this problem. Any workarounds please?

**Comment by bentsherman** [comment]
You can try either of these suggestions: https://github.com/nextflow-io/nextflow/issues/2685#issuecomment-1104011261 https://github.com/nextflow-io/nextflow/issues/2786#issuecomment-1173975771

Let me know if either of them work for you.

**Comment by emosyne** [comment]
thanks a lot, the second one, particularly envWhitelist = ['SINGULARITY_TMPDIR'], did the trick.

**Comment by bentsherman** [comment]
Excellent, I will close out these issues then.
