### ISSUE TITLE
Cloud ssh key passphrase issue

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#269]
The issue I reported on google groups in 26 December is confirmed.

I have re-created the problem on Linux (SL6, openjdk 1.7) and on macOS using nextflow 23.

If I specify the ssh keyname associated with my Amazon account, then all is good.
If I don't so that it uses the default id_rsa and id_rsa.pub, the cluster launches with nextflow appearing to pick up the correct username and ssh keys, and I get given a sensible ssh command to try. However, I get prompted for a passphrase even if the key does not have a passphrase. I tried deleting all keys in my .ssh file and creating a fresh keys both with and without  a passphrase -- if I use a key with a passphrase it still doesn't work: I just repeatedly get asked for the passphrase.

One slighlt oddity, which may be a clue, is that when I first try to ssh into the machine, ssh complained about my *private* key having too weak permission and then that my public key had permission 0640 which was too weak (I've used this for years against a range of different systems). If I then change the permission of the public key to 0600 (which is the same as my private key) then the problem goes away (no more complaining about the ssh key)

Running ssh-add does solve the problem.

**Comment by pditommaso** [comment]
I'm still unable to understand if this is a NF issue or an expected SSH feature. It must be said that the passphrase is only used to to encrypt private key and it's managed by the SSH client, thus I tend to think that's a SSH expected behaviour. 

[Here](http://superuser.com/questions/156647/ssh-key-asking-me-for-a-passphrase) it's reported a workaround for the Mac SSH terminal.

**Comment by pditommaso** [comment]
Added a note in the documentation explaining to use the `ssh-add -K` command.
