### ISSUE TITLE
Use `publishDir` with `mode: 'copy'` on cluster to be executed on nodes rather than the master

### ISSUE THREAD

**Issue by Z-Zen** [nextflow-io/nextflow#2711]
## New feature

Add the ability to make `publishDir` with `mode: 'copy'` to copy files/folders from nodes to given path instead of the master when being used on a cluster.

## Usage scenario 

Currently, when using `publishDir` with `mode: 'copy'` on a cluster (e.g. `Slurm`), the master is in charge of making the copies from the working directory to the given path. However, this issue stresses the master, especially if there are many files to copy with many processes ongoing. Generally, the master has fewer computing capabilities than the computing nodes.  Would it be then possible to make this change?

## Suggest implementation 

[publishDir copy block](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy#L437-L439)

**Comment by mahesh-panchal** [comment]
If this is implemented, it should be an option. There are times when one just wants to just regenerate results after removing a results folder that potentially has old files in them. A user would not want to wait for the cluster to submit all the `publishDir` requests to a node just to republish cached files.

**Comment by Z-Zen** [comment]
@mahesh-panchal if you want to regenerate the result folder, this means something has changed in your pipeline. In this case, doing a simple resume should replace the old data with the new one, right? Or am I missing something?

**Comment by mahesh-panchal** [comment]
> @mahesh-panchal if you want to regenerate the result folder, this means something has changed in your pipeline. In this case, doing a simple resume should replace the old data with the new one, right? Or am I missing something?

It depends on the value of `overwrite`but this is besides the point:
>  overwrite | When true any existing file in the specified folder will be overridden (default: true during normal pipeline execution and false when pipeline execution is resumed).

The point however, is that the republishing of data with `-resume` is using `publishDir`, and from your suggestion this should be executed on a worker node rather than a head node. This means the `publishDir` request needs to be separately submitted to the cluster on `-resume`, which means spending time in the queue waiting subject to fair-sharing practices. This is likely a waste of resources. I understand for large numbers of processes, this is still taxing on a head node, but perhaps then supplying an alternative method of copying is a better solution. 
When using `process.scratch` the `stageInMode` and `stageOutMode` both support the use of `rsync`. Perhaps this should also be an option for `publishDir`'s `mode`. I'm not sure if this is a solution, since I think the `publishDir` copying is actually implemented in Groovy rather than Bash ( which means the code is run on the jvm, and for it to be run on a worker node would need to start up another instance of the jvm there ).

**Comment by Z-Zen** [comment]
Why would this need to be submitted separately as a job on the cluster? I mean, If a job runs locally, then the copy is made by the local machine. If the job is being submitted on the cluster, then the copy can be written inside `.command.run` and executed by the computing node.

But I do agree that this should be an option! Also good point for the rsync.

**Comment by mahesh-panchal** [comment]
> Why would this need to be submitted separately as a job on the cluster?

For the case where the `.command.sh` doesn't need to be executed, but the copying from workdir to publish does.

**Comment by Z-Zen** [comment]
I understand better now. Thank you for the feedback
