### ISSUE TITLE
nextflow workflow hung despite all processes exiting successfully

### ISSUE THREAD

**Issue by scottgigante-immunai** [nextflow-io/nextflow#2849]
### Expected behavior and actual behavior

My [workflow](https://github.com/openproblems-bio/nf-openproblems/blob/master/main.nf) successfully completes all steps, but then hangs indefinitely without running `workflow.onComplete`. The final line in nextflow.log seems to indicate the final process that executed was [`method_images`](https://github.com/openproblems-bio/nf-openproblems/blob/master/main.nf#L244), which should create new jobs to follow it -- I can't quite tell why it's hung.

### Steps to reproduce the problem

Contained at https://github.com/scottgigante-immunai/openproblems/runs/6299791249?check_suite_focus=true

### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/8628562/nextflow.log)

### Environment 

* Nextflow version: v22.04.0
* Java version: openjdk 17.0.2 2022-01-18
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by bentsherman** [comment]
Possible duplicate of #2693

**Comment by odoublewen** [comment]
Hi @scottgigante-immunai Were you by any chance using the `-all` release of 22.04.0?  (i.e. the one that is supposed to include all the plugins.)

I've also been experiencing nextflow hang on successful completion of the workflow, but have discovered that it only happens when I use `22.04.x-all` releases, such as: 
https://github.com/nextflow-io/nextflow/releases/download/v22.04.5/nextflow-22.04.5-all

If I use the minimal version, everything works fine and the process exits properly.

I've also seen that the `-all` release of `22.08.2-edge` works fine.  So, in my experience this is only happening for `-all` releases in the `22.04.x` series.

My hunch is that this is *not* a duplicate of https://github.com/nextflow-io/nextflow/issues/2693 -- the fix to which is (I think) included in 22.04.5.

**Comment by pditommaso** [comment]
> I've also seen that the -all release of 22.08.2-edge works fine. So, in my experience this is only happening for -all releases in the 22.04.x series.

It's possible, we had ugly problems related to shutdown mechanism on 22.x series including 22.4.x (stable). 

I strongly suggest using 22.10.x which solves those issue
