### ISSUE TITLE
splitText confusing

### ISSUE THREAD

**Issue by biowang** [nextflow-io/nextflow#29]
there is 50 lines in my valid file .
why I got only one file in the validUtrChannelSplit Channel?
I am confused.

here is my script
==================================================================
params.mirfile     = "/llwang-works/data/ceRNA/example_nextflow/data/mir.expr"
params.utrfile     = "/llwang-works/data/ceRNA/example_nextflow/data/utr.expr"
params.chunkSize   = 8

mirIo = file(params.mirfile)
utrIo = file(params.utrfile)

mirChannel  = Channel.from(mirIo)
utrChannel  = Channel.from(utrIo)

process validate_utr {
        input:
        file 'source' from utrChannel

        output:
        file 'valid' into validUtrChannel

        """
        perl /llwang-works/data/ceRNA/example_nextflow/scripts/validate.pl source > valid
        """
}

process validate_mir {
        input:
        file 'source' from mirChannel

        output:
        file 'valid' into validMirChannel

        """
        perl /llwang-works/data/ceRNA/example_nextflow/scripts/validate.pl source > valid
        """
}

validUtrChannelSplit = validUtrChannel.splitText(by: params.chunkSize)
process task_cat {
        input:
        file 'seq' from validUtrChannelSplit
        file 'db'  from validMirChannel
        output:
        file 'out' into corChannel

        """
        cat seq > out
        """
}

**Comment by pditommaso** [comment]
The problem should be in the last process, replace 

    file 'db' from validMirChannel

with 

    file 'db' from validMirChannel.first()

When process has multiple input channels, they should have the same cardinality i.e. emit the same number of items, otherwise the process will stop as soon as all items in the "shortest" channel are consumed. 


A workaround is using the `first` operator on the channel that is supposed emit the always the same value. Doing this the framework will handle it as a *singleton* value. 

Please use the forum for further questions 
https://groups.google.com/forum/#!forum/nextflow
