### ISSUE TITLE
Pbspro executor: qsub/qstat does not retry on fail

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2979]
Each run of `qsub`/`qstat` can fail, e.g., `connection refused` because PBS server is just restarting. We should retry with exponencial backoff similarly to K8s executor.

We can implement this here: https://github.com/nextflow-io/nextflow/blob/2b6f70a8fa55b993fa48755f7a47ac9e1b584e48/modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy#L188 to catch some output types and return exception that do retry? Or do it right here, not sure as it should retry only few times with sleep.

**Comment by bentsherman** [comment]
> PBS server is just restarting

Does that happen often for you? I think Nextflow generally assumes that the HPC scheduler will stay alive and not reboot.

On the other hand, I have heard of cases where a workflow node can't maintain a stable enough connection with the HPC scheduler, which breaks Nextflow because it expects to be able to poll job status frequently. It would be good to make Nextflow more resilient in this aspect.

Anyway, I believe your code suggestion is correct regarding the submission of jobs. We should also look at the code that polls job status and see if we can improve the error handling there.

**Comment by xhejtman** [comment]
We see PBS server restart like once a day. However, using the Sarek pipeline that cointans Base Recalibrator processes causes flooding the PBS server because there several thousands of these processes and they rapidly wax and wane. (duration of some of them is like 10 seconds) and this can lead to temporary denial of service of PBS server.

I know one can configure submission rate but in this case, you slow down whole computation..

**Comment by pditommaso** [comment]
Consider using HyperQueue executor  https://github.com/nextflow-io/nextflow/issues/2867

**Comment by bentsherman** [comment]
I think you should consider tuning your [executor settings](https://www.nextflow.io/docs/latest/config.html#scope-executor) before you draft a PR. In particular:
- pollInterval
- dumpInterval
- queueStatInterval
- submitRateLimit
- retry.*

You can control both the submission rate and the status polling rate. Note that the submission rate is unlimited by default, so even limiting it to 10/s or 100/s can greatly improve stability while still submitting jobs quickly. The polling interval can be equally important, I just don't know what the default is.

NERSC has an excellent page about Nextflow where they show how to configure Nextflow in order to not overwhelm their SLURM cluster: https://docs.nersc.gov/jobs/workflow/nextflow/#nextflow-submits-tasks-as-slurm-jobs.

Also it looks like there are already some executor settings for retrying job submissions, so I think they should suit your purposes.

**Comment by xhejtman** [comment]
this is what I get most often as error with pbspro executor. Can this be avoided using retry.* ? If so, could you provide simple examle? Thanks.

```
Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  qsub -N nf-GenotypeGVCF .command.run

Command exit status:
  111

Command output:
  Connection refused
  qsub: cannot connect to server meta-pbs.metacentrum.cz (errno=111)
```

**Comment by pditommaso** [comment]
Well spotted, thik we should make a follow-up up the [for Nextflow user on HPC](https://www.nextflow.io/blog/2021/5-more-tips-for-nextflow-user-on-hpc.html#) blog post series, to mention this feature that at time of writing didn't exist

**Comment by xhejtman** [comment]
I can confirm that `retry.reason = '.*'` fixes all `qsub` issues, however, I confirmed that `qstat` issues are still present, e.g., if restarting PBSPro server, `qstat` fails together with the whole pipeline. And we restart PBS server about once a day.

**Comment by bentsherman** [comment]
I see. I don't think any of the Nextflow executors operate with the assumption that the scheduler will experience regular downtime like that. The best suggestion I can give is to experiment with `executor.queueStatInterval`, e.g. if you know that the PBS restart takes about 5 minutes, then increase this setting to `10min`. It's not foolproof though.

If your server is restarting because it is overwhelmed by jobs, I agree with Paolo that you should look into the hyperqueue executor that was recently added to Nextflow. I think it is better than traditional HPC schedulers at handling high-throughput workloads.

**Comment by xhejtman** [comment]
> I don't think any of the Nextflow executors operate with the assumption that the scheduler will experience regular downtime like that. 

this is not completely true as kuberun + k8s exectuor is currently (mailny with jobs) almost immortal ;) Especially k8s has retries when API is down and so on, thus I meant if we can have something similar with PBS/Grid. It should not be very complicated. I tested in dedicated PBS cluster with wrapper around `qsub` and `qstat` so they never fail and pipeline finishes in single run. I had to resume like 8 times before.

**Comment by xhejtman** [comment]
it seems that even `retry.reason = '.*'` does not catch:
```
Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  qsub -N nf-GenotypeGVCF .command.run

Command exit status:
  183

Command output:
  qsub: Premature end of message
```

is it a bug?

**Comment by pditommaso** [comment]
It should work, the code is here https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy#L118-L130

**Comment by pditommaso** [comment]
I'm closing this because it's not clear the current status. Feel free to reopen it if it's still an issue.
