### ISSUE TITLE
errorStrategy advice with exit status > 0

### ISSUE THREAD

**Issue by MaestSi** [nextflow-io/nextflow#2992]
Dear all,
I am currently integrating [TRF](https://github.com/Benson-Genomics-Lab/TRF) in a NextFlow pipeline. However, with the tool's version I'm currently using "TRF would have a non-zero exit status which was to be interpreted by the user as the number of TRs processed".  I tried `using errorStrategy = 'ignore'`, but it seems it is not doing what I would like it to do, as it is not allowing the remaining part of the process to be executed (consisting of other runs of TRF with different parameters). Is there a way I can manage to avoid this issue?
Thanks in advance,
Simone

**Comment by bentsherman** [comment]
Nextflow used to have a `validExitStatus` directive that allowed you to specify which exit codes should be considered successful. But that directive was deprecated and removed because I think it had some issues.

The recommended way to handle this kind of problem is to add some bash logic to your process script, such that it returns a 0 exit code at the end. For example:
```bash
bash -c 'exit 2' || echo "processed $? TRs"
```

The first bash command represents a process that returns a non-zero exit code, and I use or (`||`) to "catch" that exit code, print it, and return 0 exit code like normal.

**Comment by MaestSi** [comment]
Thank you very much, that worked like a charm!
Simone
