### ISSUE TITLE
Make `queueSize` work normally on AWS Batch

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#3076]
The `executor.queueSize` config option limits the number of concurrent tasks for a workflow run. That is, it works like this for every executor except for AWS Batch, which has its own option called "queue size" that means something else.

We can easily create a separate config option to map to the AWS-specific setting, but the greater challenge has to do with how the `awsbatch` executor manages jobs. Basically, the executor submits and polls jobs in batches, in order to minimize the rate of API calls. This "batch context" operates like a cache, which makes some operations more complicated. The `queueSize` config option influences whether an individual job will be submitted or delayed, but when jobs are submitted in batches, the logic will look more like "how much of this batch can be submitted at once".

I think to implement `queueSize` correctly, there will be a tradeoff between bandwidth and latency. You can submit larger batches less frequently, or smaller batches more frequently. This would be controlled by an AWS parameter e.g. `aws.batch.submitBatchSize`. For example, if the batch size is 50, Nextflow will wait for 50 jobs to be generated before submitting them. If the workflow generates fewer than 50 jobs, Nextflow needs some way to know that no more tasks are coming and submit a partial batch.

**Comment by pditommaso** [comment]
I think the problem is that the [capacity](https://github.com/nextflow-io/nextflow/blob/a55f58ff9de8d199335c51bd788c2b84be2b16ea/modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy#L185-L185) is not set by the [ParallelPollingMonitor](https://github.com/nextflow-io/nextflow/blob/a55f58ff9de8d199335c51bd788c2b84be2b16ea/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy#L196-L197) 

The rationale was to use it form the [thread pool queue size](https://github.com/nextflow-io/nextflow/blob/a55f58ff9de8d199335c51bd788c2b84be2b16ea/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy#L220-L220), but better to introduce the a new setting for the latter and use the executor queue size in the "classic" pattern
