### ISSUE TITLE
suggestion:  run -dry

### ISSUE THREAD

**Issue by andrewcstewart** [nextflow-io/nextflow#31]
A dry run option would be great for validating a pipeline script without actually executing any processes.

**Comment by pditommaso** [comment]
That would be useful, with @emi80 we discussed a bit about that. 

The problem is that it's pretty to implement in the dataflow model on which Nextflow is based, because you need always an event i.e. a piece of data to trigger a process/operator execution. 

In my opinion the easiest workaround is to have always in your pipeline a tiny dataset that can be used to validate the script execution.

**Comment by pditommaso** [comment]
No plan to implement it due to the reason explained above. We may take in consideration if we find a way to handle a `dry-run` execution on top of the dataflow paradigm.
