### ISSUE TITLE
Feature request: Specify Dockerfile instead of an Image

### ISSUE THREAD

**Issue by pbelmann** [nextflow-io/nextflow#320]
There should be a way to specify a Dockerfile for a process in addition to an image name.
When a developer builds a docker image it sometimes does not make sense to push it to a remote respository like Dockerhub because for example

1.The image needs to be tested first

2.The image should not be publicly available

3.The image has just a simple installation so that it is unnecessary to provide it on a central repository. (for example: ubuntu:16.04 with bc installed)

I know that for all 3 points a private repository is a solution but by providing a Dockerfile the development could be made faster and easier because nextflow builds the image directly without the need of pushing it to private or public repo first.

I think of something like:

~~~BASH
process TestProcess {

    container 'myImage:latest', Dockerfile: /path/to/dockerfile, force: true

    input:
    ...
    
    output:
    ...

    shell:
    ...
}
~~~

The TestProcess would check if the image exists on the host, if not it checks if a Dockerfile is specified.
If the Dockerfile is specified it builds the image otherwise it pulls it from a repository.
If Dockerfile is specified and force is set true, the image should be rebuild (maybe on the initial setup?) even if it exists.

**Comment by pditommaso** [comment]
Hi Peter, I thought  a bit to this proposal but I'm not sure that a good idea to have NF building a Docker container image. Main reasons are: 

1. Separation of concerns: a (NF) workflow should use an existing container. It's not its role to build container images.
2. Container agnostic: NF already supports Docker and Singularity (actually also Shifter though is undocumented) and it will eventually supports more engine in future. I don't want to take care of the different building process for each different technology. 
3. Limited reproducibility. the Dockerfile is not reproducible over time (packages can be retired, URL can brake, etc). I understand that what you are prosing is a convenience for development purpose. However I fear that people will start to use it to share containers as Dockerfiles instead of using binary images, ultimately reducing the reproducibility/replicability of NF workflows.

**Comment by pbelmann** [comment]
I see. I agree with the point that using a Dockerfile in NF could cause limited reproducibility.
