### ISSUE TITLE
Make exception texts red

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#3246]
Over in https://github.com/nf-core/tools/issues/1840 we are switching out `log.error`/`System.exit(1)` with `throw new Exception`.

The output is almost identical, except that the text from `log.error` is red, and the text from `throw new Exception()` is not:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/465550/192254225-7e64f84e-4eca-48de-88b6-d6faf349608f.png">

The red text really helps draw the user's eye to what is wrong.

Any chance that Nextflow could do the same when printing exception texts?

**Comment by pditommaso** [comment]
Good point, we can look into it

**Comment by bentsherman** [comment]
Here are my findings from a quick investigation.

`ScriptRunner` catches any exception and aborts the session before forwarding the exception: https://github.com/nextflow-io/nextflow/blob/021d898944428a8883fd73f3058aafc2043b0cca/modules/nextflow/src/main/groovy/nextflow/script/ScriptRunner.groovy#L137-L140

`Session.abort()` in turn does a bunch of cleanup, including the ansi-log observer: https://github.com/nextflow-io/nextflow/blob/021d898944428a8883fd73f3058aafc2043b0cca/modules/nextflow/src/main/groovy/nextflow/Session.groovy#L754

The exception bounces all the way back up to `Launcher`, which calls `log.error`: https://github.com/nextflow-io/nextflow/blob/021d898944428a8883fd73f3058aafc2043b0cca/modules/nextflow/src/main/groovy/nextflow/cli/Launcher.groovy#L535-L538

The error message originates from `LoggerHelper`, and there appears to be an issue in that the ansi-log observer has already been shut down before the error is logged: https://github.com/nextflow-io/nextflow/blob/021d898944428a8883fd73f3058aafc2043b0cca/modules/nextflow/src/main/groovy/nextflow/util/LoggerHelper.groovy#L645-L648

If not for the session already being aborted, I think this error would be red. So we may need to adjust the lifetime of the session and its internals in order to fix this issue.

**Comment by ewels** [comment]
A simple but hacky fix would be to take @robsyme's suggestion and just print the ansi codes in the [`error` function](https://github.com/nextflow-io/nextflow/blob/f38fd2db57baa98249c9cd9454a29bdae22e7f2c/modules/nextflow/src/main/groovy/nextflow/Nextflow.groovy#L257-L263) directly:

```nextflow
    /**
     * Throws a script runtime error
     * @param message An optional error message
     */
    static void error( String message = null ) {
        throw message ? new ProcessUnrecoverableException("\033[0;31m"+message+"\033[0m") : new ProcessUnrecoverableException()
    }
```

Ugly but would presumably work with minimal changes..

**Comment by pditommaso** [comment]
Better to avoid. This spam the logs with all those escaping chars. The [AnsiLogObserver](https://github.com/nextflow-io/nextflow/blob/021d898944428a8883fd73f3058aafc2043b0cca/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L39-L39) takes care to apply colours when possible.

**Comment by ewels** [comment]
Still valid

**Comment by pditommaso** [comment]
Closing as for previous comment

**Comment by ewels** [comment]
Ok, so you basically think it's not possible? Fair enough 👍🏻

**Comment by pditommaso** [comment]
It's more that we have colours in the ANSI logging, which is enabled by default. The non-ansi is usually used when running in the background on via managed system (e.g. Tower) where escape  codes are not interpreted (e.g. cloudwatch stream).

**Comment by ewels** [comment]
Ok! Maybe we can keep `log.error` with a longer user friendly explanation and then throw the exception with a very short text. Basically the same as what we had before, but without using the system exit. Then we keep the nice clear error text.

**Comment by pditommaso** [comment]
It sounds good. The important thing is not to use `System.exit`!
