### ISSUE TITLE
Allow setting different secret values to the same name for different processes

### ISSUE THREAD

**Issue by Midnighter** [nextflow-io/nextflow#3261]
## Usage scenario 

Some of my processes share the same name for an environment variable that I would like to manage by secrets. At the moment, it's only possible to have one value per secret name. I would like to assign different secret values to different processes that use the same name.

## Suggest implementation 

Maybe this could be configured using a map, rather than a list for secrets.

```nextflow
process {
    withName: PROCA {
        secrets = [GITHUB_TOKEN: 'PROCA_TOKEN']
    }
    withName: PROCB {
        secrets = [GITHUB_TOKEN: 'PROCB_TOKEN']
    }
}
```

**Comment by bentsherman** [comment]
I don't think this is feasible because it would require you to put the secret tokens in your nextflow config. Instead you should use a different name for each secret and map it to the correct name in the process script.

```groovy
process PROCA {
    secret 'GITHUB_TOKEN_PROCA'
    """
    GITHUB_TOKEN=\$GITHUB_TOKEN_PROCA
    """
}

process PROCB {
    secret 'GITHUB_TOKEN_PROCB'
    """
    GITHUB_TOKEN=\$GITHUB_TOKEN_PROCB
    """
}
```

**Comment by Midnighter** [comment]
It was just an idea for a possible mechanism. I think, it will need work to extend the secrets functionality.

While your suggestion is feasible in general, it doesn't work in my particular case. Basically, I have one module that requires the `GITHUB_TOKEN` secret and I import it under two different aliases. So changing the name of the secret somehow has to happen before the process is run.

**Comment by bentsherman** [comment]
So if I understand correctly, when you said `[GITHUB_TOKEN: 'PROCA_TOKEN']` you were aliasing the name rather than the secret value, and you want to define this alias outside of the process definition in order to keep the process generic.

For what it's worth, you should be able to accomplish it with the `beforeScript` directive, although it gets hairy if you need to inject multiple `beforeScript`s from different sources.

Your suggestion would be simple enough to implement. My only reservation is that I suspect this problem might occur for many different directives when using process modules, and I wonder if there is a more generic way to address it instead of extending individual directives. For example, I think most of these issues can be addressed with `beforeScript`, but in that case Nextflow really needs to be able to automatically merge multiple `beforeScript` values like it does with `label`, `pod`, etc.

**Comment by Midnighter** [comment]
> So if I understand correctly, when you said [GITHUB_TOKEN: 'PROCA_TOKEN'] you were aliasing the name rather than the secret value, and you want to define this alias outside of the process definition in order to keep the process generic.

Yes exactly, it was about the name. Although, in the end, what I care about is that I can assign the correct one of many different secret values to one particular secret name for the right process.

Hmm, your point about `beforeScript` is a good one if that can be configured. So something like the following would solve my problem.

```nextflow
process {
    withName: PROCA {
        secrets = ['PROCA_TOKEN']
        beforeScript = 'export GITHUB_TOKEN="\${PROCA_TOKEN}"'
    }
    withName: PROCB {
        secrets = ['PROCB_TOKEN']
        beforeScript = 'export GITHUB_TOKEN="\${PROCB_TOKEN}"'
    }
}
```
