### ISSUE TITLE
-resume integrated with different work directory

### ISSUE THREAD

**Issue by ashdederich** [nextflow-io/nextflow#3286]
## New feature

Nextflow is awesome! I love the ability to use the resume option. However, I have run into an issue with the -resume tag. I am working on a cluster environment, where the scratch directory is in a different place than the nextflow files. I specify this through the command line using -w /path/to/scratch/dir. When a process is terminated and I want to resume that process later with the -resume tag, it does not resume and instead starts from the beginning. Is there a way to implement the resume feature to work with a work directory that is not in the directory of the rest of the nextflow files?

## Usage scenario 

```
nextflow run file.nf -w /path/to/scratch/dir -resume
```
or
```
nextflow run file.nf -w /path/to/scratch/dir -resume /path/to/scratch/dir
```

I've looked through the documents and maybe this feature exists and I am implementing it wrong, or maybe missed it in the docs?

Thank you!
Ashley

**Comment by bentsherman** [comment]
The resume should work as long as you use the same work directory and `.nextflow` cache. Are you launching the workflow from the same directory every time?

Also, not sure if you meant it this way, but individual tasks cannot be recovered unless they completed. So resuming a workflow will only recover tasks that completed successfully.

**Comment by ashdederich** [comment]
Hi, I'm bringing this back up because this is the first time I got to test the -resume functionality after submitting this issue.

I'm using the exact same work directory (and should be using the same ```.nextflow``` cache. However, the resume tag is not resuming from the previously completed step (also @bentsherman, you are correct, I misspoke in my original post about resuming individual tasks!).

I've attached a couple of screenshots showing what I am seeing. Am I missing something?

Thank you!

Also note - the first process is super quick, so I wasn't able to take a screenshot before it finished. The process 'resumed' on the first step (pwdloaddata).
<img width="1432" alt="Screen Shot 2022-10-27 at 9 10 50 AM" src="https://user-images.githubusercontent.com/42787542/198331703-bfee8483-e363-4a9e-87ec-7ec752eb7b07.png">
<img width="1267" alt="Screen Shot 2022-10-27 at 9 11 15 AM" src="https://user-images.githubusercontent.com/42787542/198331741-588253d3-a147-49a4-945e-ae9f41b4bf89.png">

**Comment by bentsherman** [comment]
Hi Ashley, sometimes the resume has trouble on HPC systems because the work directory resides in networked storage and the file timestamps get out of sync. You can set the `cache` directive to `'lenient'` to make the resume ignore timestamps: https://www.nextflow.io/docs/latest/process.html#cache

If you could try that, it will help us narrow down the root cause.

Quick question, does your pipeline use the `collect` or `collectFile` operator at all? Particularly near the beginning?

**Comment by ashdederich** [comment]
Hi Ben,

Okay I was able to add ```cache 'lenient'``` to the beginning of each process and it resumed successfully. Thank you!

My pipeline does not currently use the ```collect``` or ```collectFile``` operator at all. However, I believe that I might have to use them toward the end of my pipeline to collect all of the output from each instance of one process and pass it to the last process. Would that cause issues with resume?

**Comment by bentsherman** [comment]
We are still investigating, but a common thread between many of these resume issues is the collect and collectFile operators. The theory is that these operators combine their incoming items into a list, and because everything is asynchronous, the resulting list might be different each time and break the resume.

In your case, if you have a final process after a collect, then at worst that final process might not resume correctly. If that happens to you when you get there, let us know as it would be more evidence for our theory. 😄
