### ISSUE TITLE
fix workflow.revision

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#329]
when executed locally, `workflow.revision` is `null`, but Nextflow still display a revision.
```
Launching `./main.nf` [sharp_northcutt] - revision: 909c2f2293
workflow.revision: null
workflow.scriptId.substring(0,10): 909c2f2293
```
I do think it should display the first 10 characters of `workflow.scriptId` instead.
Intended behavior:
```
Launching `./main.nf` [sharp_northcutt] - revision: 909c2f2293
workflow.revision: 909c2f2293
workflow.scriptId.substring(0,10): 909c2f2293
```

**Comment by pditommaso** [comment]
It must be noted that in the execution log the term *revision* is used with a more wide meaning. Basically it reports the branch/tag name when available (`workflow.revision`), otherwise fallback on the Git commit-id (`workflow.commitId`). If also the commit-id is missing it fallback on the script-id (content unique hash, `workflow.scriptId`). 

It think it makes sense keep separate these data, noting it's straightforward to same logic in your script just using

```
def rev = workflow.revision ?: workflow.commitId ?: workflow.scriptId
```

**Comment by MaxUlysse** [comment]
Make senses that way.
Thanks
