### ISSUE TITLE
Nextflow in Docker but with sibling task containers

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#3335]
See this Slack thread for the original discussion: https://nextflow.slack.com/archives/C02T98A23U7/p1667329586435039?thread_ts=1664216236.425379&cid=C02T98A23U7

A user found a way to run Nextflow in Docker in such a way that Nextflow submits tasks as sibling containers in the host environment. Apparently this command takes care of it all:
```bash
docker run -it --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /path/to/nxf_data:/path/to/nxf_data \
    -w /path/to/nxf_data \
    -e "NXF_HOME=/path/to/nxf_data" \
    nextflow/nextflow:latest \
    nextflow run [...]
```

Basically, the nextflow container mounts the docker service from the host, so task containers are routed back to the host environment, and the nextflow container mounts a host directory that will be used by the task containers.

I haven't tested it myself, but it might be something we could add to the docs as a way to run everything in Docker, as it eliminates the need to install Java or Nextflow.

@mribeirodantas might be an interesting thing for you to try out.

**Comment by pditommaso** [comment]
This existed since ages with the `-dockerized` option 

https://github.com/nextflow-io/nextflow/blob/master/nextflow#L226-L239

**Comment by bentsherman** [comment]
I didn't realize the `-dockerized` option also uses sibling containers...

However, the `-dockerized` option still requires you to install Nextflow and Java. I think the user who started that thread was looking for a way to launch a dockerized Nextflow pipeline without installing Nextflow or Java beforehand.

**Comment by pditommaso** [comment]
> However, the -dockerized option still requires you to install Nextflow and Java

Not really

**Comment by bentsherman** [comment]
Hmm, so you would do something like `docker run nextflow/nextflow nextflow run -dockerized [...]` ... ?

If that is the case, it is not obvious from the docs: https://www.nextflow.io/docs/latest/cli.html#docker-driven-execution

This section gives an example as:
```bash
nextflow -dockerize run nextflow-io/hello
```

which suggests that you have to install nextflow in order to use the `-dockerize` option.

**Comment by bentsherman** [comment]
Also if the `-dockerize` option already works this way then we should merge #3148

**Comment by pditommaso** [comment]
> Hmm, so you would do something like docker run nextflow/nextflow nextflow run -dockerize [...]

Nope, just `nextflow run -dockerize`. `nextflow` is Bash, when you specify `-dockerize` it runs through docker instead the jvm

**Comment by bentsherman** [comment]
Okay, I see what you mean, the code you linked shows how the nextflow script basically re-launches itself in a docker container. But that requires you to have Nextflow and Java installed.

If you wanted to launch a purely Dockerized Nextflow pipeline, you would do something like:
```bash
docker run nextflow/nextflow nextflow run [...]
```

But that won't work because Nextflow-in-the-container will see the `.dockerized` folder and know it's already in a container, so it will run normally, which means it won't launch tasks as sibling containers.

So we still need the command I originally posted. I realize that you basically embedded this command in the Nextflow binary, but you have to install Nextflow and Java to use it...

**Comment by pditommaso** [comment]
You don't need java with `-dockerized`

**Comment by mshunjan** [comment]
So I think the key-part of my use-case in that slack discussion was that I was starting nextflow from within a container. I am essentially running multiple services using docker-compose, and I wanted one of those services to launch sibling containers. In that scenario, the `-dockerized`  flag does not work, and you get the following error because of the bind mount issue: 
```bash
/bin/bash: .command.run: No such file or directory
```
You can't communicate between host processes and docker containers, as the whole purpose of the container is to isolate your process, so everything needs to be done from within the container. In this very specific scenario, my proposed solution lets nextflow do exactly that.

**Comment by mshunjan** [comment]
Also I don't know if this is the appropriate thread to mention this in, but the `-dockerized` functionality is broken at the moment. You get the following error when using it as intended: 
```bash
/usr/local/bin/entry.sh: line 46: addgroup: command not found
adduser: group 'docker' does not exist
chown: invalid user: ‘nextflow’
su: user nextflow does not exist
```
There does however seem to be an open PR about it #3137.

**Comment by bentsherman** [comment]
Thanks @mshunjan for adding your context. We will get that PR merged in due time I'm sure.

As for this issue, I think there are two things we can do here:
1. Add some clarification to the docs on how to do a minimal-install dockerized Nextflow run
2. Modify the `-dockerize` docker command embedded in Nextflow with the tweaks you made to make it work

Looking at your docker command and the command that is embedded in Nextflow, do you think it can be tweaked to fit your use case?

https://github.com/nextflow-io/nextflow/blob/bae749fa89804b5286f97c4e222d791f2b8a4fb6/nextflow#L226-L238

**Comment by pditommaso** [comment]
I think this is provided by the `-dockerize` option. Inclined to close it ?

**Comment by mshunjan** [comment]
Hi guys sorry for the late reply. I would say the `-dockerize` option does not cover my use-case, and tweaking it to fit my use-case may be difficult, as the purpose seems to be quite different. @pditommaso I can't see how `dockerize` could work within a container, since it does bind mounts, meaning sibling containers would not be able to access any of the data stored on the master container required for running a process (.command files, input data, etc.). There may be some solution with named volumes, as these can be shared by containers, but I think it would have to be a different command (ex. `-in-docker`, but this may be very confusing for users).

**Comment by pditommaso** [comment]
The `-dockerize` allows to run nextflow within a container, and spawn child jobs as sibling containers. So, what's the difference in your use case?

**Comment by mshunjan** [comment]
My use-case is launching from within a container, not the host. The setup is different.
