### ISSUE TITLE
Allow to publish timeline, trace and DAG files as a Tower report

### ISSUE THREAD

**Issue by jordeu** [nextflow-io/nextflow#3460]
## New feature

Current Tower plugin is only able to use as reports files that are notified with the `onFilePublish` event. This excludes some files generated by Nextflow like the timeline, trace and DAG files.

Allow the Tower plugin use these files too. 

## Usage scenario 

- A user wants to add the pipeline timeline as a final report and visualize it directly in Tower
- A user wants to download the trace file from Tower
- A user want to download or visualize the DAG file from Tower.

## Suggest implementation 

Trigger a `onFilePublish` event for each of these files.

**Comment by stevekm** [comment]
since Tower already is aware (?) of the config of the running pipeline, would it be possible for Tower to just check the config after the pipeline completes and see if there are config entries for the report, DAG, and trace, and check if they exist, and add them to the Tower run output? 

so that you would basically offload the task to Tower to try to intelligently find the files, instead of modifying the behavior of Nextflow in order to signal it to Tower

not sure if that would be a better or worse option for this functionality

**Comment by bentsherman** [comment]
@stevekm thanks for the suggestion, that is indeed much simpler and I believe it is the direction we will pursue with the Platform team
