### ISSUE TITLE
Google Batch spot enabled configuration for processes

### ISSUE THREAD

**Issue by schuyler-smith** [nextflow-io/nextflow#3530]
## New feature

When using Google Batch, it'd be nice if **spot** could be enabled for individual processes. The reason being, in some pipelines I may have processes that run over 1 hour that cannot be paused and restarted, running the risk of them wasting hours of compute time, or possibly never finishing at all, if the spot resources are reclaimed. I haven't experimented to see if the `maxSpotAttempts` configuration would prevent the fail for Google Batch, but all the same it would be nice to be able to have on-demand be able to be set as the default.

Apologies if I have missed something in the documentation about this. I did try setting `google.batch.spot = true` within a `withName` config, but that seemed to still enable it for the entire workflow.

## Usage scenario 

As above.

## Suggest implementation 

Simply as an end-user, I do not know enough about the architecture of Google Batch or NextFlow's interaction with it to know how feasible this is. Currently the implementation is at the workflow level, but it would be nice to have it as a configuration for the process, the same way that `machineType` works and is implemented for Google Batch processes.

Thanks!

**Comment by MattWellie** [comment]
@bentsherman @schuyler-smith this issue was raised and closed as completed, but I can't see a linked change or anything in documentation.. Is this still an unsupported mode/behaviour?

We are moving to NextFlow and deploying to google-batch, where the majority of jobs will be spot, but some large tasks would benefit from being non-spot (multi-hour runtime, spinning up and monitoring a dataproc cluster). There's no effective way to reduce this large task to a smaller series of tasks, so being able to set individual jobs to spot=False would be a major win.

**Comment by bentsherman** [comment]
We added a `hints` directive (#7034) in 26.04, and the ADR even mentions this issue, but it looks like we didn't actually implement anything for google batch. Feel free to submit a PR for it, seems like it would be trivial to implement a `google-batch/spot` hint
