### ISSUE TITLE
`task.cpus` in script directive affects resume behaviour

### ISSUE THREAD

**Issue by saulpierotti-ebi** [nextflow-io/nextflow#3581]
## Bug report 

When using `${task.cpus}` inside the script directive to pass the number of cores to use to a tool the cache is invalidated when changing the value of the `cpu` directive.

### Expected behavior and actual behavior

The number of core specified in the `cpu` directive should not affect the resume behaviour, but the cache is invalidated when `${task.cpus}` is used as part of the `script` directive.

### Environment 

* Nextflow version: 22.04.4.5706
* Java version: openjdk 11.0.15
* Operating system: RHEL 8.5
* Bash version: zsh 5.5.1

### Additional context
I think the behaviour is due to the fact that the `${task.cpus}` variable is replaced by its value before calculating the hash for the script directive, so the content of the `script` directive changes when the number of cpus specified changes.

**Comment by bentsherman** [comment]
You are correct, any changes to the script text will invalidate the cache.

Unfortunately, I don't think anything can be done here, because there is no clean way to tell whether any particular change to the script affects reproducibility. Nextflow errs on the side of safety by assuming any change should trigger a re-run.

**Comment by jemunro** [comment]
I think we need better solution to this, otherwise [dynamic computing resources](https://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources) specification are always going to cause friction on pipeline resume.

One potential way to implement it would be through bash variables. E.g. Nextflow could export variables such as NXF_TASK_CPUS NXF_TASK_MEM_GIGA etc. That would allow the script to stay unchanged. E.g.:

```nextflow
process DO_SOMETHING {
  cpus   { 1    * task.attempt }
  memory { 2.GB * task.attempt }
  
  input: path input
  output: path output
  script:
  """
  something --in $input --out $output --cpus \$NXF_TASK_CPUS  --mem \$NXF_TASK_MEM_GIGA
  """
}

```

**Comment by bentsherman** [comment]
@jemunro I don't actually know what happens if a task fails, then succeeds on a second attempt, and then later you try to resume the entire run. I don't know if the second attempt will be resumed properly, if the resources were dynamic.

If you can create a test case to show that it doesn't resume properly, then we could look into it. But we would probably solve it by adjusting how tasks are cached and recovered.

**Comment by jemunro** [comment]
Hmm, for some reason I was sure that if a task failed then succeeded on a second attempt it would not be picked up on resume, but testing shows that is not the case:

`nextflow.config`:
```nextflow
process {
    maxRetries = 3
    errorStrategy = 'retry'
    executor = 'local'
}
````
`test.nf`:
```nextflow
process TEST {
    cpus { task.attempt * 1 }
    tag "$x"
    
    input: 
    val x

    output:
    stdout
    
    script: 
    """
    [ "$task.cpus" -ge "$x" ] || exit 1
    echo $task.cpus
    """
}

workflow {
    Channel.of(1,2,3) \
        | TEST \
        | view { it.trim() }
}
```

`nextflow test.nf`:
```
N E X T F L O W  ~  version 22.10.4
Launching `../dynamic_resources.nf` [exotic_pike] DSL2 - revision: a49ab4882b
executor >  local (6)
[04/8921e0] process > TEST (3) [100%] 6 of 6, failed: 3, retries: 3 ✔
1
2
3
[56/b6cd74] NOTE: Process `TEST (2)` terminated with an error exit status (1) -- Execution is retried (1)
[0b/0739d1] NOTE: Process `TEST (3)` terminated with an error exit status (1) -- Execution is retried (1)
[c6/b449ee] NOTE: Process `TEST (3)` terminated with an error exit status (1) -- Execution is retried (2)
```

`nextflow test.nf -resume`:
```
N E X T F L O W  ~  version 22.10.4
Launching `../dynamic_resources.nf` [confident_ekeblad] DSL2 - revision: a49ab4882b
[04/8921e0] process > TEST (3) [100%] 3 of 3, cached: 3 ✔
1
3
2
```

**Comment by bentsherman** [comment]
Okay, I see how it works in the codebase now. Nextflow also caches the failed attempts. On a resume, Nextflow will iterate through failed attempts in the cache until it finds a successful attempt or a cache miss. Nice 😎
