### ISSUE TITLE
a tiny bug in tutorial.nf from nextflow/docs/getstarted.rst

### ISSUE THREAD

**Issue by gawxyz** [nextflow-io/nextflow#3625]
## Bug report 
a tiny bug in tutorial.nf from nextflow/docs/getstarted.rst
it causes error you can see the ### Program output 

nextflow.enable.dsl=2  
should be added first in the tutorial.nf script.

And there are some right branches fixed it.

### Program output 
 nextflow run tutorial.nf --str 'Bonjour le monde'
N E X T F L O W  ~  version 21.10.6
Launching `tutorial.nf` [admiring_wing] - revision: 89283bb31a
No such variable: stdout

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Additional context

I am just beginner and it cost my half hour doubt what I do something wrong.

**Comment by mribeirodantas** [comment]
Hello, @gawxyz. [The DSL2 syntax has become the default for a while now](https://github.com/nextflow-io/nextflow/releases/tag/v22.03.0-edge), which means you don't have to enable DSL2 syntax anymore. For a while, you had to do it for DSL1 as DSL2 became the default, but we have been past that too now. The only accepted DSL in recent versions of Nextflow is DSL2. You're using an old version of Nextflow, that uses DSL1 by default, and that's why you're running into this error. I recommend you update Nextflow, if there's nothing preventing you from using a newer version (Run `nextflow self-update`).

**Comment by pditommaso** [comment]
Solved via 1563b05a
