### ISSUE TITLE
option to resubmit long-queued tasks with smaller resource requests

### ISSUE THREAD

**Issue by notestaff** [nextflow-io/nextflow#3715]
Sometimes a job can run faster if it requests more resources (e.g. more cpus/memory or a GPU), but can also get queued longer if it requests more resources (e.g. because few cluster nodes have GPUs).  It'd be nice if Nextflow could resubmit long-queued jobs (after specified time in queue) with reduced resource requests.  The same closure-based mechanism could be used that already works for e.g. resubmitting with higher memory request in case of failure ( https://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources ).

**Comment by bentsherman** [comment]
We could add a config option like `executor.queueTimeout` so that tasks can be killed if they're in the queue for too long. By default it would cause the workflow to fail, but you could change the error strategy to retry and use dynamic resources as you say to request fewer resources.

The problem though is how to tell whether a task failed because it was queued too long or because it e.g. used too much memory. That makes the difference between requesting more or less memory on the next attempt.

@pditommaso Wondering if we could include the previous attempt exit code in the task object. You might want to increase, decrease, or keep the same task resources based on why it failed.

**Comment by pditommaso** [comment]
Something very similar was discussed for cloud execution in which jobs can queue forever due to the unavailability of spot resources. 

There's a draft implementation, I'll open a PR for it.
