### ISSUE TITLE
Document how params.modules in the config is used

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#3817]
Folks use `params.modules` in a `modules.config` to make parameters to only a specific process (by lower case process name).   See [`nf-core/bacass`](https://github.com/nf-core/bacass/blob/959967364c7c0105b5b271acf0441fa9290e0d4c/conf/modules.config#L23-L29).  I don't see this documented anywhere.

Folks can also use the `addParams` method when importing to add parameters, and specifically module parameters with `include { FOO } from '../foo' addParams(params.modules["bar"])`.  This is briefly described in the [modules parameters](https://www.nextflow.io/docs/latest/dsl2.html?highlight=addparams#module-parameters).

It would be great if `params.modules` could be fully documented, ideally in the [configuration section under the params scope](https://www.nextflow.io/docs/latest/config.html#scope-params) as well as in the above modules parameters section.  I think highlighting in the former that `addParams` can also reference these is important. 

Thoughts?

**Comment by bentsherman** [comment]
There are no built-in params, so that must be an nf-core convention. I would talk to the maintainers of that nf-core pipeline to see if they can document it somewhere for their pipeline or nf-core in general.

Modules are currently documented on the [DSL2 page](https://nextflow.io/docs/latest/dsl2.html#modules) in the Nextflow docs, but there is also a PR #3793 to create a dedicated page for Modules. Hopefully that clears things up for you.

**Comment by nh13** [comment]
@bentsherman I think I just didn't see that everyone just uses `addParams(params.modules["bar"])` and assumed it must have been a syntax thing.  I.e. if there's `params.modules`, then those are made as first-class params to the included module..  I am now thinking it's used so often it could be added to the language.  What do you think?

**Comment by bentsherman** [comment]
I'm not sure what it would mean to "add" it to the language. It's already supported by the language, but it's a convention, one of many possible conventions that someone might use. We wouldn't want to restrict users unnecessarily just because a plurality of users do things a certain way.

I think this feature is covered by the documentation on `addParams`, but if you think it could be expanded upon in some useful way, you're welcome to submit a PR 😄

**Comment by mribeirodantas** [comment]
For people looking into this issue in the future, that's the [new] current nf-core convention for modules args: https://nf-co.re/docs/contributing/modules#new-module-guidelines-and-pr-review-checklist
