### ISSUE TITLE
HEAD is detached error

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#389]
When running a pipeline specifying a revision different from the current one, the following error may be reported: 

```
DEBUG nextflow.cli.Launcher - Operation aborted
org.eclipse.jgit.api.errors.DetachedHeadException: HEAD is detached
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:202)
	at nextflow.scm.AssetManager.download(AssetManager.groovy:574)
	at nextflow.scm.AssetManager.download(AssetManager.groovy)
	at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:280)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:197)
	at nextflow.cli.Launcher.run(Launcher.groovy:410)
	at nextflow.cli.Launcher.main(Launcher.groovy:564)
```

**Comment by pditommaso** [comment]
This may be related to #233

**Comment by rspreafico** [comment]
I am getting something similar with the following workflow:

1) Run a pipeline from a Git repo specifying a commit ID, e.g.

`nextflow run http://my.git.repo/pipelines/my_pipeline.git -hub gitlab -r e67ac082`

Run again the same pipeline on different input files:
```
nextflow run http://my.git.repo/pipelines/my_pipeline.git -hub gitlab -r e67ac082

N E X T F L O W  ~  version 0.24.4
Pulling pipelines/my_pipeline ...
HEAD is detached
```
This issue can be solved by deleting `~/.nextflow/assets/my_pipeline` and then re-executing Nextflow

**Comment by pditommaso** [comment]
@rspreafico Are you able to reproduce the error?

**Comment by pditommaso** [comment]
Maybe related to https://stackoverflow.com/questions/12614631/jgit-branch-checkout-issue

**Comment by rspreafico** [comment]
@pditommaso Yes it happens consistently

**Comment by pditommaso** [comment]
Could you provide me the exact commands sequence or a test case, so I can debug it?

**Comment by rspreafico** [comment]
We access the pipelines through our organization's internal Gitlab server, so I can't provide an identical test case. The commands are literally just running Nextflow as per previous comment (I redacted the names of the pipeline and of our internal Gitlab server, but otherwise it is the command I use to run a pipeline). It happens for any pipeline as long as the `-r` option is used. The first time a pipeline is run with `-r`, no problem. Then it gets cached into the `assets` subfolder of `~/.nextflow`. When re-executing the same pipeline again with `-r`, it the pipeline is already present in `assets`, I get the `HEAD is detached` error. If I call a pipeline with `-latest` instead, no errors. It has happened consistently with any Nextflow version so far.

**Comment by pditommaso** [comment]
No way. I can't manage to replicate it.

**Comment by msmootsgi** [comment]
I'm able to reproduce with 0.25.6.  I believe this is a result of using git tags and the `-latest` flag.

 Here's the command:
```
nextflow run http://zzzzzzz/SGI-Pipelines/nextflow_test -resume -hub gitlab -r 1.0.2 -latest -params-file params.yaml
```
The first time this runs, everything works.  The second time I get the detached head exception above.

If I change the `-r 1.0.2` to `-r master` I'm able to repeatedly run the pipeline.

If I leave `-r 1.0.2`, but omit the `-latest` flag, I can run the pipeline repeatedly.  

When I go to the `~/.nextflow/assests/SGI-Pipelines/nextflow_test` dir after running with `-r 1.0.2` and do a `git pull` it will fail.  If I change that command to `git pull origin 1.0.2`, then it works.

Maybe the right solution is to always run `git pull origin <value from -r>` instead of `git pull`?

**Comment by msmootsgi** [comment]
Sorry I can't point you to actual code!  I think you should be able to reproduce with any pipeline as long as it has a tag.

**Comment by pditommaso** [comment]
Thanks for the detailed report! I can't look into it now. If you want to give a try to a patch you are welcome.
