### ISSUE TITLE
file() behavior changed with glob on s3 with latest edge release compared to latest stable release

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/nextflow#4081]
### Expected behavior and actual behavior

`file()` used to work with globs on s3 buckets, but no longer with the latest edge release.

Issue was noticed while trying to reproduce issues with the nf-core/proteinfold pipeline.

### Steps to reproduce the problem

```
workflow {

ch_input = file("s3://ngi-igenomes/test-data/proteinfold/db/alphafold_mini/small_bfd/*")

println ch_input

}
```

### Program output 

```
export NXF_VER=23.04.2; nextflow run .
N E X T F L O W  ~  version 23.04.2
Launching `./main.nf` [magical_planck] DSL2 - revision: b71c613cc3
[/ngi-igenomes/test-data/proteinfold/db/alphafold_mini/small_bfd/bfd-first_non_consensus_sequences.fasta]
```

```
export NXF_VER=23.06.0-edge; nextflow run .
N E X T F L O W  ~  version 23.06.0-edge
Launching `./main.nf` [lonely_wozniak] DSL2 - revision: b71c613cc3
[]
```

### Environment 

* Nextflow version: [?] 
* Java version: [?]
* Operating system: [macOS, Linux, etc]
* Bash version: (use the command `$SHELL --version`)

### Additional context

I think we should be using `Channel.fromPath()` in that case, but wondering if this change of behavior of `file()` is expected or not.

**Comment by drpatelh** [comment]
We have just observed the same behaviour again with nf-core/viralrecon as reported in https://github.com/nf-core/viralrecon/issues/385

Works with `23.04.2` and fails with `23.07.0-edge`. Be good to know whether this change was intentional or is a bug because it will mean current versions of pipelines will break if a backward-compatible fix isn't pushed to NF.

**Comment by pditommaso** [comment]
Too bad, looking into it
