### ISSUE TITLE
Misleading command line parameter type conversion

### ISSUE THREAD

**Issue by fujimuramasa** [nextflow-io/nextflow#434]
using strings combining a float number and lower case 'm' as input parameter will be recognized into time datatype.for example:
`println(params.size)`
if I type `--size 1.2m`, it would print `1m 12s` out.
Anything I could do to prevent this happening?
Cheers.

**Comment by pditommaso** [comment]
Oops, this looks a bug in the command line option interpreter. Right now, the only workaround it to strip the `m` on the command line option and then append it in the script. For example:  

```
size_value  = "${params.size}m" 
```

**Comment by pditommaso** [comment]
The problem here is that the command line parser tries to convert command line parameter strings to the corresponding object types. This makes sense for number and boolean, but does't make much sense for time/duration value which may result in weird conversion like the one reported above. 

This automatic conversion will be removed starting from release `0.26.x`
