### ISSUE TITLE
glacierAutoRetrieval doesn't work

### ISSUE THREAD

**Issue by berguner** [nextflow-io/nextflow#4511]
### Expected behavior and actual behavior

I tried running `nf-core/demultiplex` pipeline on a data that is stored on S3 Glacier Deep Archive but it failed. I had already restored an illumina run folder using AWS CLI from S3 Glacier Deep Archive and set `aws.client.glacierAutoRetrieval = true` but I am still getting the error below.

### Program output 

```
Object is of storage class GLACIER. Unable to perform download operations on GLACIER objects. You must restore the object to be able to perform the operation. See aws s3 download help for additional parameter options to ignore or force these transfers.
```

### Environment 

* Nextflow version: 23.10.0.5889
* Java version: openjdk version "11.0.20.1" 2023-08-24
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

I tried downloading the files with AWS CLI to make sure that they were actually restored and I had to enable the `--force-glacier-transfer` in order to recursively download. Could it be that this option wasn't enabled by Nextflow?

**Comment by bentsherman** [comment]
Can you share the entire log please?

**Comment by berguner** [comment]
Here is the log file:
[nextflow_aws-glacier-auto-retreival-err.log](https://github.com/nextflow-io/nextflow/files/13345816/nextflow_aws-glacier-auto-retreival-err.log)

**Comment by bentsherman** [comment]
I think it is failing because we never implemented the Glacier auto-retrieval for tasks

@pditommaso if I recall correctly, we only implemented the glacier restore for the Nextflow head node because otherwise you could have many tasks doing nothing while waiting for the restore. On the other hand, currently the only way to trigger the glacier restore is to download the entire file to the head node.

What would be ideal is a way to only trigger the glacier restore from the head node before launching the tasks, let the head node do all the waiting, and then launch new tasks only when their inputs are restored

**Comment by pditommaso** [comment]
Glacier restore can take ages, I think it makes no sense to run hundreds of task hanging for the data to be available

**Comment by berguner** [comment]
Yes, tasks shouldn't wait for restoring to be completed. It would be an amazing feature if the head node could check the restoration status once every set interval (i.e. every hour) and launch the tasks once the files are restored. According to the [AWS documentation](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-s3-restore-status-s3-glacier-objects-list-api/), it should be possible to query the restoration status of the files, so head node wouldn't have to download the files.

**Comment by bentsherman** [comment]
@berguner as a workaround, you could read the first line of each file ([docs](https://nextflow.io/docs/latest/script.html#advanced-file-reading)) you want to restore in  the Nextflow code. That should trigger the restore, then you can pass the files to the tasks and they will run as normal. For example:

```groovy
input_files = files('*.fastq')
input_files.each { file ->
  file.withReader { it.readLine() }
}

workflow {
  Channel.of(input_files) | MY_PROC
}
```

Of course this requires you to modify the pipeline code, and this particular example isn't ideal because it will wait for each file one at a time. If instead you read the first line in the process body, that should restore all the files in parallel

**Comment by bentsherman** [comment]
It might be easier to just run a script before the pipeline execution (or as a step in the pipeline) that restores all the input files you want to retrieve from glacier.

**Comment by bentsherman** [comment]
> I already tried to restoring prior to running the pipeline but it still failed

What exactly did you try? You should be able to use the `aws` CLI just like the task script, but with the extra option, like this:

```bash
for file in $files; do
  aws s3 cp --force-glacier-transfer $file - > /dev/null &
done

wait
```

Although I would use the [restore-object](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/restore-object.html) to simply restore each object without downloading it

**Comment by pditommaso** [comment]
Alternatively a plugin may able to handle this

**Comment by pditommaso** [comment]
This feature has been removed https://github.com/nextflow-io/nextflow/pull/4705
