### ISSUE TITLE
Add support for Python package installer (pip) via Conda

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4664]
## Context 

A key feature of nextflow is the ability to handle task dependencies with popular package managed such as Conda and Spack.  

In the context of Python execution the most adopted one is Python package installer aka `pip`. 

The goal of this task it to provide Nextflow to handle pip package installation for processes that carry out Python based script. 

This can be easily achieved leveraging the Conda subsystem, that it's able to handle the installation also of `pip` packages from the [Python Package Index](https://pypi.org/). 

Given one or more pip packages e.g. `multiqc`, these can be installed via Conda using the following conda environment file: 

```yaml
name: multiqc-pypi
dependencies:
  - pip
  - pip:
    - multiqc
```

## Implementation 

1. Introduce a new `pip` directive that allows the user to declare a list of pip packages to be used 
2. Implement a mapping that converts the pip packages to the corresponding Conda environment 
3. Add support to Wave to container building via pip + conda.

**Comment by pditommaso** [comment]
Adding @ewels for review

**Comment by ewels** [comment]
Out of curiousity, do you think that this would work already?

```nextflow
process MULTIQC {
    conda 'pip: [multiqc]'
    // ..
}
```

**Comment by pditommaso** [comment]
nope, it should be a list of Conda packages

**Comment by bentsherman** [comment]
@marcodelapierre should be a good one for you

**Comment by ewels** [comment]
Are we not throwing away an easy win for conda users then though? If it's just a question of deciding on a syntax in Nextflow, then we can pass that on to conda in a way that it understands.

**Comment by pditommaso** [comment]
What about?

```
conda 'pip: multiqc blah blah'
```

**Comment by marcodelapierre** [comment]
I see a potential limit in Paolo's syntax suggestion, as it does not allow to mix pip and non pip packages within the directive. So what about :

```
conda 'pip:multiqc, pip:numpy, blast, samtools`
```

**Comment by marcodelapierre** [comment]
If you approve, I will aim to work on it very soon

**Comment by marcodelapierre** [comment]
Also, out of scope for this issue, but just as a natural extension. I am thinking we could add a new package provider (in addition to Conda and Spack) that uses Pyhton `pip` directly instead of Conda.

Advantages (non-exhaustive):
- Friendly and hence attractive to `pip` intensive communities (astronomers, data scientists)
- Quick install times, so easy add for both Nextflow and Wave
- Quicker than Conda for Pypi packages

Disadvantages (non-exhaustive):
- compared to conda, does not allow for mixing with non Pypi packages - however, it does target a different community
- yet another package manager in Nextflow - but worth the small effort IMHO

**Comment by ewels** [comment]
Yup, agree with the `pip:packagename` syntax for each package 👍🏻 

Having an additional `pip` installer would be nice, though needs thought about environment encapsulation. Might need to use [pipx](https://pipx.pypa.io/stable/) or related. By default `pip` will just install to the local python environment which could be system, which would be bad.

**Comment by marcodelapierre** [comment]
Yep good point Phil, either `pipx` (which I didn't know) or `venv`

**Comment by pditommaso** [comment]
I feel this is derailing from the original intent to provide a simple way to define pip \*only* dependencies. If the users need to mix Conda and Pip, they can rely on the usual Conda environment file. The above syntax is just introducing yet another way to do it. 

I think we should not also care much about local installation (which can be problematic with pip) and go ahead with Wave only support at least at this stage. The fact it relies on the Conda subsystem should be seen as a mere technical implementation detail.

**Comment by marcodelapierre** [comment]
Oh I see your point Paolo.   Indeed here we are talking of a bit of syntax sugar to achieve installation of Pip packages through the Conda installer. 

You suggest the following for `pip` only:
```
conda 'pip: multiqc pipPkg1 pipPkg2'
```

I suggest the following extension for both `pip` only and `pip`+`conda`:
```
# pip only
conda 'pip:multiqc pip:pipPkg1 pipPkg2'

# pip and conda
conda 'pip:multiqc blast samtools pip:pipPkg1 pip:pipPkg2'
```

I know mine is more verbose, but it still enable a concise way to address two realistic scenarios rather than one.  If you find it significantly more verbose, hence confusing, fair enough.

**Comment by marcodelapierre** [comment]
As regards local installation, I think it is not an issue, it is possible to leverage environments as for conda installations.

**Comment by ewels** [comment]
> they can rely on the usual Conda environment file

Following this - do we need to do anything at all? If this isn't about introducing a new syntax sugar, then we already have support for this: just use a conda env file (with _only_ pip dependencies if you want)

**Comment by marcodelapierre** [comment]
@ewels  @pditommaso  see PR #4677 for a targeted addition in the Documentation
