### ISSUE TITLE
AWSBatch: Catch API Error 500s and retry

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4709]
Every now and then, the AWS Batch API has a hiccup and throws error responses as jobs are submitted. These usually show with status codes 500. This error derails Nextflow, causing the pipeline run to be aborted.

A typical log entry below, courtesy of @sateeshperi taken [from Slack](https://nextflow.slack.com/archives/C02T97HAV5M/p1663797581252979?thread_ts=1663794255.660899&cid=C02T97HAV5M):

```
DEBUG nextflow.Session - Session aborted -- Cause: Internal server error (Service: AWSBatch; Status Code: 500; Error Code: AuthorizerConfigurationException; Request ID: .....; Proxy: null)
```

The errors themselves are from AWS. However, as they are typically transient, it would be great if Nextflow could recognise them and have some kind of retry policy that could be used. This could avoid the entire run being borked for a blip that may only last a few seconds / minutes.

We already have `aws.batch.maxSpotAttempts` and `aws.batch.maxTransferAttempts`, so I could imagine something similar here.. Maybe `aws.batch.maxSubmitErrors` or something, with a backoff strategy?

**Comment by bentsherman** [comment]
Can you share the full stack trace

**Comment by ewels** [comment]
I have one but I can't share it publicly, will send it via Slack.. 👍🏻

**Comment by bentsherman** [comment]
From the nextflow log:
```
[...] [AWSBatch-executor-1126] DEBUG nextflow.Session - Session aborted -- Cause: Internal server error (Service: AWSBatch; Status Code: 500; Error Code: AuthorizerConfigurationException; Request ID: [...]; Proxy: null)
```

It was a DescribeJobs request, which is only used by Nextflow to check the status of aws batch jobs. Likely could be addressed by wrapping this line in a try-catch:

https://github.com/nextflow-io/nextflow/blob/74c66ba6ace18f03fa9d3e7a7685c114c812944e/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy#L197

Normally I would oppose retrying 500-level errors like this, but because this code is just checking the job status, we could simply ignore the failure and wait for the next polling iteration.

**Comment by pditommaso** [comment]
Note that it's fair to retry 5xx errors because can be temporary service failure, even if it's not an 503. In wave all these are retired 

https://github.com/seqeralabs/wave/blob/abc155f2e355c601612f4b6a63fe6379f9537424/src/main/groovy/io/seqera/wave/WaveDefault.groovy#L46-L46


Also, note that client already implementes a retry policy for TooManyRequestsException, see here 

https://github.com/nextflow-io/nextflow/blob/279c410b8de69627dbb7992e37e98ad36883c180/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy#L233-L235

It should be enough to extend it to handle HTTP errors 429, 500, 502, 503, 504

**Comment by pditommaso** [comment]
Dove via 62926c28

**Comment by JoshuaEPSamuel** [comment]
Hi there, 
I was running one of my pipelines on AWS Batch, as usual, but when I checked the progress I had noticed that the Nextflow script had crashed with the same Error 500 message here - but the jobs were still running and Batch could submit new jobs.

Here is the error message:
`DEBUG nextflow.Session - Session aborted -- Cause: Internal server error (Service: AWSBatch; Status Code: 500; Error Code: AuthorizerConfigurationException; Request ID: [...]; Proxy: null)`

Background:
- I launched the same pipeline twice at the same time, with slightly different parameters
- Both pipelines crashed with the same error message, though one pipeline received the error 2 hours after the first
- The pipeline runs each process' scripts in specific Docker containers
- Using `N E X T F L O W  ~  version 24.02.0-edge` and the recursion feature
 
The script had crashed for around 4 hours before I had a look at the log, and whilst I was investigating this issue, I noticed that one of the scripts had a `hangup` signal, whilst I was reading the logs, which exited the docker container the script was running in. AWS Batch then immediately submitted another copy of the job, even though Nextflow exited hours ago - at this point I manually terminated my AWS Batch jobs.

##########################

I've got a few questions to make sure there isn't an oversight on my side:
- My config does not specify any changes to `aws.batch.maxSpotAttempts` and `aws.batch.maxTransferAttempts` - do I need to?
- The Role assigned to my (AWS) Compute Environment/Job Queue only includes policies for EC2/S3 etc - am I missing Batch policies here such as Describe/Submit job?
- Typically when I exit a running Nextflow script using AWS Batch, or if it crashes due to container errors, it terminates the jobs. I'm confused why in this case it A) Didn't terminate the jobs, and B) Submitted new jobs even though Nextflow had finished?
