### ISSUE TITLE
job schedule with dependency in slurm system

### ISSUE THREAD

**Issue by gorliver** [nextflow-io/nextflow#4770]
Nextflow submit each process after previous job finished. That means I have to keep nextflow running on the login node. The maximum time I can run a commond is 30 mins on the login node.
I wonder if nextflow can schedule all the processes using `--denpendency` or is there an alternative workaround?

**Comment by bentsherman** [comment]
It is not possible in general because Nextflow can't always know the full task graph at the beginning. If any of your processes has a glob output that can produce any number of files, or if you have dataflow logic which decides how to launch tasks based on runtime conditions, then the task graph cannot be known from the start. Only very simple pipelines could be hypothetically scheduled in this way.

**Comment by bentsherman** [comment]
Duplicate of #4068

**Comment by stevekm** [comment]
I think the solution for this problem is, more generally, to submit a SLURM job that runs Nextflow. I used a method like this in the past;

https://github.com/NYU-Molecular-Pathology/NGS580-nf/blob/master/Makefile#L351-L381

using a Makefile recipe to dynamically generate a SLURM sbatch script that would attempt to (safely) run the Nextflow pipeline.

Another great alternative to this, is to use Nextflow Tower which performs similar functionality for you.

**Comment by gorliver** [comment]
> I think the solution for this problem is, more generally, to submit a SLURM job that runs Nextflow. I used a method like this in the past;
> 
> https://github.com/NYU-Molecular-Pathology/NGS580-nf/blob/master/Makefile#L351-L390
> 
> using a Makefile recipe to dynamically generate a SLURM sbatch script that would attempt to (safely) run the Nextflow pipeline.
> 
> Another great alternative to this, is to use Nextflow Tower which performs similar functionality for you.

Thank you for the solution and Nextflow Tower. Definitely will try Nextflow Tower.
