### ISSUE TITLE
singularity.pullTimeout lack of error message

### ISSUE THREAD

**Issue by edoyango** [nextflow-io/nextflow#4823]
Hi Team,

My team has recently discovered (after a long time digging around) that Nextflow will SIGTERM `singularity/apptainer pull`s after 20mins. We've since fixed it by increasing the `singularity.pullTimeout` config. In our case, the long time taken to convert Docker images to Singularity is due to the high-latency shared filesystem we use on our cluster.

Firstly, could I get some clarification on why this is necessary? I notice that Docker doesn't have a similar config.

Secondly, is it possible to add a meaningful error message when the timeout is reached? The current error message looks like:

```
Caused by:
 Failed to pull singularity image
 command: singularity pull  --name ghcr.io-wehi-researchcomputing-haemosphere-latest.img.pulling.1710721200833 docker://ghcr.io/wehi-researchcomputing/haemosphere:latest > /dev/null
 status : 143
 message:
   INFO:    Converting OCI blobs to SIF format
   INFO:    Starting build...
   Getting image source signatures
   Copying blob sha256:9d19ee268e0d7bcf6716e6658ee1b0384a71d6f2f9aa1ae2085610cf7c7b316f

 ... skipped output ...

   2024/03/18 11:31:02  info unpack layer: sha256:e5a50e1173436b4242b02cff1322507cbd5cce18c675ea94dc11ccb6bb8e3ef0
```

Which, besides saying the pull has failed with error code 143, doesn't provide much more meaningful information. Adding more meaningful information could save others lots of time debugging. E.g. saying something to the tune of `pullTimeout of "20 mins" reached. singularity/apptainer pull terminated. Increase timeout with singularity/apptainer.pullTimeout.`.

**Comment by marcodelapierre** [comment]
Proposing a more informative error message in PR #4974 , see `hint` line below:

```
ERROR ~ Error executing process > 'sayHello (1)'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name quay.io-pawsey-openfoam-v2206.img.pulling.1714984564755 docker://quay.io/pawsey/openfoam:v2206 > /dev/null
    status : 143
    hint   : Try and increase singularity.pullTimeout in the config (current is "20m")
    message:
      INFO:    Converting OCI blobs to SIF format
      INFO:    Starting build...
      Getting image source signatures
      Copying blob sha256:dbf1d9048d1ae5ea69d3b024d7197450c8548afeccc95fb767b9b0465ad96868
      Copying blob sha256:0fb668748fc8bb961f4580895692ae741be788857ac2e8220adc2265ffb38e10
      [...]
```

**Comment by Yijun-Tian** [comment]
> Hi Team,
> 
> My team has recently discovered (after a long time digging around) that Nextflow will SIGTERM `singularity/apptainer pull`s after 20mins. We've since fixed it by increasing the `singularity.pullTimeout` config. In our case, the long time taken to convert Docker images to Singularity is due to the high-latency shared filesystem we use on our cluster.
> 
> Firstly, could I get some clarification on why this is necessary? I notice that Docker doesn't have a similar config.
> 
> Secondly, is it possible to add a meaningful error message when the timeout is reached? The current error message looks like:
> 
> ```
> Caused by:
>  Failed to pull singularity image
>  command: singularity pull  --name ghcr.io-wehi-researchcomputing-haemosphere-latest.img.pulling.1710721200833 docker://ghcr.io/wehi-researchcomputing/haemosphere:latest > /dev/null
>  status : 143
>  message:
>    INFO:    Converting OCI blobs to SIF format
>    INFO:    Starting build...
>    Getting image source signatures
>    Copying blob sha256:9d19ee268e0d7bcf6716e6658ee1b0384a71d6f2f9aa1ae2085610cf7c7b316f
> 
>  ... skipped output ...
> 
>    2024/03/18 11:31:02  info unpack layer: sha256:e5a50e1173436b4242b02cff1322507cbd5cce18c675ea94dc11ccb6bb8e3ef0
> ```
> 
> Which, besides saying the pull has failed with error code 143, doesn't provide much more meaningful information. Adding more meaningful information could save others lots of time debugging. E.g. saying something to the tune of `pullTimeout of "20 mins" reached. singularity/apptainer pull terminated. Increase timeout with singularity/apptainer.pullTimeout.`.

Hi @edoyango,

May I know how did you adjust the singularity pull.Timeout configuration during the nextflow run? i met the same issue when pull image in our share drive.

Thanks!

**Comment by edoyango** [comment]
hi @Yijun-Tian you can add singularity.pullTimeout = "1h" to your config (increase the number as needed). See the config docs for examples https://www.nextflow.io/docs/latest/reference/config.html

**Comment by Yijun-Tian** [comment]
> hi @Yijun-Tian you can add singularity.pullTimeout = "1h" to your config (increase the number as needed). See the config docs for examples https://www.nextflow.io/docs/latest/reference/config.html
Thanks for indicating this helpful reference, @edoyango! Yijun

**Comment by asp8200** [comment]
I got that error message `hint   : Try and increase singularity.pullTimeout in the config (current is "20m")` but the real problem was lack of disk space.

**Comment by Reziya** [comment]
I also have same problem and added  singularity.pullTimeout = "1h" to my config but still have same issue, i try to get the image interactive session but still failded ,does somebody know the reason and solution?

**Comment by Reziya** [comment]
````

> I got that error message `hint : Try and increase singularity.pullTimeout in the config (current is "20m")` but the real problem was lack of disk space.

did you solved the problem ?

**Comment by Reziya** [comment]
> > hi [@Yijun-Tian](https://github.com/Yijun-Tian) you can add singularity.pullTimeout = "1h" to your config (increase the number as needed). See the config docs for examples https://www.nextflow.io/docs/latest/reference/config.html
> > Thanks for indicating this helpful reference, [@edoyango](https://github.com/edoyango)! Yijun

did you solved the problem?

**Comment by marcodelapierre** [comment]
@Reziya you mention that a `1h` pulltime is not enough. I am wondering if other problems are happening, related to the container pull phase, which I understand in your case is handled by Singularity/Apptainer.

Can you provide here the error message you are getting?
 
Some containers can be quite large. Can you check how much disk space/disk quota you have available in the device where you are pulling the container?  and how much RAM memory you have as well? The outcome might give indications that you need to pull the container in a machine with more disk and/or RAM.

Another useful test that might give useful indications is to pull the container manually outside of Nextfllow, using Singularity/Apptainer directly. - You can look at your pipeline files to locate the full name of the container being pulled.

**Comment by Reziya** [comment]
Dear Dr Marco Claudio De La Pierre,
Thank you for your email.
*my config file* is : executor {
    $local {
        cpus = 40
        memory = "256 GB"
    }
}


*my script:* #!/bin/bash
ulimit -s unlimited
export NXF_SINGULARITY_CACHEDIR=/fast/AG_Ohler/Reziya/dimeloseqrun/env_test/


# #SBATCH --chdir=dimeloseqrun/                    # Start from current
directory
#SBATCH --job-name=dimeloTest2                       # Job name
#SBATCH --mem=256G                                     # Request 256GB of
memory per node
#SBATCH --time=72:00:00                              # Runtime limit (72
hours)
#SBATCH --export=ALL                                 # Export all
environment variables
#SBATCH --output=log/wf-basec.out  # Stdout/stderr
#SBATCH --error=log/wf-basec.err   # Same as output
#SBATCH --mail-type=BEGIN,END,FAIL                   # Notifications
#SBATCH --mail-user=M   # Email
#SBATCH --cpus-per-task=40
#SBATCH --gres=gpu:4                            # Request 64 CPU cores
# #SBATCH --constraint=maxg01                          # Node constraint


#source ~/.bashrc



nextflow run epi2me-labs/wf-basecalling \
  -profile singularity,discrete_gpus \
  -c basecaller_nf_config.cfg \
  -r v1.5.0 \
  --input pod5_11/ \
  --cuda_device "cuda:all" \
  --dorado_ext 'pod5' \
  --out_dir output2 \
  --basecaller_basemod_threads 8 \
  --output_fmt fastq \
  --sample_name GM12878_H3K4me3_r83_2 \
  --basecaller_cfg ***@***.*** \
  --remora_cfg ***@***.******@***.***"

*and Error* : Pulling Singularity image
docker://ontresearch/dorado:sha268dcb4cd02093e75cdc58821f8b93719c4255ed
[cache
/fast/AG_Ohler/Reziya/dimeloseqrun/env_test/ontresearch-dorado-sha268dcb4cd02093e75cdc58821f8b93719c4255ed.img]

executor >  local (1)
[-        ] wf_dorado:dorado               -
[-        ] wf_dorado:qsFilter             -
[-        ] wf_…:merge_pass_calls_to_fastq -
[-        ] wf_…:merge_fail_calls_to_fastq -
[-        ] getVersions                    -
[77/cf73d4] getParams                      | 1 of 1 ✔
[-        ] bamstats                       -
[-        ] progressive_stats              -
[-        ] makeReport                     -
[-        ] output_last                    -
[-        ] output_stream                  -

ERROR ~ Error executing process > 'wf_dorado:dorado (1)'

Caused by:
  Failed to pull singularity image
    command: singularity pull  --name
ontresearch-dorado-sha268dcb4cd02093e75cdc58821f8b93719c4255ed.img.pulling.1755173848512
docker://ontresearch/dorado:sha268dcb4cd02093e75cdc58821f8b93719c4255ed >
/dev/null
    status : 255
    hint   : Try and increase singularity.pullTimeout in the config
(current is "20m")
    message:
      INFO:    Converting OCI blobs to SIF format
      INFO:    Starting build...
      INFO:    Fetching OCI image...
      INFO:    Extracting OCI image...
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/2to3} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/bzcmp} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/bzegrep} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/bzfgrep} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/bzless} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/captoinfo} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/idle3} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/infotocap} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"
      2025/08/14 14:21:38  warn
rootless{opt/custflow/epi2meuser/conda/bin/lzcat} ignoring (usually)
harmless EPERM on setxattr "user.rootlesscontainers"

**Comment by marcodelapierre** [comment]
Hi @Reziya , from your attached outputs, I extracted the name of the Dorado container you need for your pipeline, `docker://ontresearch/dorado:sha268dcb4cd02093e75cdc58821f8b93719c4255ed`, and then manually tried to download it using Singularity/Apptainer, as I had suggested in the previous post:
```
singularity pull docker://ontresearch/dorado:sha268dcb4cd02093e75cdc58821f8b93719c4255ed
```

What I found out is that 3 layers of the container are particularly big, 2.3GB, 1.9GB and 6.1GB ... these take quite a bit to download! In my test it took 20 minutes to download the first 2, while the 3rd one is still downloading , with an estimated total time between 45 min and 1 hour.

So I have 2 suggestions for you:
- increase the time out for pulling , to 2 hours, to be safe
- in the future, consider trying to identify which commands of the automated pipeline you can try yourself manually in a shell: performing this kind of manual tests can help you in understanding the problem, identifying possible solutions and growing your skills in deploying pipeline

Please let me know how it goes!

Kind regards,

**Comment by marcodelapierre** [comment]
[update] : on first `singularity pull` attempt, the 2.3GB layer caused the pull to fail with this error:
```
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: error writing layer: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

However, on my 2nd run the pull succeeded.  The tips in my post above still hold then.

**Comment by Reziya** [comment]
Dear Dr Marco ,

Thanks for the tip! And I will really appreciate if you provide some
template about your tips , like how to add pulling time ‘2h’ in
configuration file and after pull out images in the cluster when run the
script how to give directory to image in the script ?

Thank you so much! I am really appreciate your support!

**Comment by marcodelapierre** [comment]
Let me guide you around the pullout setting. 
In the error output that Nextflow prints (see eg your attached outputs), it says:
```
hint   : Try and increase singularity.pullTimeout in the config
(current is "20m")
```

So this is the setting to change. If you need more details and context, please go to the Nextflow official documentation, and search for the setting named above, `pullTimeout`. You will see that information is in this page: https://www.nextflow.io/docs/latest/reference/config.html

Once you set a timeout that is long enough for the image to be pulled successfully, there should be no other action that you need to take for the pipeline to run successfully.

**Comment by Reziya** [comment]
Thank you marco,

But what did you say before the download image in cluster before running
the script, after downloaded how to give the directory to the image in my
job script?
Thank you!

**Comment by marcodelapierre** [comment]
Oh, I see!
I only did that for testing purposes. What I would recommend for production is to specify a longer `pullTimeout` setting in the Nextflow pipeline.

**Comment by Reziya** [comment]
Thank you .

and I found that when i try to download the image in the cluster the image
default path to the my home directory and give a error about lack of enough
space, how to deal with that ?

Thank you 1

**Comment by marcodelapierre** [comment]
Indeed, by default Nextflow uses the directory `~/.nextflow`, where `~` points to your home directory.  
Depending on how the cluster you use is setup, other paths maybe more suitable. Let me make examples below using the path `/shared` (which you will need to replace with the actual path that is relevant to your cluster).

Two possibilities come to my mind:
 
1. redefine that path using the variable NXF_HOME in your shell environment, for example in `~/.bash_profile`: `export NXF_HOME=/shared`
 
2. create the nextflow directory in that path, and then create a symbolic link inside your home:
```
mkdir -p /shared/.nextflow
mv ~/.nextflow ~/.nextflow_old
ln -s /shared/.nextflow ~/.nextflow
```

**Comment by Reziya** [comment]
Thank you so much for your support Marco .
 Your tips really helped me.

**Comment by marcodelapierre** [comment]
No worries, I am glad this helped you!

**Comment by Reziya** [comment]
I have finished basecalling ,next step is Demultiplexing,is it possible to use epi2me basecling wf to demultiplex to basecalled fastq file ?
