### ISSUE TITLE
Auto-casting behaviour of Strings to file/Path objects differs between relative and absolute paths

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nextflow#5289]
## Bug report 

A small workflow

```nextflow
process test1 {
    input: path(test)
    script: "ls ${test}"
}

workflow {
    test1(params.input)
}
```

... works when `--input /is/an/absolute/path`, but not when `--input is/a/relative/path`

### Expected behavior and actual behavior

When given an absolute path, the workflow succeeds:

```
$ bar touch test.txt
$ bar nextflow run . --input $PWD/test.txt

 N E X T F L O W   ~  version 24.04.4

Launching `./main.nf` [tender_swanson] DSL2 - revision: 68d1f13e28

executor >  local (1)
[df/72603e] test1 [100%] 1 of 1 ✔
```

When given a relative path, the workflow fails:

```
$ nextflow run . --input test.txt     
 N E X T F L O W   ~  version 24.04.4

Launching `./main.nf` [elated_hugle] DSL2 - revision: 68d1f13e28

ERROR ~ Error executing process > 'test1'

Caused by:
  Not a valid path value: 'test.txt'

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

[nextflow.log](https://github.com/user-attachments/files/16899796/nextflow.log)

### Environment 

* Nextflow version: 24.04.4
* Java version: openjdk 17.0.6 2023-01-17 LTS

* Operating system: macOS

**Comment by pditommaso** [comment]
<img src="https://media2.giphy.com/media/HoSyEAe48WBpTCmEz4/giphy.gif"/>

**Comment by bentsherman** [comment]
Dynamic cast of string to path input is implemented here: https://github.com/nextflow-io/nextflow/blob/6e866ae81ff3bf8a9729e9dbaa9dd89afcb81a4b/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1910-L1920

For static types I am still pondering whether to have an implicit cast from string to path, so that you don't have to wrap everything in `file()`. Ideally we would want to do the above validation in static analysis so that the user gets a compile-time error, but the static analysis only works if it's a string literal, not something like `params.input`.

So maybe it's better just to require explicit conversion via `file()` 🤷

**Comment by pditommaso** [comment]
Closing this. @robsyme feel free to re-open if needed
