### ISSUE TITLE
Allow to specify Kubernetes Pod template

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#531]
When executing in Kubernetes there are a large number of parameters for a Pod definition, many of which are directly relevant to running NF jobs (e.g. where the Pod is scheduled to run). Currently NF only allows to specify the image name, the cpu and the memory.
Better to allow to specify a Pod template (as json or yaml) for the process that will be used to schedule the Pod. That way the operator has full control over how the Pod is scheduled.

Also see #468

**Comment by pditommaso** [comment]
The problem with this proposal is that NF creates automatically the pod specification given task requirements, command and container. Giving the ability to inject any any pod yaml could easily break the NF container specification and at the same time  would not allow the provisioning of some setting. 

The last release provides the ability to control some pod configuration settings for each process pod, such as env variables, config maps, secret file, etc. See https://www.nextflow.io/docs/latest/process.html#process-pod. 

My proposal is to identify what pod are missing and implement a proper mapping from NF config to K8s pod spec. 

How does it sound?

**Comment by tdudgeon** [comment]
Well, not sure how flexible this would be. I can see that we'd need to keep coming back you you and asking for more properties to be added. I don't see why Nextflow can't layer the information on top of what is provided in a pod template, but then I don't fully understand how this works so I'm probably missing something.

The ability to specify environment variables, config maps, secrets and volume claims  is certainly useful. The most obvious thing that seems to be missing is labels. These are probably the most important thing to be able to specify as you need these to control which nodes the pods get deployed to and to be able to specify a pod preset. Also probably need to be able to specify `pod.spec.securityContext.runAsUser`. And maybe lot's of other things. This is why this is potentially a slippery slope.

Is is possible to define these environment variables, config maps, secrets and volume claims (and labels) globally for a pipeline (e.g. in the `nextflow.conf` file) so that they get applied to all pods?

**Comment by pditommaso** [comment]
>  I don't see why Nextflow can't layer the information on top of what is provided in a pod template, but then I don't fully understand how this works so I'm probably missing something.

Because it will possible results in possible ambiguous situations. For example, the pod spec allows the definition of many contains, if a user provide a template with two more container which one is supposed to overlap NF? then consider a property like `volumeMounts`that can contain many entries, the NF volumes should be appended to ones provide to the template or overwritten? what about possibile volume name conflicts? 

There are many corner cases like this that would require a complex ruleset to be applied that nobody will remember. It think it would be more sustainable to provide an implementation for the feature needed.  

> These are probably the most important thing to be able to specify as you need these to control which nodes the pods get deployed to and to be able to specify a pod preset.

I agree. This could be easily added as for the other pod settings. Another possibility I'm temped is to directory map a nextflow [label](https://www.nextflow.io/docs/latest/process.html#label) to a k8s pod label . 

> Is is possible to define these environment variables, config maps, secrets and volume claims (and labels) globally for a pipeline (e.g. in the nextflow.conf file) so that they get applied to all pods?

Yes, using the `k8s` scope eg 

```
k8s {
  pod = [ 
    [env:'FOO', value:'x'],  
    [env:'BAR', value: 'x']
  ]
}
```

**Comment by pditommaso** [comment]
The new [pod](https://www.nextflow.io/docs/latest/process.html#process-pod) directive allows a much more granular settings of K8s pod settings. If something is missing it could be implemented as pod setting extension.
