### ISSUE TITLE
Is there a way to find out the requested entry point (cli option -entry) from within main.nf 

### ISSUE THREAD

**Issue by vruano** [nextflow-io/nextflow#5319]
Is there a way to find out the requested entry point (cli option -entry) from within `main.nf`? 

seems that I can extract it from the command line unprocessed string using some regex solution (`workflow.commandLine`) but I wonder whether there is a smarter/cleaner way to obtain that name.

**Comment by bentsherman** [comment]
The command line string is the only way as far as I can tell. I suggest that you use a param to call different subworkflows from the entry workflow rather than specifying a named entry. Then you can just use the param instead of parsing the command line string. I suspect the `-entry` option will eventually be deprecated anyway.

**Comment by vruano** [comment]
Thanks, that answers the question.
