### ISSUE TITLE
Operator `subscribe` returns wrong results when chained and hangs at the end

### ISSUE THREAD

**Issue by siddharthab** [nextflow-io/nextflow#5354]
### Expected behavior and actual behavior

When `subscribe` is chained with another operator like `view`, some elements from the channel go to subscribe and some to `view`, but never both. As per the documentation, `subscribe` should return the source channel, thereby all elements should flow through all operators in the chain. The execution hangs after, which is a good thing in this case, because it prompts the user to look closer. Otherwise, the results would be incorrect.

### Steps to reproduce the problem

```groovy
workflow {
    Channel
        .of('foo', 'bar', 'baz')
        .subscribe { println "Subscribe $it" }
        .view { println "View $it" }
}
```

### Program output 

```
View bar
Subscribe foo
Subscribe baz
^C # Had to manually kill the process
```

### Environment 

* Nextflow version: 24.04.4 build 5917
* Java version: OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35)
* Operating system: macOS
* Bash version: zsh 5.9 (arm64-apple-darwin24.0)

### Additional context

Seems to be a duplicate of #4436, but I wanted to call out the unexpected branching behavior.

**Comment by bentsherman** [comment]
I suspect it is because `subscribe` returns the same reference to the source channel instead of a copy:

https://github.com/nextflow-io/nextflow/blob/324de3d162e476ed3bf58a9c77ae8e95e27cb3ee/modules/nextflow/src/main/groovy/nextflow/extension/OperatorImpl.groovy#L71-L74

In which case I think it could be solved with `CH.getReadChannel()`:

```groovy
    DataflowReadChannel subscribe(final DataflowReadChannel source, final Closure closure) {
        subscribeImpl( source, [onNext: closure] )
        return CH.getReadChannel(source)
    }
```

I also suspect that if you change it to view -> subscribe then it will be correct

**Comment by bentsherman** [comment]
I guess `CH.getReadChannel()` just returns the input.

`view` doesn't have this problem because it does an explicit map operation: https://github.com/nextflow-io/nextflow/blob/711864fd4fcdbf6839f0370fb609d28a003b6942/modules/nextflow/src/main/groovy/nextflow/extension/OperatorImpl.groovy#L1067-L1079

As a result, the problem goes away if you do `view -> view` or `view -> subscribe`

I think I would rather document `subscribe` as a "terminal operator" that should not be chained with downstream operators, i.e. it should only ever be at the "end" of a chain. This aligns nicely with some future improvements I have in mind.

**Comment by siddharthab** [comment]
Thank you @bentsherman. Documentation update in this case is perfect! `subscribe` does not really need to chain.
