### ISSUE TITLE
Iterate a complex workflow

### ISSUE THREAD

**Issue by rmhubley** [nextflow-io/nextflow#541]
I have found recipes for iterating a process N times, and to iterate over files within a process.  What escapes me is how to take a complex workflow containing both serial and parallel processes and iterate over it  N times.  I naively imagined I could "push" values back onto the Channel that initiates the workflow and end when a counter reaches a target value -- but alas I see why that won't work.  What is the standard practice for this?

**Comment by pditommaso** [comment]
NF uses a streaming approach in which iteration does not fit well. But this does not mean that you cannot apply the same workflow to multiple data. It only requires to parametrise your input data so that it triggers the execution of the tasks multiple time. 

For example [this workflow](https://github.com/nextflow-io/rnaseq-nf/blob/master/main.nf#L36) can be applied to any number of read pairs.

**Comment by rmhubley** [comment]
Right...but that glob expression requires the the input files are in existence at the start and not generated by a stage in the workflow itself.   Unless there is best-practice for doing this within NF I will probably just wrap NF externally with a script like so:

#!/bin/perl
my $dataFile = "foo.dat";
for ( my $i=0; $i<15; $i++ ){
  system("nextflow myworkflow.nf $dataFile");
  if ( -s "$dataFile.out" ){
     system("mv $dataFile.out  $dataFile");
  }else { last; }
}

**Comment by pditommaso** [comment]
I see. There are some trick to create a [feedback loop](https://gist.github.com/pditommaso/a7fb853e2528158b885c), but I wouldn't suggest it as a solution for your problem. 

Maybe an external loop in your case it's a better alternative.

**Comment by pditommaso** [comment]
I'm closing because there's any more feedback. Feel free to comment below if needed
