### ISSUE TITLE
nextflow-24.10.0-all dist not available 

### ISSUE THREAD

**Issue by khaug** [nextflow-io/nextflow#5451]
## Bug report 

Nextflow release 24.10.0 is downloadable as [nextflow-24.10.0-dist](https://github.com/nextflow-io/nextflow/releases/download/v24.10.0/nextflow-24.10.0-dist) but not as `nextflow-24.10.0-all`

### Expected behavior and actual behavior

Documentation references how to download a "nextflow-\<version\>-all" file from GitHub.

### Steps to reproduce the problem

For release 24.10.0 I can not locate the `*-all` file. Like this "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow-${NEXTFLOW_VERSION}-all

### Program output 

N/A

### Environment 

* Nextflow version: 24.10.0
* Java version: N/A
* Operating system: N/A
* Bash version: N/A

### Additional context

N/A

**Comment by bentsherman** [comment]
This is intentional, the `-all` release was replaced with the `-dist` release which includes fewer core plugins and works with third-party plugins, whereas the `-all` release did not.

Looks like it isn't documented here: https://nextflow.io/docs/latest/install.html#standalone-distribution

Tagging @christopher-hakkaart , we need to document this change in the release structure. It was introduced in 24.07.0-edge

**Comment by khaug** [comment]
Got it, thought that may be the case. Thanks Ben
