### ISSUE TITLE
channel.join by key

### ISSUE THREAD

**Issue by timdiels** [nextflow-io/nextflow#559]
It would be nice to have a `channel.join(channel2, by: 'key')`, I like to name my values using maps instead of passing plain lists. For example:

```
ch1= Channel.from([[species: 'a', blah: 'blah'], [species: 'b', blah: 'blahb'], [species: 'c', blah: 'blahc']])
ch2=Channel.from([[species: 'a', val: 'val'], [species: 'c', val:'cval']])
ch1
    .join(ch2, by: 'species', remainder: true)
    .view()
```

with as output

```
[species: 'a', blah: 'blah', val: 'val']
[species: 'b', blah: 'blahb']
[species: 'c', blah: 'blahc', val: 'cval']
```

Thanks in advance

**Comment by LukeGoodsell** [comment]
Agreed. I'm currently using boilerplate such as below to accomplish this, but it's a little clumsy. I also need it to be paranoid - raise exceptions if there isn't exactly one match per channel or keys are duplicated between channels.

```
channel1 = Channel.from([
    ['mykey':'A', 'myval': 'asdf'],
    ['mykey':'B', 'myval': 'zxcv']
])

channel2 = Channel.from([
    ['mykey':'B', 'otval': 'qwer'],
    ['mykey':'A', 'otval': 'uiop']
])

mergedchannel =
    channel1
    .concat(channel2)
    .groupBy({item -> item.mykey })
    .flatMap({item ->
        item.collect { mykey, entries ->
            assert entries.size() == 2 : "Unpaired join for ${mykey}"
            mergedItem = [:]
            mergedItem.mykey = mykey
            entries.each { entry ->
                entry.each { key, val ->
                    if(key == "mykey") return;
                    assert ! mergedItem.containsKey(key) :
                        "Duplicate values of ${key} for ${mykey}"
                    mergedItem[key] = val
                }
            }
            return mergedItem
        }
    })
    .map({ println(it); it })
```

... which outputs:

```
[mykey:A, myval:asdf, otval:uiop]
[mykey:B, myval:zxcv, otval:qwer]
```

Is this planned/underway? If not, I'll see if I can modify `JoinOp.groovy` to do this for us.

**Comment by pditommaso** [comment]
The `join` operator already supports `by` parameter. This feature request is proposing to extend the `join` semantic to element that are maps instead of tuples and therefore the `by` usage to map entry instead of tuple positional index. 

This can be tricky and above all not sure on the impact when chaining it with other operators/processes.

**Comment by pditommaso** [comment]
> I take it from your comment that you'd favour creating a new plugin/operation distinct from join for joining map-based channels?

No, it can be even implemented by the current `join` operator. What I mean is that it's needed a careful assessment of the impact of the usage or associative arrays over tuples for all the remaining operator and the process input/output semantic. See for example #343.

**Comment by multimeric** [comment]
While we wait for this, here's my attempt at a clean function for doing this in DSL2:

```groovy
nextflow.enable.dsl=2

def map_join(channel_a, channel_b, key){
    channel_a
        .map{ it -> [it[key], it] }
        .join(channel_b.map{it -> [it[key], it]})
        .map { it[1] + it[2] }
}

workflow {
    a = Channel.from(
        [a: 'abc', b: 123],
        [a: 'def', b: 456],
    )
    b = Channel.from(
        [a: 'def', c: true],
        [a: 'abc', c: false],
    )
    map_join(a, b, key: 'a').view()
}
```
```
[a:abc, b:123, c:false]
[a:def, b:456, c:true]
```

The idea is that we first pull out the "key" from each map, making each channel into an `(Object key, Map value)` tuple, allowing us to use the normal `join()` method that only works on tuples, then we add together the maps with the `+` operator (so any key in `channel_b` will override the same key in `channel_a`; order matters). 

Since this is DSL2 you can also just put that function into a module and import each time you need it.

**Comment by ilya-kolpakov** [comment]
Nowadays data is often kept as JSON objects which are nicely parsed as maps. Converting them to tuples and using numeric indices instead of human-readable keys is insanity IMO. I can't quite comprehend the decision to deprecate `groupBy` and to not implement the join by `keys`, but I guess there might be technical reasons.

**Comment by multimeric** [comment]
I looked into implementing key join myself but the join operation is already spread across several classes and methods, it's really quite hard to understand. So although it should be a simple feature I can see why it hasn't happened yet!
