### ISSUE TITLE
Optional container hash when calculating cache key

### ISSUE THREAD

**Issue by fmorency** [nextflow-io/nextflow#562]
Fix for issue #443 adds container cache when calculating the cache key. However, some circumstances such as

 - long running pipeline ending in an easily fixable error
 - run part of a pipeline using a container and the rest using another (ie. process the data while waiting for a new feature)

would benefit in having a mechanism to skip hashing the container.

**Comment by pditommaso** [comment]
Still think that a new container should result in a new computation, if you don't want that you can just avoid to give the container image the same name/tag. 

Also because adding this flag, it should be added a flag to disable the the same behaviour for a different environment module #627, then also for a bioconda #493 when it will be supported.

**Comment by pditommaso** [comment]
Good. @msmootsgi does this solution works also for you?

**Comment by msmootsgi** [comment]
Yes, I think I can manage this.

**Comment by pditommaso** [comment]
Nice. If so I'm closing this issue.
