### ISSUE TITLE
Remove support for DRMAA

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#587]

**Comment by stevekm** [comment]
hey just wondering, does this mean you are planning to remove support for DRMAA in upcoming versions of NextFlow? Are there any details surrounding this and how it would impact HPC cluster integration?

**Comment by pditommaso** [comment]
The DRMAA (1.0) implementation for Java is very poor and difficult configure. I have notice of only one user using it. Nextflow uses native tools to interface with HPC batch schedulers. Are you using DRMAA with NF?

**Comment by stevekm** [comment]
"Nextflow uses native tools to interface with HPC batch schedulers." Then I guess I am not using DRMAA after all then; I had assumed that Nextflow was using DRMAA under the hood but I guess that's not the case? My biggest concern was the continued native support for multiple HPC schedulers. I had tried to use the [DRMAA Python](https://github.com/pygridtools/drmaa-python) wrapper library but also found it [difficult to configure](https://github.com/pygridtools/drmaa-python/issues/61). Had also developed my own [native solution](https://github.com/NYU-Molecular-Pathology/util/blob/master/qsub.py) for SGE as well, but Nextflow's implemention so far has been better than both.

**Comment by pditommaso** [comment]
> Nextflow's implemention so far has been better than both.

One reason more in favour to remove DRMAA.

**Comment by stevekm** [comment]
Is there a description of the internal methods that Nextflow uses for this instead?

**Comment by pditommaso** [comment]
The target scheduler cli tool such as `sbatch` `squeue`, etc. have a look at executors code https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/SlurmExecutor.groovy

**Comment by iamh2o** [comment]
I feel like the reason for using DRMAA and it's existence might not have been grok'd?  It's whole purpose was to provide a direct API to he numerous HPC systems and abstracts away the need to manage LSF, qsub, bsub,sbatch,pbs,etc.    Further, DRMAA is 'retired' in favor of DRMAA2 since 2012 with v2 greatly enhanced.   DRMAA also being more performant than wrapping each systems unique CLIs, and less error prone.   I'm surprised this hasn't been a sticking point as it's pretty widely leveraged.  [Even outside HPC now, for interfacing with Docker, Kubernetes...](https://github.com/dgruber/drmaa2os).    

4 years though- if no one has missed it, you're doing something right :-)

**Comment by pditommaso** [comment]
Besides we great work made by @dgruber, I see very little adoption of DRMAA API grid scheduler vendors. Much easier just wrapping CLI tools such `qstat`, `qsub` etc

**Comment by iamh2o** [comment]
I see a debate regarding the pros/cons of wrapping multiple  diffeerent vendor CLI calls vs. adopting a uniform single API as really only going in one direction. Just on basic principles of reduced complexity and portability a single API would wim in mmy mind at least.  But then the API also expands greatly on the capabilities of the CLIs, and make them more consistent.  
But, if no one cares to look at the executor at play and it works, eh. Maybe moot point?  

This was my position, but then started to run analyses with 100,000++ jobs, and I can verify thousands of calls to qstat qacct etc will all of a sudden catastrophically fail. And when this happened, I had the good fortune to recover by changing `--cluster qsub` to `--drmma `. whew.  I found this thread b/c I want to give NF a shot, but am skeptical my large jobs will be managed via qsub/qacct/qstat better somehow by NF that via SNKMK.   It's a pretty simple (and inefficient CLI, I would anticiplate the same outcome).  If I find success unexpectedly, I'll surely share the news.

Adoption is so widespread, and the DRMAA1 spec so effective, I think it may obscure it's popularity.  At least in Biology HPC, it's generally considered a given to be available, and is a rare example of a consortium API out performing and enabling features the vendor CLIs do not.  Most of the time, I would expect that no one even thinks about the specifics of the executor being used

**Comment by dgruber** [comment]
Interesting discussion and thanks for referencing my project :). It is purely focussed on Go as Go plays also pretty well with C (compared to Java, like mentioned above) and is nice to work with.

Both ways interacting with the backend, using cli wrapper or API, are valid and must not exclude each other. Behind the standardized API I actually used both. That way both can complement each other but _in front_ of a standardized API.

Like @iamh2o mentioned, drmaa (v1) is extremely efficient, the fastest way to inject huge amount of jobs into a cluster but it lacks in features / functionalities, only targeted to a single app which takes care about its own jobs. No way of building a  monitoring tool. The drmaa2 feature set tried to add missing functionality found after a survey (increasing the amount of functions from 30 to around 100), especially adding monitoring and multi-job session capabilities around a more object oriented model. Unfortunately the HPC workload manager vendors didn't pick it up. Univa (now Altair)  is the only vendor providing a supported C drmaa2 implementation. Implementation was challenging as the API's view changed more towards a users perspective rather than being very close to the workload managers internal API. Seeing others starting but not finalizing.

Nevertheless engineering jobs (which I currently work with) take usually many hours so performance does not matter so much but drmaa still makes lot of sense. But more interesting are meanwhile "newer" workload managers, like Kubernetes. The submission performance drops down by another factor even when using the native APIs. Not sure if s.o. would like to wrap kubectl.

I see the big plus of drmaa at decoupling workload from the execution backend and also have a common job specification template. Jobs are such a universal concept. No need to start each time from scratch when building a job model. A DRMAA2 job can easily represent dynamic infrastructure as well (infrastructure jobs). We successfully applied that concept to whole Kubernetes clusters (non-open source), i.e. being able to create, monitor, and manage Kubernetes clusters as DRMAA2 jobs (and of course the workload inside the clusters and containers as DRMAA2 jobs as well).  Due to the extensibility of the structures so far everything could be accomplished. Even resizing the infrastructure can be represented as a job even not directly specified in DRMAA2. Having a single, simple state model across different components (different infras _and_ workload running on the infrastructure) is also very helpful, rather looking up the differences each time. But that's I believe far away from what is discussed here.

Anyone who is interested in a universal Go version of DRMAA2 is absolutely invited to contribute to https://github.com/dgruber/drmaa2os

I'm pretty sure when you try it out you immediately stumble across some issues, please report them.

For me it does what I need it for...

**Comment by iamh2o** [comment]
My company is moving to nextflow & one of our executors will be UGE.  I had written a lof of Snakemake workflows using the approach of wrapping qsub and qacct.  If you're running small workflows of a few 100 jobs,  tracking job status wrapping the CLI is probably starting to get annoying... at 100K this begins to be a 'choose a new technology' level problem as jobs go MIA largely not due to failing to be picked up, but b/c the CLI for monitoring jobs was never intended to be an API for machines, but occasional use by people, and as an API, it performs as your expect, terribly.  

I had ended up building the most rube goldbergian job status script(qstat, failing back to qacct- which had a kill timer on it b/c it will sometimes never return), failing back to a local DB I recorded what I knew of the job, and finally would flip a coin .  Then realized what drmaa was, and have not lost a job since & needed no submit or status scripts ( portable to other drmaa systems to boot -dead horse kicked-).

Maybe I'm talking myself into taking a stab at enabling 2.0 :-). I do not think perfection is required (or healthy to purse even), if it covers the drmaa 1 features it'd be, i'm sure, and improvement over monitoring large #s of jobs via qacct.  Or maybe there is an UGE trick I am still unaware of.

Speed of submission and scheduling is quite important when dealing with large 'N'-  ot can translate to days of unnecessary time.

I'll peek at the go project to!
