### ISSUE TITLE
Nextflow on Homebrew

### ISSUE THREAD

**Issue by sjackman** [nextflow-io/nextflow#620]
I've opened a PR to submit Nextflow to Homebrew/core.
See https://github.com/Homebrew/homebrew-core/pull/24367

**Comment by pditommaso** [comment]
Hi Shaun, despite Homebrew is a super tool, I've decided to not support it directly. Mainly because NF it's so easy to install that it does not require a package manager and for me it's an extra manual step to manage. I'm only providing a formula for conda because they also automatically package it in a docker/singularity container which can be useful in some contexts.

**Comment by sjackman** [comment]
Fair enough.
