### ISSUE TITLE
Cannot use def to scope variable in process

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#678]
Trying to define a variable with `def` in a `process` scope casues the following error:
```
No such property: x for class: Script.....
```
Tested with the following example:
```
a = Channel.from("a".."z")

process testA{

    input:
       val letter from a
    shell:
        def b = "this is the letter: ${letter}"
        '''
        echo !{b}
        '''

}
```

**Comment by pditommaso** [comment]
I think this is an interesting corner case and potentially an inconsistency in the syntax that should be documented. Using groovy native string interpolation that would work, but when using the `!{..}` syntax scripts variable cannot be declared locally using the `def` keyword. 

To summarise: 

* script/shell variable should be *defensively* declared in the local scope using the `def` keyboard
* do not use `def` when 
  1. the variable needs to be referenced as a `output` value
  2. the variable needs to be used in a `shell` template

**Comment by baffelli** [comment]
Interesting! Why does interpolation not work in shell templates?
 Could it be changed? I suppose it would be safer to use def everywhere (except when needed as an output)

**Comment by pditommaso** [comment]
Because the `shell` is not a native (groovy) language feature, I don't think this can be changed. I need to investigate, but there's a very low chance.

**Comment by baffelli** [comment]
I knew that ```shell``` is not a native groovy command. Is there a more consistent way of mixing shell comands and groovy string interpolation?

**Comment by pditommaso** [comment]
Nope. Anyhow following the rules in my first comment, you should be able to tackle the problem.

**Comment by darachm** [comment]
Commenting a related trick because it has a similar error. No bug, just work around if anyone finds this issue
when searching for this.

To dynamically set shell parameters based on given resources, here thinking about memory for `sort`, 
you can use the `!{task.memory}` syntax. This is fine and all, but if you have a long piped command that uses
two `sort`s, then I started to run out of memory and hang while running big batch jobs.

I could halve the value, and so I wrote some Groovy to set a shell variable using this. But it looks messy and I have
to copy and paste it into each process. 

To make this cleaner I wrote a function at the top (using `def`) that will take the cpus, memory, and number of concurrent sorts 
to dynamically calculate how much memory each sort will get. 
However when I used the `def` as above, I get a very similar error as described here. 

What worked was to use the rule above, and call the function before the shell, 
then use the `!{}` syntax to access it, sort of like this:

    shell:
        sort_parm_1 = buildSortParm(task.cpus,task.memory,1)
        sort_parm_2 = buildSortParm(task.cpus,task.memory,2)
        '''
        cat something | sort !{sort_parm_1} > output
        cat something | sort !{sort_parm_2} | other_program | sort !{sort_parm_2} > output
        '''

Just posting in case this helps anyone in the future dynamically set their command-line parameters or arguments
using a Groovy function in each process.
