### ISSUE TITLE
Add enabled to conda scope

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/nextflow#749]
I suggest adding `enabled` to the conda scope. If you define a `conda` directive at the process level it could be useful to be able turn on/off conda. 

Similar to what is currently implemented for containers e.g. `docker.enabled = true` in the config, `conda.enabled = true` would enable more portability.

**Comment by pditommaso** [comment]
Similar to `module` environment, `conda` is implicitly enabled when specified. For `container` the main reason was to allow to switch between different engines, ie. docker, singularity, etc. 

If you want to specify a conda environment without enabling it by default use a profile, eg 

```
profiles {
  withConda { process.conda = '/env.yml'  }
}
```

**Comment by KevinSayers** [comment]
I didn't think about `modules` and how they function. I think it could be useful to enable/disable anything that manages dependencies whether that be container, module, or conda. In my opinion it would be better for reproducible/portable workflows as it could reduce the need to modify a workflow that you have pulled if you aren't using the dependency management. 

Obviously this could all be avoided specifying this in the `nextflow.config` as different profiles.

**Comment by pditommaso** [comment]
> I think it could be useful to enable/disable anything that manages dependencies whether that be container, module, or conda.

Well, this is a different thing. 

> In my opinion it would be better for reproducible/portable workflows as it could reduce the need to modify a workflow that you have pulled if you aren't using the dependency management.

I agree. I guess, you are defining the `conda` deps in the main script. You should do that only for small scripts / testing purpose. In all other cases you should define the (conda) deps in `nextflow.config` file. Using a separate profile only for that allows you to enable/disable the conda support an you need. 

I'm not supporting the idea of having an `enabled` flag because that will promote that definition of conda properties in the main script file, that's not a good practice.

**Comment by ewels** [comment]
I asked @pditommaso for the same thing and got the same response 😉 In the end we switched to using config profiles to manage all of this. See for example the [nf-core/methylseq](https://github.com/nf-core/methylseq/blob/bb83fffeb621a316fa9194a7cf12ad9472d2b0ac/nextflow.config#L49-L51) pipeline:

```nextflow
profiles {
  conda { process.conda = "$baseDir/environment.yml" }
  docker { docker.enabled = true }
  singularity { singularity.enabled = true }
}
```

So now instead of doing `nextflow run -with-docker` you do `nextflow run -profile docker`. Because you can put any config in you like, you can then have the nice and consistent:
```
nextflow run -profile (docker|singularity|conda)
```

Note that profiles can be used in combination, so for example on our UPPMAX cluster we have the choice of running with `-profile singularity,uppmax` or `-profile conda,uppmax`.

I hope this helps!

Phil

**Comment by pditommaso** [comment]
Exactly!

**Comment by KevinSayers** [comment]
@ewels @pditommaso I think this should be mentioned explicitly in the docs as currently the examples all show using the `conda` directive in a process block. I have created a PR with a 'best practices' section #802  as a suggestion.

**Comment by pditommaso** [comment]
It has been added a note in the documentation. See 6f6d5c9234824647a78b6249af187684cd4f8949.

**Comment by ewels** [comment]
With the advent of DSL2 this issue is coming around to bite us again. We want to define the conda environment in the module in the process that will be imported, and not in the pipeline config that is importing it, eg:

```nextflow
process FASTQC {
    container "docker.pkg.github.com/nf-core/$MODULE"
    conda "${moduleDir}/environment.yml"
    // [...]
}
```

However, by defining it in the process like this, conda is implicitly enabled.

Supporting `conda.enabled` / `-with-conda` etc in the same way as the container engines are handled would solve this for us in the most elegant way. The process could then define the software in every possible way without requiring a separate definition in the pipeline that imports it - much better for reproducibility and stability.

We're looking at using workarounds such as `conda: if(params.use_conda) {"environment.yml"} else {null}` (suggested by @grst, untested), but obviously native support would be much better.

**Comment by pditommaso** [comment]
My main concern is breaking exiting codebase and config. What about a simple trick 

```
conda params.conda ? "/some.env" : null 
```

ps. put condition expression at the top of nf-core best practice! 😄

**Comment by pditommaso** [comment]
haven't tried, it may require parentheses eg. 

```
conda (params.conda ? "/some.env" : null)
```

**Comment by ewels** [comment]
Ok, we'll stick with the workaround for now then. Maybe we'll use `params.with-conda` so that we can have `--with-conda` and `-with-docker` 😅 (idea from @JoseEspinosa!)

**Comment by pditommaso** [comment]
-1 on the option naming! The use of `-` and `--` is already confusing for newbie users. Adding the `--` alternative to the `with-something` scheme will further increase uncertainty.

**Comment by ewels** [comment]
Yes I know, poor joke sorry 😂

**Comment by JoseEspinosa** [comment]
I have the feeling that I am not the only one that wrote`-with-conda` in my nextflow command thinking that it will just work 🤣

**Comment by ewels** [comment]
Yeah, personally I feel that the _future_ confusion caused by `-with-conda` not working in the same way as the other flags is greater than the potential confusion of changing the behaviour. But that's not my call to make.. 😄

**Comment by pditommaso** [comment]
In the future the manual Conda handling won't needed anymore. We'll automate the building of containers from Conda .. 😎

**Comment by ewels** [comment]
What about people who can't use containers though? They'll still want Conda..?

**Comment by pditommaso** [comment]
Not saying it will be removed, but IMO it will be less relevant.
