### ISSUE TITLE
No signature of method: java.lang.String.emtpy() is applicable for argument types: () values: []

### ISSUE THREAD

**Issue by kemin711** [nextflow-io/nextflow#771]
Got this message, but my code never used empty() method:

```
Caused by:
  No signature of method: java.lang.String.emtpy() is applicable for argument types: () values: []
Possible solutions: isEmpty(), every(), every(groovy.lang.Closure), notify(), dump(), any()

Source block:
    sample2poolid = loadLookup(sampletab.toString())
  poolid=sample2poolid[sampleName]
  """
  barcodeready -p $poolid $sampleName --pool-file "$ADAPTER_DIR/pool.tab"
  """
```

**Comment by pditommaso** [comment]
Include your script or an test case able to replicate the error, the complete nextflow output and the `.nextflow.log` file.

**Comment by kemin711** [comment]
I figured it out.  To help others, you have to look into the function that it is calling.  The runtime error happened when it was trying to call another function.

**Comment by jsan4christ** [comment]
@kemin711, you can definitely provide a better explanation  of your answer that is more helpful. I have the same problem:

ERROR ~ Error executing process > 'runFastQC (rFQC.120003-1020_S1_L001_R1_001)'

Caused by:
  No signature of method: nextflow.processor.TaskPath.get() is applicable for argument types: (Integer) values: [0]
Possible solutions: getAt(int), grep(), getAt(java.lang.String), grep(java.lang.Object), head(int), wait()

Source block:
  """
  fastqc -q ${in_fastq.get(0)} ${in_fastq.get(1)}
  """

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
Please advise,
