### ISSUE TITLE
Add year and timezone to log entries

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#779]
Is there a way of enabling the year and (less importantly) the timezone in the logfiles?

I'm processing the content of the logs for timing information and although not terribly important the year would be useful. The format isn't important, although ISO8601 is common. Anyway, not terribly important.

**Comment by pditommaso** [comment]
I agree that could be useful, however the logging config logic is hardcode in the [LoggerHelper](https://github.com/nextflow-io/nextflow/blob/daded334b2478596d9821fb9049f91e05fc22699/src/main/groovy/nextflow/util/LoggerHelper.groovy#L125-L182) class and it's not configurable.

**Comment by lorenzgerber** [comment]
We would have benefit of at least the year appearing in the logs too, so I did some preliminary tests by modifying the `createEncoder()` function in the `LoggerHelper` class:

` result.setPattern('%d{yyyy MMM-dd HH:mm:ss.SSS XXXX} [%t] %-5level %logger{36} - %msg%n')`.

...which seems to work and will result in something like:
`2018 Sep-13 12:13:19.497 +0800 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye`

Paolo, could you enlighten me why this would not be a feasible solution?

**Comment by pditommaso** [comment]
Sorry for the late comment. I would not like to change the default. The proper way to handle this would be giving some log config options, which may require a separare configuration file.

**Comment by lorenzgerber** [comment]
No problem Paolo... Could we solve it with a new key/value pair for a log format string in the nextflow.config file?

**Comment by pditommaso** [comment]
That should be possible but it would require to parse twice each nextflow configuration file. This would be needed because the logging config must take place *before* the workflow config is parsed.

IMO it would be better to use a separate file only for logging configuration, something like `nextflow-log.config`. 

Then the other problem is how flexible the log config should be? These was a similar discussion in the past, see for example https://github.com/nextflow-io/nextflow/issues/211#issuecomment-260773895. However at the same time I would not reinvent the wheel, because the logger subsystem i.e. Logback already implements its own [config format](https://logback.qos.ch/manual/configuration.html).

**Comment by lorenzgerber** [comment]
imho the logback config format is too low level for an average nextflow user and, correct me if I am wrong, there are not too often requests for new log features. Hence my choice would probably be to offer only a limited number of configuration possibilities based on feature requests, through a separate `nextflow-log.config` file.
I'm still a bit curious why you don't want to have the year in the default log format ;)

**Comment by pditommaso** [comment]
> imho the logback config format is too low level for an average nextflow user and, correct me if I am wrong, there are not too often requests for new log features 

I agree that logback is too low level, would be better to define a minimal set of log setting more user oriented. 

> there are not too often requests for new log features

True, but like anything else, when you are giving a setting it should be somehow flexible. For example just for this trivial request, what date format should be used? the year should be prefixed or pos-fixed? why not using ISO 8601 timestamp? and what timezone .. etc, etc. 

In this cases, better to stick on default and give the user to ability to configure how it prefer. 

> I'm still a bit curious why you don't want to have the year in the default log format ;)

What I just said above ;)


Also I'm thinking that this should be a system wide setting, therefore instead of checking a file in the current directory, would make more sense to only allow the definition in a file locate in the `$NXF_HOME/log.config` path. 

What do you think?

**Comment by lorenzgerber** [comment]
...sounds all reasonable to me. 

LOGback seems to [support](https://logback.qos.ch/manual/layouts.html#date) [SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html). Hence `$NXD_HOME/log.config' could contain a key/value pair with the value being a valid SimpleDateFormat string.

**Comment by pditommaso** [comment]
It makes sense.
