### ISSUE TITLE
DAG graph creation does not work if basename of output file is DOT language keyword

### ISSUE THREAD

**Issue by Shellfishgene** [nextflow-io/nextflow#783]
### Expected behavior and actual behavior

Expected: Produce DAG graph in file `graph.png`
Actual: Error

### Program output 
```
Jul-06 18:13:28.544 [main] DEBUG nextflow.dag.GraphvizRenderer - Graphviz error -- command `command -v dot &>/dev/null || exit 128 && dot -Tpng /scratch/nxf-8632269156005144691.dot > /foo/bar/graph.png` -- exist status: 1

Jul-06 18:13:28.544 [main] WARN  nextflow.dag.GraphvizRenderer - Failed to render DAG file: /foo/bar/graph.png
```
Graphviz error:
```Error: nxf-8632269156005144691.dot: syntax error in line 1 near 'graph'```

### Steps to reproduce the problem

Set run option `-with-dag graph.png` (or any other DOT keyword such as node, subgraph etc.)

### Environment 

nextflow version 0.30.0.4843
openjdk version "1.8.0_121"
Linux

**Comment by pditommaso** [comment]
This is happening because the workflow script file name is used as the graph name in the dot file. Likely `graph` is a graphviz reserved work. 

Relevant code [here](https://github.com/nextflow-io/nextflow/blob/daded334b2478596d9821fb9049f91e05fc22699/src/main/groovy/nextflow/dag/DotRenderer.groovy#L58) and [here](https://github.com/nextflow-io/nextflow/blob/fc00a7051129ae52f1e9301d66950000fa1f102c/src/main/groovy/nextflow/trace/GraphObserver.groovy#L61).
