### ISSUE TITLE
Suggestion: auto assign profiles based on hostname

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#792]
Just a thought that I had earlier. We usually have a bunch of different config profiles for different systems. I've previously [implemented warnings](https://github.com/nf-core/methylseq/blob/e9106e500a4a0d7685b30e6a79dfb278490d99f6/main.nf#L877-L885) that check the system `hostname` and flag if it looks like the wrong profile was used. It would be really nice if config profiles could be automatically used based on this.

A simple toy example:

`nextflow.config`
```nextflow
profiles {
  standard {
    includeConfig 'conf/base.config'
  }
  uppmax {
    auto: { host.hostname.contains('.uppmax.uu.se') }
    includeConfig 'conf/base.config'
    includeConfig 'conf/uppmax.config'
  }
  system_two {
    auto: { host.hostname.contains('.system_two.com') }
    includeConfig 'conf/base.config'
    includeConfig 'conf/system_two.config'
  }
}
```

I'm trying to generalise a little here, but hopefully you get the idea. These profiles could still be specified normally using `-profile uppmax`, but would automatically be used when the `auto` call returns `true`.

I suspect that this would prevent some of the common user errors that we see with our pipelines and make it them easier to use.

Phil

**Comment by apeltzer** [comment]
Feels like I could try to work on this one during nfhack today :-)

**Comment by ewels** [comment]
NB: `when` could be a better name instead of `auto`, as that's consistent with pipeline syntax. But minor thing. What do you mean about managing the syntax @pditommaso?

**Comment by pditommaso** [comment]
Yes, maybe `when` is slightly better than `auto`, however the tricky thing is to handle the colon character. TLDR; the nextflow config file is a [GroovyObject](http://docs.groovy-lang.org/2.4.9/html/gapi/groovy/util/ConfigObject.html) class that must be reduced to Java Map object, therefore everything must be converted to a key-value pair. 

When using the property dot notation, it's easy to understand how nested object are created, e.g. 

```
foo.bar = 1 
```

creates a `foo` map object containing the `bar:1` pair. 

When using the curly brackets notation, that code should be read as a dynamic method invocation to which it's passed the closure, then the closure set the key-value pairs in the nested pairs, eg. 

```
foo {
  bar =1 
}
```

Any identifier postfixed with a `:` is supposed to be a java/groovy label keyword, therefore it's possible to write, 

```
foo: bar = 1 
```

or 

```
foo: bar { 
  x = 1 
}  
```

In both cases `foo:` is a label preceding that statement i.e. a variable assignment or a method invocation. 

I'm not sure that's possible to write 

```
foo: {

}
```

Because that it's not a method invocation (there's no method name). I think it's reduced to a closure definition (that should be used to define the profile activation logic), but it could be tricky to handle in the config object. 

The config object is parsed using the [ConfigParser](https://github.com/nextflow-io/nextflow/blob/a1fa3475e466833209184e47fa12ecc9a33ca343/src/main/groovy/nextflow/config/ConfigParser.groovy#L92). The first goal is to understand how the `when` definition is mapped in the config object. The [ConfigParserTest](https://github.com/nextflow-io/nextflow/blob/a1fa3475e466833209184e47fa12ecc9a33ca343/src/test/groovy/nextflow/config/ConfigParserTest.groovy#L36) can help to make some experiments. 

Then once we have the auto profile information it should be enforce in the `ConfigBuilder` at [this point](https://github.com/nextflow-io/nextflow/blob/8932eb7903950b96401c19a8d2c2a606eb10ed21/src/main/groovy/nextflow/config/ConfigBuilder.groovy#L362-L364]. 

Hope it helps 😄

**Comment by ewels** [comment]
So... would this work?

```groovy
profiles {
  standard {
    includeConfig 'conf/base.config'
  }
  uppmax {
    when = host.hostname.contains('.uppmax.uu.se')
    includeConfig 'conf/base.config'
    includeConfig 'conf/uppmax.config'
  }
  system_two {
    when = host.hostname.contains('.system_two.com')
    includeConfig 'conf/base.config'
    includeConfig 'conf/system_two.config'
  }
}
```

**Comment by pditommaso** [comment]
yep

**Comment by apeltzer** [comment]
Thanks both! I'll try to fit this in at some point in the next weeks :-) Hopefully can be of help here :-)

**Comment by ewels** [comment]
FYI for googlers: we're now doing this in a custom manner in nf-core pipelines.
Config setup is [here](https://github.com/nf-core/configs/blob/d95b464e139e7a033494d7fa1eac3539e54b24bf/nfcore_custom.config#L31-L40) and function is [here](https://github.com/nf-core/rnaseq/blob/21f36a179cd23792090fbf6f612c730b263ae830/main.nf#L1267-L1286)..

Of course, a native method for doing this within nextflow as discussed above is always nicer 😉
