### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [nextflow-io/nextflow#83]
This is something I brought up some time back. Can you consider switching to ASL 2.0. Perhaps even joining the ASF?

**Comment by pditommaso** [comment]
It turns out that our institute policy is GPL, though I think we will switch to LPGL soon. Joining AFS would be challenging but it would make everything more "bureaucratic". It could make sense in case of a serious contribution or funding, otherwise in my opinion it's much better use an agile development model.

**Comment by sirinath** [comment]
Instead of LGPL please consider ASL 2.0
