### ISSUE TITLE
Config or master branch should not be used when a specific revision is specified

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/nextflow#837]
## Bug report

If a `nextflow.config` in the master branch has an error, it can cause NF to not execute even if the `nextflow.config` file in another branch is error free. 

### Expected behavior and actual behavior

Expected: The repository would use the config file from the branch even if the master branch config has errors. 

Actual: If the master branch has issues in the config it doesn't execute

### Program output 
```
Not a valid Nextflow project -- The repository `https://github.com/KevinSayers/QUARS` must contain a the script `main.nf` or the file `nextflow.config`
```

### Steps to reproduce the problem

`nextflow run https://github.com/KevinSayers/QUARS -r test`

The master branch has an error in the config, but the test branch is correct. 

### Environment 

* Nextflow version: 0.30.2
* Operating system: Linux

**Comment by pditommaso** [comment]
This is somehow expected because NF checks out the specified branch info only after the pipeline repo is cloned locally. Therefore the config in the master needs to be parsed before closing the repo to verify the existence of main script file. 

However it should be possible to fix it as you are suggesting.
