### ISSUE TITLE
Nextflow crashes with sigbus error

### ISSUE THREAD

**Issue by markberger** [nextflow-io/nextflow#842]
## Bug report 

Nextflow seems to sporadically crash with a sigbus error for me. It has happened during multiple processes in my pipeline, so I don't think it has anything to do with one specific process. I am running Nextflow with:

```
export NXF_OPTS='-Xms1G -Xmx4G'
./nextflow run my_program.nf -resume
```

I am also using the SLURM executor.

### Program output 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f22adbd8016, pid=54591, tid=0x00007f2270ed0700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x154016]  __memmove_ssse3+0x27f6
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /scratch/users/mjberger/linacc-nf/hs_err_pid54591.log
Compiled method (nm) 4034851 2805     n 0       sun.misc.Unsafe::copyMemory (native)
 total in heap  [0x00007f22996ab9d0,0x00007f22996abd40] = 880
 relocation     [0x00007f22996abaf8,0x00007f22996abb40] = 72
 main code      [0x00007f22996abb40,0x00007f22996abd40] = 512
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

### Steps to reproduce the problem

Unclear

### Environment 

* Nextflow version: version 0.31.1 build 4886
* Java version: java version "1.8.0_131"
* Operating system: linux

[hs_err_pid54591.log](https://github.com/nextflow-io/nextflow/files/2307402/hs_err_pid54591.log)
[nextflow.log](https://github.com/nextflow-io/nextflow/files/2307416/nextflow.log)

**Comment by pditommaso** [comment]
> Failed to write core dump 

This is suspect. I've seen this genre of error when there's not enough disk space in the local storage.

**Comment by markberger** [comment]
I've looked into this and the error seems to have been from a disk space error. Thank you for your help!

**Comment by robsyme** [comment]
I've been chasing down this SIGBUS for a few weeks, but have cornered the error into a slightly different position.

One of the login nodes to our cluster had some network problems and the infiniband connection degraded into gigabit, which had subtle implications for the lustre networked filesystem. 

The Nextflow cache uses LevelDB to track runs inside the .nextflow directory. To improve random access reads, it uses mmap to lazily read the file into memory. It is my understanding that lustre supports mmap, but under degraded network conditions, reading the file into memory seems to fail, which triggers the SIGBUS as shown above.

The workaround is to either: 
1) Annoy our cluster admins into having networking that never fails, or
2) Forcing LevelDB to use FileChannelTable instead of memory-mapped files:

```
NXF_OPTS="-Dleveldb.mmap=false" nextflow run hello
```

An interesting question might be "Does Nextflow really need memory-mapped LevelDB to track the runs?" Perhaps it might be worth using FileChannelTable by default to sidestep problems caused by flaky underlying filesystems.

**Comment by lindenb** [comment]
@pditommaso thank you for the quick answer. unfortunately setting `NXF_OPTS="-Dleveldb.mmap=false"` didn't fix the  problem on my side. 


My old laptop is quite slow for I/O, I wonder if there would be an underlying `timeout` problem ?

**Comment by pditommaso** [comment]
>  I wonder if there would be an underlying timeout problem ?

No idea. Hopefully upgrading to the latest version of DB library should fix the problem.

**Comment by robsyme** [comment]
I haven't been able to replicate this error since upgrading to nextflow v20.02.0. Thanks @pditommaso!

**Comment by poquirion** [comment]
@robsyme Sadly I am also having a similar error with nexflow 20.04.1. Copying the .nexflow directory from the share file system to the local ssh does solve the problem
