### ISSUE TITLE
`nextflow config` doesn't parse main.nf

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#876]
When running `nextflow config`, things defined in `main.nf` are not picked up. For example:

`main.nf`:
```nextflow
params.one = 'this is defined'
```

`nextflow.config`:
```nextflow
params.two = 'this is also defined'
```
```
$ nextflow config .

params {
   two = 'this is also defined'
}
```

This can be a little confusing sometimes, if the config is split between the two.

Phil

**Comment by drpatelh** [comment]
This came up again yesterday because `nf-core lint` is set to only parse `nextflow.config` for the standard parameters we require to be defined in the template. e.g. I have actually defined the standard parameter in `main.nf` because it's a mandatory and doesn't necessarily need to be initialised in `nextflow.config`.

**Comment by ewels** [comment]
@pditommaso - is this issue affected by #889?

**Comment by pditommaso** [comment]
Unfortunately no.
