### ISSUE TITLE
Method numLines() or similar on file object

### ISSUE THREAD

**Issue by micans** [nextflow-io/nextflow#972]
## New feature

I would appreciate a method `numLines()` on a file object that returns the number of lines in the file.

## Usage scenario 

For a large number of samples, I use `collectFile()` to create a metafile of input files (one file name per line). I would like to use e.g. something like
`memory { (4 + (input.numLines() % 1000)) * 4.GB }`

This is just one possible use case though; when asking about this on the gitter forum, I was given a number of different ways of doing this (https://github.com/stevekm/nextflow-demos/blob/master/filter-channel/main.nf). A native implementation would be efficient, useful, and idiomatic.

**Comment by pditommaso** [comment]
Actually already exists a set of undocumented (and deprecated) built-in functions to count records in basic data structures: 

* `.countText()`
* `.countFasta()`
* `.countFastq()`
* `.countCsv()`

Maybe I should deprecate the deprecation and include in the documentation. However this wont' work in the process context, because the file content cannot be read there. The record count should applied beforehand with a map and then evaluated in the process context.

**Comment by micans** [comment]
`countText()` returns the number of lines I see. Thanks! I tried it, it works, with a deprecation message. This snippet gives me the metafile of file inputs plus the number of lines stuck in a value:
```
ch_input
  .collectFile { file -> file.collect{ it.toString() }.join('\n') + '\n' }
  .map { [it.countText(), it] }
  .view()
  .set{ ch_merge }
```
It's useful I think, especially in conjunction with the `memory` directive. Although `countText` is not entirely intuitive, `countLines` would be clearer. Anyway, I vote for dedeprecating `countText`!

**Comment by pditommaso** [comment]
+1 to promote these method officially in the NF API. Thinking to replace `countText` and `countCsv` with just `countLines()`.
